### ISSUE TITLE
Symbolic shifts don't work with small-size index

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#103]
In Cryptol, we use `sbvShiftLeft` and `sbvShiftRight` to implement symbolic shifting. If a symbolic index of width n is used to shift a bitvector of width greater than 2^n, then SBV generates SMT-Lib output with inconsistent assertions. (See also GaloisInc/cryptol#158.)

    Cryptol> :sat \(i:[2]) -> (1:[8]) << i == (1:[8]) << i
    Unsatisfiable.
    Cryptol> :set prover=offline
    Cryptol> :sat \(i:[2]) -> (1:[8]) << i == (1:[8]) << i
    Writing to SMT-Lib file standard output...
    To determine the satisfiability of the expression, use an external SMT solver.
    ; Automatically generated by SBV. Do not edit.
    ; Created on Wed Jan 14 13:56:19 PST 2015
    (set-option :produce-models true)
    (set-logic QF_UFBV)
    ; --- uninterpreted sorts ---
    ; --- literal constants ---
    (define-fun s_2 () Bool false)
    (define-fun s_1 () Bool true)
    (define-fun s1 () (_ BitVec 8) #x01)
    (define-fun s2 () (_ BitVec 8) #x02)
    (define-fun s3 () (_ BitVec 8) #x04)
    (define-fun s4 () (_ BitVec 8) #x08)
    (define-fun s5 () (_ BitVec 8) #x10)
    (define-fun s6 () (_ BitVec 8) #x20)
    (define-fun s7 () (_ BitVec 8) #x40)
    (define-fun s8 () (_ BitVec 8) #x80)
    (define-fun s9 () (_ BitVec 8) #x00)
    ; --- skolem constants ---
    (declare-fun s0 () (_ BitVec 2))
    ; --- constant tables ---
    (declare-fun table0 ((_ BitVec 2)) (_ BitVec 8))
    (assert (= (table0 #b00) s1))
    (assert (= (table0 #b01) s2))
    (assert (= (table0 #b10) s3))
    (assert (= (table0 #b11) s4))
    (assert (= (table0 #b00) s5))
    (assert (= (table0 #b01) s6))
    (assert (= (table0 #b10) s7))
    (assert (= (table0 #b11) s8))
    ; --- skolemized tables ---
    ; --- arrays ---
    ; --- uninterpreted constants ---
    ; --- user given axioms ---
    ; --- formula ---
    (assert ; no quantifiers
       (let ((s10 (table0 s0)))
       s_1))
    (check-sat)

Both `sbvShiftLeft` and `sbvShiftRight` are implemented using `select`, which (if I understand correctly) generates the SMT-Lib tables. I expect a similar problem would arise any time `select` is used with an index of width n, and a list of m > 2^n alternatives.

**Comment by brianhuffman** [comment]
Here's a more concrete example that uses only standard types from the SBV library:

    Prelude Data.SBV.Bridge.CVC4> let xs = take 257 (cycle [true, false, true]) :: [SBool]
    Prelude Data.SBV.Bridge.CVC4> sat (select xs false :: SWord8 -> SBool)
    Unsatisfiable

It works just fine with an index type of `Word16` instead of `Word8`, or with fewer than 257 list elements.

**Comment by LeventErkok** [comment]
Thanks for the report Brian.. This was a subtle but long standing bug indeed. Commit https://github.com/LeventErkok/sbv/commit/b1887b48a58d84dd5487a0c0e910cde6a62a20e1 should fix it; can you give it a try?

**Comment by brianhuffman** [comment]
The latest commit fixes the problem on the Cryptol side. Thanks for the quick response!

**Comment by LeventErkok** [comment]
@brianhuffman: Glad it's taken care of! I'll make an official SBV release later today.

We should really talk about getting the changes Cryptol needs into Cryptol so you guys can just "import" it from Hackage..
