### ISSUE TITLE
Support user-defined word types of new sizes (e.g. Word4, Word128)

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#104]
I created a Haskell module that defines a `Word4` type, with instances of all the standard Haskell classes (`Eq`, `Ord`, `Bounded`, `Enum`, `Num`, `Integral`, `Bits`, etc.) Now I'd like to define instances for all the SBV type classes:

    type SWord4 = SBV Word4
    instance SymWord Word4
    instance PrettyNum Word4
    instance SatModel Word4
    instance SDivisible Word4 where
    instance SDivisible SWord4 where
    instance SIntegral Word4
    instance FromBits SWord4 where
    instance Splittable Word8 Word4
    instance Splittable SWord8 SWord4
    instance Polynomial Word4
    instance Polynomial SWord4

However, I can't define these instances in the same way that SBV does for e.g. `Word8` and `Word16`, because SBV doesn't export many of the functions used: `genMkSymVar`, `genLiteral`, `genFromCW`, `liftQRem`, `liftDMod`, `checkAndConvert`, `genSplit`, `genJoin`, and others. Some of these functions are also useful for variable-width bitvectors; Cryptol relies on `liftQRem` and `liftDMod` in particular (they are exported by Cryptol's SBV fork). It might make sense to export some of these via `Data.SBV.Internals`.

It would also be good to add a module under `Data/SBV/Examples` showing how to instantiate the classes for a new word type like `Word4`.

**Comment by LeventErkok** [comment]
Indeed Data.SBV.Internals is the right place to export these.. Or perhaps, we should work on just getting SBV to support arbitrary sizes. I was planning to wait till Iavor's "type level integers" make it into GHC proper; but perhaps we can go ahead and implement the functionality needed right away.

**Comment by LeventErkok** [comment]
This shouldn't be too hard to do once all the other pieces are in place..

**Comment by LeventErkok** [comment]
@brianhuffman Is this the last thing that needs to be done to get full support for Cryptol? If so; let's get WordN in as well with instances.. I'm assuming you've the autogenerator for Word1-Word256 etc.?

**Comment by brianhuffman** [comment]
No, I don't have an autogenerator for these. I'm not sure how I feel about generating 250-some separate modules; might it be better to wait and use GHC type naturals for this?

**Comment by LeventErkok** [comment]
Agreed; that's too much junk.

**Comment by LeventErkok** [comment]
I'm closing this; a new ticket to follow.
