### ISSUE TITLE
Export `Quantifier` datatype

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#105]
Class `SymWord` (exported by `Data.SBV`) includes an operation

  mkSymWord :: Maybe Quantifier -> Maybe String -> Symbolic (SBV a)

but type `Quantifier` (which appears in its type signature) is not exported at all: neither its data constructors or even the type name itself.

This makes it difficult to write new instances of class `SymWord` that do not use the default definition of `mkSymWord`.

**Comment by LeventErkok** [comment]
Yes; we should export his from Data.SBV.Internals (along with a ton of other stuff, perhaps.)
