### ISSUE TITLE
Support for dynamically sized word types

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#106]
The lack of this feature is the main reason why Cryptol uses its own separate fork of SBV.

Certain operations don't make sense for variable-width word types, in particular `fromInteger`, `bit`, and `mkSymWord` and related functions; Cryptol's SBV fork is careful to avoid using any of these in the definitions of functions that *do* make sense for variable-width words.

Cryptol's SBV also provides variations of all these functions with a user-provided word-size argument.

We could simply merge the changes from Cryptol's SBV fork back in. Alternatively it might make sense to refine SBV's class hierarchy, splitting `SymWord` into separate classes for fixed- and variable-width word types.

Let me know what you think!

**Comment by LeventErkok** [comment]
I'm not sure what you mean by "variable size."

Do you mean a bit-vector that has a "polymorphic" size? Or, do you mean a size other than 8/16/32/64, i.e., one that's not natively understood by SBV?

If latter; by all means; let's pull the changes in from your fork and we'll have the necessary support. If you mean some other notion of variable-sizes, I need to think about that as there's so much code that depends on concrete size info and I'm not sure how we'd go about that. Also; I'm not exactly sure what it would mean to have a polymorphic-sized bit-vector in SBV..

**Comment by brianhuffman** [comment]
What I need is a symbolic version of a `WordN` type like this one:

    data WordN = WordN { width :: Int, value :: Integer }
      -- invariant: 0 <= width x && 0 <= value x && value x < 2 ^ width x

    type SWordN = SBV WordN

So the *type* `WordN` has "variable size", but any particular *value* of that type has a definite size. Essentially `WordN` is the union of types `Word0`, `Word1`, `Word2`, `Word3`...

The `SymWord` instance would produce symbolic words with different SBV kinds, depending on the `width` field:

    instance SymWord WordN where
      literal x = SBV k (Left (mkConstCW k (value x)))
          where k = KBounded False (width x)

Having types with a mixture of different SBV kinds then means we need to change the `HasKind (SBV a)` instance to depend on `kindOf`'s argument, instead of just its argument's type:

    instance HasKind (SBV a) where
      -- kindOf _ = kindOf (undefined :: a)
      kindOf (SBV k _) = k

**Comment by LeventErkok** [comment]
Great.. Let's make all the necessary changes so SBV can become a pure hackage dependency for Cryptol.. Happy to accept further patches.. (But we need to address #108 first!)

**Comment by LeventErkok** [comment]
Closing this; new release will wait till #104 is closed
