### ISSUE TITLE
sBranch is too strict

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#108]
After @brianhuffman 's generalizations to SBV, the basic SBranch test case started failing. To wit:

```
path :: SWord8 -> SWord8
path x = ite (x .> 5)
             10
             (sBranch (x .> 10)
                      (error "this case is not reachable!")  -- NB. x .> 5 fails, so can't be .> 10 here
                      20)

pathCheck :: IO ThmResult
pathCheck = prove $ \n -> let pn = path n in pn .== 10 ||| pn .== 20
```

The `pathCheck` theorem is no longer provable, because it terminates with the `error` call. This should not happen; i.e., `sBranch` should be smart enough not to touch any of the branches at all.

I suspect this has to do with the `kindOf` being more strict than before; i.e., it's actually looking inside an SBV value. This is rather unfortunate. I'm not sure how much it's pushing, but there are certain efficiency requirements and I'm worried the strictness can cause performance regressions, aside from the failed test case above.

Can we somehow address this? I don't want to release a new version without this problem being understood and somehow remedied.

**Comment by brianhuffman** [comment]
The `pathCheck` example from `SBranch.hs` works if we swap the branches of `sBranch (x .> 10) (error "...") 20` to make `sBranch (x .<= 10) 20 (error "...")`. It looks like `sBranch` always forces the first branch, but not the second. 

The reason has to do with the `Mergeable (SBV a)` instance declaration:

    instance SymWord a => Mergeable (SBV a) where
        symbolicMerge force t a b
          ...
          = SBV k $ Right $ cache c
          where k = kindOf a
          ...

Changing `kindOf a` to `kindOf b` makes `sBranch` strict in the `else` branch instead; now the original `pathCheck` works and the swapped version raises an error.

(I'm a bit surprised that we never noticed this problem in Cryptol; I guess all our examples that relied on `sBranch` for termination always had the recursion in the `else` branch, which wasn't forced.)

The `sBranch` function needs to be able to produce a symbolic value (with a kind) *without* forcing either of its two branch arguments. I think that this simply will not work for a type like `WordN` where values do not all have the same SBV kind. (In this respect, `sBranch` is a bit like `fromInteger`, `bit`, or `mkSymWord`, where for `WordN` we need to use variants that take an explicit kind/bitwidth argument.)

Here's what I think we should do:

1. Provide *two* variations of `kindOf :: SBV a -> Kind`, the original lazy `kindOf _ = kindOf (undefined :: a)` and the strict `kindOf (SBV k _) = k`. (One or both will need a new name.)

2. The `Num (SBV a)` and `Bits (SBV a)` instances should mostly use the strict variant of `kindOf`. (Those operations are strict anyway, and pulling the kinds from the arguments ensures that they will work for multi-kind types like `WordN`.) The only exceptions would be `fromInteger` and `bit`, which must rely on the lazy `kindOf (undefined :: a)` as neither takes an argument containing a kind.

3. The `symbolicMerge` function should use the lazy variant of `kindOf`. This makes `sBranch` sufficiently lazy; it also means that `ite` and `sBranch` will only work for single-kinded types (not `WordN`).

4. Introduce a new `symbolicMergeWithKind` function that is just like `symbolicMerge`, but takes the kind of the result as an explicit argument. We can then have a default definition `symbolicMerge = symbolicMergeWithKind (kindOf (undefined :: a))`. User applications (e.g. Cryptol) can use similar "WithKind" variants of `ite` and `sBranch` to implement conditional branches on `WordN` types.

**Comment by LeventErkok** [comment]
Sounds good.. Let's keep `kindOf` for the lazy version; and `kindOfStrict` for the new version; to make sure the uses are easily spottable. I trust a patch will be coming in soon? Thanks!

**Comment by LeventErkok** [comment]
Test suite passes..
