### ISSUE TITLE
ABC interface doesn't work with allSat

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#116]
[@acfoltzer  Capturing this as a separate issue to track properly]

For the following script:

```
; Automatically generated by SBV. Do not edit.
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s1 () (_ BitVec 8) #x02)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 8))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s2 (bvmul s0 s1)))
   (let ((s3 (bvshl s0 #x02)))
   (let ((s4 (= (bvcomp s2 s3) #b1)))
   s4))))
; --- refuted-models ---
(assert (not (= s0 #x00)))
(check-sat)
(get-value (s0))
```

ABC returns 0 as a value for `s0` which is not OK due to the second assert. Need to follow with Alan and co. @acfoltzer: I trust you'll do that?

**Comment by acfoltzer** [comment]
Done; will update here. Thanks!

**Comment by LeventErkok** [comment]
@acfoltzer Indeed the smt-lib backend doesn't seem to be quite ready yet for SBV/Cryptol usage. I played around a bit and it fails for some other inputs too. I filed this one: https://bitbucket.org/alanmi/abc/issue/30/

**Comment by acfoltzer** [comment]
@LeventErkok thanks! I sent some more examples to Alan yesterday, so hopefully it'll be ready for prime time soon.

**Comment by LeventErkok** [comment]
ABC version as of March 1st 2015 addresses the problems.
