### ISSUE TITLE
Build failures with GHC 7.10

### ISSUE THREAD

**Issue by yav** [LeventErkok/sbv#117]
Hi Levent,

the default instances for `NFData` have changed in GHC 7.10: the new defaults are in terms of `Generic` rather than just using `seq`.   So `sbv` fails to build.  The fix is simple:  

Replace:

    instance NFData SOMETHING where

with

    instance NFData SOMETHING where rnf a = seq a ()

**Comment by LeventErkok** [comment]
Hey Iavor.. I don't have 7.10 installed; I usually wait till there's an official release.. I'm assuming this is still compatible with 7.8? Or do we need some macro-magic to have it compile with both?

In any case, if you could send me a pull-request with a patch it would be really nice; that way you guys can build it with 7.10; and I'll make sure it works with 7.8 before I push it out.
