### ISSUE TITLE
Should &sweep be default for abc?

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#123]
@acfoltzer @weaversa @brianhuffman

I'm planning to do a SBV 4.2 release; nothing major in it except for a few documentation patches, and a few other tidy ups. But it'd allow Cryptol 2.2 (is that the next version) to be pushable to hackage with easy integration.

Should “%blast; &sweep; &put; dsat -s” be the default options I pass for ABC? (Note the extra sweep, compared to what we currently have.) I don't see why we wouldn't want the sweep; but perhaps Sean has some opinion on this matter. Please advise.

**Comment by weaversa** [comment]
Well, I've been playing around w/ it, and LOVE the SBV_ABC_OPTIONS flag.

My favorite command so far is:

%blast; &sweep -C 4000 -S 6000; &syn4; &splitprove -P 7 -s

The arguments to &sweep make it a bit stronger. I was able to solve more of the simon and speck proofs, but not all, with the stronger arguments. When &sweep fails to solve, &syn4 does a good job of optimizing the resulting circuit. Then, &splitprove is a parallel solving process, so much better than dsat. However, -P 7 will create 7 threads, and I don't know how hard it is to determine how much computational power the user is willing to release to abc.

Also, Alan made these commands play nice w/ Cryptol and SBV (they have silencing flags `-s`).

**Comment by LeventErkok** [comment]
@weaversa 

Ah I see. Not a clear-cut choice. So, what would you recommend the default arguments should be then? Something that should perform OK, though perhaps not too demanding on the machine?

Granted, you're the only real customer of this feature for the time being, so whatever works for you is the right choice I think. Would be great if you just give me a string!

**Comment by weaversa** [comment]
Then, I suggest
`%blast; &sweep -C 5000; &syn4; &cec -m -C 2000`

abc can solve all of the simon properties with this command (even 128_256, in 2 minutes!). However, Alan hasn't quieted &cec yet. I have asked him to, so hopefully this will work smoothly soon.

**Comment by LeventErkok** [comment]
Cool.. I'll make a release with that default as soon as I can get a a cec-queitized version of abc built on my machine.

@acfoltzer Holler if you'd like to sneak in anything else!

Incidentally, Sean: It'd be soo much easier if Alan moved abc to github; this bitbucket thing is a hassle to use. (Perhaps I'm just not used to it.) I find github to be so friendly and easy to use, anything else pales in comparison.

**Comment by weaversa** [comment]
%blast; &sweep -C 5000; &syn4; &cec -s -m -C 2000

That seems to be the magic command. Using that, `abc` can prove all properties in every spec. currently in the Cryptol examples directory, including contributions and maliciousSHA. The only exception is a bug in the `simon.cry : uniqueExpandSimon` proofs, which is not unexpected since this is new functionality for `abc`. I alerted Alan to the problem. Otherwise, pretty great, and I don't expected the commands to change. Please make this the new default. Thanks!

**Comment by acfoltzer** [comment]
Sounds good! I don't really have a dog in this fight except for wanting the default to be portable and well-supported. If all we have to say is "build abc from a checkout after this date" then that should be fine.

Thanks for doing the hill climb to find this config, @weaversa!

**Comment by LeventErkok** [comment]
@weaversa 

I just did a fresh build of ABC, and tried to use it with the options you suggested. If the problem is indeed unsat, then ABC does stay quiet. But if it is sat, it appears it still spits out some info that confuses SBV. This is what I saw:

```
***  The network is unchanged by fast extract.
***  Disproved at least one output of the miter (zero-based number 0).
***  Networks are NOT EQUIVALENT.  Time =     0.00 sec
```

The SMTLib file that causes the issue is:

```
; Automatically generated by SBV. Do not edit.
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s2 () (_ BitVec 8) #x02)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 8))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s1 (bvshl s0 #x02)))
   (let ((s3 (bvmul s0 s2)))
   (let ((s4 (= (bvcomp s1 s3) #b1)))
   (not s4)))))
(check-sat)
``` 

I think we're pretty close! I'll do a new release as soon as at least this example works.

**Comment by weaversa** [comment]
O.K. All fixed! `hg pull -u && OPTFLAGS="-O3" make`

**Comment by LeventErkok** [comment]
Sweet; I'll give this a try later tonight and will release if all goes well.

**Comment by LeventErkok** [comment]
Hmm, not quite.. This is the SMT-Lib input:

```
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s2 () (_ BitVec 8) #x02)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 8))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s1 (bvshl s0 #x02)))
   (let ((s3 (bvmul s0 s2)))
   (let ((s4 (= (bvcomp s1 s3) #b1)))
   (not s4)))))
(check-sat)
```

ABC responds `sat`, which is good; but then SBV issues: `(get-value (s0))` to which we get the response:

```ABC does not have a counter-example available to process a "get-value" request.```

Something must've gone wrong on the ABC side..

**Comment by LeventErkok** [comment]
Just noticed Alan pushed a fix.. All looks good. New release coming out shortly.

**Comment by weaversa** [comment]
@LeventErkok abc has some new capabilities and it may be worthwhile to update the default options - for example, I use `&fraig -y` over `&cec` anymore as it gives much better results (at least for me). However, I can't seem to get SBV to recognize `abc` if I modify the `SBV_ABC_OPTIONS` to anything other than the default.

**Comment by LeventErkok** [comment]
@weaversa 

Defining abc options is tricky since it has fancy quoting. Try like this (note the escapes):

```
Prelude Data.SBV> proveWith abc{verbose=True} $ \x  -> x + x .== (2*x::SWord8)
** Calling: abc -S "%blast; &sweep -C 5000; &syn4; &fraig -y"
[ISSUE] ; Automatically generated by SBV. Do not edit.
** Skipping heart-beat for the solver ABC
** Backend solver ABC does not support global decls.
** Some incremental calls, such as pop, will be limited.
[ISSUE] (set-option :diagnostic-output-channel "stdout")
[ISSUE] (set-option :produce-models true)
[ISSUE] (set-logic QF_BV)
[ISSUE] ; --- uninterpreted sorts ---
[ISSUE] ; --- tuples ---
[ISSUE] ; --- sums ---
[ISSUE] ; --- literal constants ---
[ISSUE] (define-fun s2 () (_ BitVec 8) #x02)
[ISSUE] ; --- skolem constants ---
[ISSUE] (declare-fun s0 () (_ BitVec 8))
[ISSUE] ; --- constant tables ---
[ISSUE] ; --- skolemized tables ---
[ISSUE] ; --- arrays ---
[ISSUE] ; --- uninterpreted constants ---
[ISSUE] ; --- user given axioms ---
[ISSUE] ; --- preQuantifier assignments ---
[ISSUE] (define-fun s1 () (_ BitVec 8) (bvadd s0 s0))
[ISSUE] (define-fun s3 () (_ BitVec 8) (bvmul s0 s2))
[ISSUE] (define-fun s4 () Bool (= s1 s3))
[ISSUE] ; --- arrayDelayeds ---
[ISSUE] ; --- arraySetups ---
[ISSUE] ; --- formula ---
[ISSUE] ; --- postQuantifier assignments ---
[ISSUE] ; --- delayedEqualities ---
[ISSUE] ; -- finalAssert ---
[ISSUE] (assert (not s4))
[SEND] (check-sat)
[RECV] undecided
[SYNC] Attempting to synchronize with tag: "terminating upon unexpected response (at: 2022-04-25 10:54:43.045292 PDT)"
[FIRE] (echo "terminating upon unexpected response (at: 2022-04-25 10:54:43.045292 PDT)")
[RECV] ABC is expecting "get-value" in a follow-up input of the satisfiable problem.
*** Exception:
*** Data.SBV: fd:18: hGetLine: end of file:
***
***
***    Executable: /usr/local/bin/abc
***    Options   : -S "%blast; &sweep -C 5000; &syn4; &fraig -y"
***
***    Hint      : Solver process prematurely ended communication.
***                It is likely it was terminated because of a seg-fault.
***                Run with 'transcript=Just "bad.smt2"' option, and feed
***                the generated "bad.smt2" file directly to the solver
***                outside of SBV for further information.
```

In this case `abc` responded `undecided` which caused SBV to give-up. Perhaps a different set of options is better to use?

I'm happy to change the default options to whatever you want, if you send me a proper string.
