### ISSUE TITLE
sbvTestBit performance issues

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#129]
@brianhuffman and co found that `sbvTestBit` is way too slow on concrete words when the bit-sizes get large. This does make sense since GHC itself (and gmp in turn) are not so fast when the bit-sizes go above 128 or so.

@brianhuffman is suggesting some fixes that require (re-)introduction of 1-bit-size vectors that can address the issue. This ticket will track that to make sure eventually the perf improvements make it to mainline SBV. See: https://github.com/GaloisInc/cryptol/issues/189

**Comment by LeventErkok** [comment]
@brianhuffman Can we close this, now that I've merged the Data.Dynamic? Or is more work required before this one is handled properly?

**Comment by brianhuffman** [comment]
Yes, it should be very easy to fix now. I'll submit a patch in the morning.

**Comment by LeventErkok** [comment]
Do a pull first! I committed a whole bunch of stuff. (All around floating-point stuff, but I had to move some code around. There shouldn't be any conflicts.)
