### ISSUE TITLE
Reenable negative-zero tests when GHC bug is addressed

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#138]
The addition of new fp-classifier predicates unearthed a number issues on the z3 side, but also potentially in SBV.. Need to get a clean-test suite before next release.

**Comment by LeventErkok** [comment]
Reduced to only two failures currently, and I suspect perhaps a GHC bug is in play here. Need to dig this down further.

**Comment by LeventErkok** [comment]
OK, this is caused by the following GHC bug: https://ghc.haskell.org/trac/ghc/ticket/10215#ticket

Need to figure out if we should "skip" this test for the time being, or perhaps there's a workaround; based on the response to the ticket.

**Comment by LeventErkok** [comment]
Currently skipping this test; when GHC gets the fix, remove the corresponding line in SBVUnitTest/TestSuite/Basics/ArithSolver.hs, Look for the comment that mentions issue #138.

**Comment by LeventErkok** [comment]
GHC folks are tracking this here: https://ghc.haskell.org/trac/ghc/ticket/9238

Might make it to 7.10.2, possibly..

**Comment by LeventErkok** [comment]
Note: This fix didn't make it to 7.10.2; and GHC folks are now tracking it for 8.0.1

**Comment by ygale** [comment]
As per [Austin's request on ghc-dev](https://mail.haskell.org/pipermail/ghc-devs/2015-September/009953.html), I recommended that 9238 be included in GHC 7.10.3, if it will ever exist, by changing the target version of 9238 to 7.10.3.

**Comment by LeventErkok** [comment]
Thanks @ygale 
I just noticed that this is now fixed in the GHC HEAD.

Re-enable these tests when GHC 8.0 (?) is released.
