### ISSUE TITLE
Upgrade to GHC 7.10

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#140]
7.10 is out; upgrade and make sure all works well. (No Mac-release yet, waiting for that.)

Link: https://www.haskell.org/ghc/download_ghc_7_10_1#binaries

**Comment by LeventErkok** [comment]
Warnings I get with 7.10: (Need to figure out how to fix these and whether travis/hackage will work; I'm not sure if those guys have 7.10 installed.)

```
Data/SBV.hs:109:14: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

Data/SBV/Provers/Prover.hs:14:14: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

Data/SBV/BitVectors/Symbolic.hs:58:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’

Data/SBV/Compilers/CodeGen.hs:19:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
```

**Comment by TomMD** [comment]
For redundant messages, such as your `'Control.Applicative'`, if the redundancy is due to the symbol also coming from `Prelude` then a hack-fix is to explicitly import `Prelude`.  This would remain till support for 7.8 is dropped, then both imports should be dropped.

**Comment by LeventErkok** [comment]
Thanks @TomMD 

Any advice for the OverlappingInstances issue?

**Comment by LeventErkok** [comment]
Partially addressed in https://github.com/LeventErkok/sbv/commit/7785323a7935224232ceedf2f722dbcf496f619e

The Control.Applicative import is only done if GHC is < 710.

Still need a solution for the Overlapping stuff when GHC is < 710.

**Comment by LeventErkok** [comment]
Fixed as of https://github.com/LeventErkok/sbv/commit/cf23a43e93db6a99a2d9e04f8dc65316f8357602

Essentially, simplified code by getting rid of Overlapping-instance causing instances. Provable sarray instance was the main culprit, along with the Equality class; neither of which was really essential. Led to a bunch of code clean-up too..
