### ISSUE TITLE
test-bit on signed types is broken

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#144]
@brianhuffman 

```
Prelude Data.SBV> sbvTestBit (1::SWord8) 0
True
Prelude Data.SBV> sbvTestBit (1::SInt8) 0
False
```

Something gone wrong with the Dynamic conversion here..

**Comment by LeventErkok** [comment]
@brianhuffman 

I see the problem.. When you do an extract, you're keeping the kind the same as the original. So, a signed value remains a signed value; an unsigned value remains an unsigned value.

This is fine for extract, as types sort of require that. But when you extract precisely one bit as in testBit, you always want to get a KBool. That's not happening currently.

So, there's a problem here. Differentiating between "extract i i" for the purposes of extracting a subsequence; vs. "extract i i" for the purposes of testing a bit. Those two are two different operations from a type perspective.

**Comment by LeventErkok** [comment]
Hmm; looks like you just committed as I was commenting..

Clearly that's the problem, but I'm not 100% sure if extract should always return unsigned. we need to look at exactly how SBV uses extract and make sure that's OK. Have you done that?

**Comment by brianhuffman** [comment]
Hmm, I thought I had... I was under the impression that only unsigned types were instances of the `Splittable` class, but it looks like the signed word types are there too. Hold off on accepting the pull request while I fix the bug in another way.

**Comment by LeventErkok** [comment]
cool.

**Comment by LeventErkok** [comment]
hmm; I don't actually see the signed ones in the Splittable class; only unsigned.. Where did you see them?

I'm still wary of blanket returning unsigned.

**Comment by brianhuffman** [comment]
Oh, I guess I saw `SWord64` and thought it meant *signed* `Word64`. Anyway, I'm going to make `svExtract` preserve the signedness, and just make the size-1 bitvector comparison work for either signed or unsigned.

**Comment by LeventErkok** [comment]
yeah; that sounds safe.

I suspect the test-suite is still going to fail due to SMTLib-generation failures; but I can take care of that. (Just make sure arithCF passes..)

**Comment by brianhuffman** [comment]
We should be good to go:

    All 291379 test cases in category "arithCF" successfully passed.
