### ISSUE TITLE
ABC Error when attempting to arove aes128isCorrect

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#154]
I thought that I'd try ABC on the aes128IsCorrect proof. Of course, I wasn't expecting a successful proof, but rather than simply sitting and spinning, it quickly returns the following error:

```
*Data.SBV.Examples.Crypto.AES> Data.SBV.Bridge.ABC.prove aes128IsCorrect 
*** An error occurred.
***  Failed to complete the call to ABC
***  Executable   : "/home/jpziegl/local/bin/abc"
***  Options      : -S "%blast; &sweep -C 5000; &syn4; &cec -s -m -C 2000"
***  Exit code    : -6
***  Solver output: 
***  ==============================================================================
***  abc: src/base/wlc/wlcReadSmt.c:221: Smt_StrToType: Assertion `0' failed.
***  ==============================================================================
***  Giving up..
```

Interestingly, when I dump the SMT file and run it directly in ABC with the (above-reported) command-line options, I don't see an error and it sits and spins as expected.

**Comment by TomMD** [comment]
I can reproduce the failure using Linux, ghc-7.8.4 x86-64, ABC 1.01 (pullled and re-built today), and SBV 4.4.

I have not tried to produce SMT and verified the alternate behavior.

**Comment by LeventErkok** [comment]
@TomMD Thanks!

@jpziegler Interesting; I didn't get a chance to reproduce this yet; but there's one difference between when SBV calls abc, and when you do it from the command line. When SBV calls it, the input comes from a pipe; something like this: `cat file.smt2 | abc options` or `abc options < file.smt2`

Can you try that variant and see how abc behaves?

**Comment by LeventErkok** [comment]
@jpziegler Indeed ABC dies when used from SBV for this problem.

But if I generate the SMTLib file and I give it to ABC on the command-line, it fails as well, with the following message:

```
$ abc
UC Berkeley, ABC 1.01 (compiled Mar 15 2015 21:17:20)
abc 01> %read aes.smt2
The following operations is currently not supported (table2)
Assertion failed: (0), function Smt_StrToType, file src/base/wlc/wlcReadSmt.c, line 221.
[1]    12324 abort      abc
```
I don't think ABC supports array-declarations quite yet; so you might want to report this to Alan as needed.

@acfoltzer @brianhuffman fyi
@jpziegler I'm curious how you got the ABC to actually not crash from the command line; can you double check that is indeed the case?

**Comment by jpziegler** [comment]
It was my mistake. I forgot that abc takes its input from stdin. It didn't
complain when I passed the smt file as a parameter, so I assumed it was
chugging away when in fact it was just waiting for input. I do get the
error when I execute it properly.

**Comment by jpziegler** [comment]
@LeventErkok: I added a comment and the SMT file to the ABC issue you
created on BitBucket:

https://bitbucket.org/alanmi/abc/issue/30/smt-lib-reader-issues#comment-17625693

**Comment by LeventErkok** [comment]
Ah, so this is indeed something ABC doesn't quite yet support. Alan might appreciate a simpler example than the AES blob; so you might want to send him the output from something like:

```
prove $ \x -> readArray (writeArray (x::SArray Word8 Word8) 0 0) 0 .== 0
```

I'm closing this ticket on the SBV side..
