### ISSUE TITLE
ABC incorrectly rejects theorem

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#158]
I've been writing an application using Data.SBV.Dynamic. It works well. However, a proof I generated seems to be giving ABC some trouble. It returns as Q.E.D. for cvc4, z3, yices, boolector, and mathSAT, but ABC returns the following:
```
Falsifiable. Counter-example:
  s0 = 0 :: Word1
  s1 = 1 :: Word1
```
The example relies on some specialized libraries, but here is the SMT output. This is a proof that a particular 1-bit adder is correct.
```
; Automatically generated by SBV. Do not edit.
(set-option :produce-models true)
(set-logic QF_BV)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s3 () (_ BitVec 1) #b0)
(define-fun s5 () (_ BitVec 1) #b1)
; --- skolem constants ---
(declare-fun s0 () (_ BitVec 1))
(declare-fun s1 () (_ BitVec 1))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s2 ((_ extract 0 0) s0)))
   (let ((s4 (not (= (bvcomp s2 s3) #b1))))
   (let ((s6 (ite s4 s5 s3)))
   (let ((s7 ((_ extract 0 0) s1)))
   (let ((s8 (not (= (bvcomp s3 s7) #b1))))
   (let ((s9 (ite s8 s5 s3)))
   (let ((s10 (= s_1 s8)))
   (let ((s11 (= s_1 s4)))
   (let ((s12 (not s11)))
   (let ((s13 (ite s10 s12 s11)))
   (let ((s14 (= s_1 s13)))
   (let ((s15 (ite s14 s5 s3)))
   (let ((s16 (concat s9 s15)))
   (let ((s17 (concat s6 s16)))
   (let ((s18 (bvadd s0 s1)))
   (let ((s19 (concat s1 s18)))
   (let ((s20 (concat s0 s19)))
   (let ((s21 (= (bvcomp s17 s20) #b1)))
   (not s21))))))))))))))))))))
```

**Comment by LeventErkok** [comment]
Well; if cvc4, z3, yices, boolector, and mathSAT are all agreeing and ABC isn't, then this would be something Alan would be very much interested in seeing! Can you file it at Bicbucket ABC site?

**Comment by jpziegler** [comment]
Will do. Thought I'd post here first.

**Comment by jpziegler** [comment]
Link to the Bitbucket issue, for reference:
https://bitbucket.org/alanmi/abc/issue/33

**Comment by brianhuffman** [comment]
It seems that lines like `(let ((s10 (= s_1 s8)))` are redundant and that we could optimize them away, i.e. replace `true = x` with just `x`. Interestingly, I found that if I inline all three such declarations in the example above (`s10`, `s11`, and `s14`) then abc once again returns unsat.

**Comment by LeventErkok** [comment]
@brianhuffman yeah; x = True should disappear. I'm surprised I don't already have that optimization in there.. Is it coming from the bit-wise extraction instead of masking to test-bits?

**Comment by brianhuffman** [comment]
I don't know where the `(= s_1 s8)` comes from. As I understand it, `svTestBit` produces exactly this:

    (let ((s2 ((_ extract 0 0) s0)))
    (let ((s4 (not (= (bvcomp s2 s3) #b1))))

**Comment by LeventErkok** [comment]
I'll add the optimization later today.. In any case, this is an ABC bug just by @brianhuffman 's observation that inlining those definitions change ABC's response. @jpziegler Feel free to mention that to Alan, he might find it useful.

**Comment by LeventErkok** [comment]
Added the optimizations in https://github.com/LeventErkok/sbv/commit/02b40b09e1fba97c09b2421afb0acdc059419854

Also, looks like Alan fixed the actual issue on the ABC side; so closing this ticket. @jpziegler Please feel free to re-open (and continue to submit tickets!) as you find issues!
