### ISSUE TITLE
SBV.Dynamic API requests

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#159]
Functions similar to the following would be useful in the SBV.Dynamic API:
```haskell
svFromWord :: SVal -> [SVal]
--Converts a bitvector to a list of SVals of kind Bool

svToWord :: [SVal] -> SVal
--Converts a list of SVals of kind Bool to a bitvector

svIncrement :: SVal -> SVal
--Adds one to an SVal (Except for kind KBool, presumably)

svAddConstant :: SVal -> Num -> SVal
--Adds a constant amount to the SVal (Except for kind KBool, presumably)
```

**Comment by LeventErkok** [comment]
Note that `svIncrement`/`svAddConstant` will need to know whether they treat their argument signed and/or unsigned. The SBV api handles this automatically via types, but with SBV.Dynamic, each operation will need to be careful about whether the arguments should be treated signed or otherwise.

**Comment by LeventErkok** [comment]
@jpziegler Not quite sure if you still need these, but I just added the following 8-functions to the Dynamic API; which should cover everything you listed. Let me know if there's more..

```
       * svSetBit                  : set a given bit
       * svBlastLE, svBlastBE      : Bit-blast to big/little endian
       * svWordFromLE, svWordFromBE: Unblast from big/little endian
       * svAddConstant		       : Add a constant to an SVal
       * svIncrement, svDecrement  : Add/subtract 1 from an SVal
```
