### ISSUE TITLE
SBV.Dynamic: Define a unique type for SVal of kind KBool

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#160]
It would be useful for SVal of kind KBool to have its own type, since it's kind of special. (For example, proveWith can only take an SVal of kind KBool.) That way, code would would be more readable (you could tell an SBool just by looking at the type) and the type-checker would be more of a help when coding.

**Comment by LeventErkok** [comment]
@brianhuffman I added you as a collaborator, so I think you should be able to "push" stuff directly to the repo, manipulate sources etc. if internet is to be believed. Hack away.

**Comment by LeventErkok** [comment]
I think the train has left on this one. Doesn't seem to be worth complicating that interface at this point. Please re-open if this is still an issue.
