### ISSUE TITLE
SBV.Dynamic: Add sAssert-like functionality

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#171]
Please add a function to SBV.Dynamic similar to [sAssert](https://hackage.haskell.org/package/sbv-4.4/docs/Data-SBV.html#v:sAssert) that allows checking for conditions that should not be possible or allowable.

**Comment by jpziegler** [comment]
Can this currently be done using [`svReduceInPathCondition`](https://hackage.haskell.org/package/sbv-4.4/docs/Data-SBV-Dynamic.html#g:17)?
```

**Comment by LeventErkok** [comment]
I think the proper place for this is in the SBV code, as opposed to the user-land; even if it might be possible to do so. I'm sure Brian can convert the current implementation to work on dynamic when he gets a chance. (I'll defer to him unless he declares otherwise!)

**Comment by jpziegler** [comment]
@LeventErkok Definitely agree. Was hoping to get something working in the mean time.

**Comment by LeventErkok** [comment]
@jpziegler 

I removed support for `sBranch/sAssert` due to a (recently realized) soundness issue in their implementation, see #180.

There's a new function, called `isSatisfiableInCurrentPath`. It has a different type: The computation has to be done at the `Symbolic` monad level. (There's an dynamic variant as well.) Please give that a try and see if that works for you.

Note that since the 'Symbolic' monad is now exposed, your program will have to take quite a different shape; the types will guide you, nonetheless.

**Comment by jpziegler** [comment]
Was hoping to try this, so I upgraded to GHC 7.10.1 to support the latest SBV. Unfortunately, that broke another library I use that has the requirement "`base (>=4.6 && <4.8)`". As I understand it, with GHC 7.10 you're stuck with `base-4.8.0.0`. So I don't see an easy way to test this with my application.

Any suggestions? Something I'm missing?

**Comment by LeventErkok** [comment]
@jpziegler You'll have to get that library ported to work with GHC 7.10.1.. So far as I know, there can only be one "base."

**Comment by jpziegler** [comment]
Understood, and as I suspected.

In any case, since there is no `sAssert` now and the replacement, `isSatisfiableInCurrentPath`, is reflected in `Data.SBV.Dynamic` as `svIsSatisfiableInCurrentPath`, I'll go ahead and close this ticket.

**Comment by LeventErkok** [comment]
@jpziegler Cabal allows "relaxing the constraints" during installations, see `--allowNever` here: https://www.haskell.org/cabal/users-guide/installing-packages.html

If the other package happens to compile with the newer base, but just happens to have a more-than-necessary constraint, then you might be able to install it using `--allowNever`.

If that package really doesn't work with the new version of the `base`, then you'll have to get its author to upgrade!
