### ISSUE TITLE
SBV.Dynamic: Add QuickCheck support for predicates

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#172]
It would be useful to be able to be able to automatically `quickCheck` theorems/predicates (Functions returning `Symbolic SVal` of kind `KBool`) built with SBV.Dynamic.

**Comment by jpziegler** [comment]
I see that there are mentions of QuickCheck on the [SBV.Dynamic page](https://hackage.haskell.org/package/sbv-4.4/docs/Data-SBV-Dynamic.html). What's the best way to go about this right now? Are there any examples available?

**Comment by LeventErkok** [comment]
It might help if you post a small code segment you tried with regular-SBV and a dynamic variant where the former works but the latter does not. That'd help Brian see what functionality is missing.

**Comment by jpziegler** [comment]
Here's an example:
```haskell
import Data.SBV
import Data.SBV.Dynamic
import Test.QuickCheck

predicate :: SWord8 -> SBool
predicate x = x `shiftL` 2 .== 4 * x

dynamic_predicate :: Int -> Symbolic SVal
dynamic_predicate n = do
  x <- svMkSymVar Nothing (KBounded False n) Nothing
  let four = svInteger (svKind x) 4
  return $ (x `svShl` 2) `svEqual` (four `svTimes` x)
```
Now interactively:
```
> Data.SBV.proveWith z3 predicate
Q.E.D
> quickCheck predicate
+++ OK, passed 100 tests.
> Data.SBV.Dynamic.ProveWith z3 $ dynamic_predicate 8
Q.E.D.
> quickCheck $ dynamic_predicate 8

<interactive>:30:1:
    No instance for (Testable (Symbolic SVal))
      arising from a use of `quickCheck'
...
```
This is tricky because the inputs to the predicate are declared dynamically and are not visible in the type of the function.

**Comment by jpziegler** [comment]
One workaround is to wrap things up in something that quickCheck knows about:
```haskell
import Data.SBV.Dynamic
import Test.QuickCheck

dynamic_predicate_tester :: Int -> Integer -> Bool
dynamic_predicate_tester n xint =
  let x = svInteger (KBounded False n) xint in
  let four = svInteger (svKind x) 4 in
  case svAsBool $ (x `svShl` 2) `svEqual` (four `svTimes` x) of
    Just b -> b
    Nothing -> False
```
```
> quickCheck $ dynamic_predicate_tester 8
+++ OK, passed 100 tests.
```
But it's so nice in Data.SBV to be able to use the same functions for `prove` as for `quickCheck`. Not sure if it's feasible for SBV.Dynamic, but thought I'd ask!

**Comment by LeventErkok** [comment]
I think there's enough "info" in the SBV.Dynamic stuff to be able to do this automatically; but @brianhuffman will have to comment on that.

**Comment by brianhuffman** [comment]
It's possible to quickcheck values of type `Symbolic SVal` by converting from `SVal` to `SBool`. (Note that currently you need to import `Data.SBV.Internals` to define `toSBool`.)

    toSBool :: SVal -> SBool
    toSBool = Data.SBV.Internals.SBV

    checkSVal :: Symbolic SVal -> IO ()
    checkSVal s = quickCheck (fmap toSBool s)

Now you can do:

    *Main> checkSVal (dynamic_predicate 8)
    +++ OK, passed 100 tests.

It should be easy to add an instance of `Testable (Symbolic SVal)` to the library so that you will be able to use `quickCheck` instead of `checkSVal` here.

What *won't* work is an instance of `Arbitrary SVal`, because there's no way to know what kind/bitsize of value to generate. This means that you can't quickcheck a function of type `SVal -> SVal -> SVal` like you can check a function of type `Word8 -> Word8 -> Word8`.

**Comment by jpziegler** [comment]
Nice! Working from this, I found that "native" QuickCheck functionality can be gained by adding the following lines to `Data.SBV.BitVectors.Model`:
```haskell
instance Testable (Symbolic SVal) where
  property m = property $ fmap (SBV::SVal -> SBool) m
```
Seems like more checks should be put in to ensure that all the types are what they need to be within the `SVal`, but this works.

**Comment by brianhuffman** [comment]
@jpziegler Looks good. I'll go ahead and add that instance.

**Comment by brianhuffman** [comment]
@jpziegler See commit 2a2389b7. I added the `Testable` instance with a run-time check to ensure kind KBool. If this works for you, then we can close the ticket.

**Comment by jpziegler** [comment]
Looks good! Closing.
