### ISSUE TITLE
SBV produces output unparsable by ABC

### ISSUE THREAD

**Issue by TomMD** [LeventErkok/sbv#173]
It seems SBV is producing something ABC can not parse.  I know this has been encountered before but don't currently see an issue filed.

Consider Salsa20 theorem 1:

```
quarterround : [4][32] -> [4][32]
quarterround [y0, y1, y2, y3] = [z0, z1, z2, z3]
  where
    z1 = y1 ^ ((y0 + y3) <<< 0x7)
    z2 = y2 ^ ((z1 + y0) <<< 0x9)
    z3 = y3 ^ ((z2 + z1) <<< 0xd)
    z0 = y0 ^ ((z3 + z2) <<< 0x12)

property theorem1 a = quarterround [a, -a, a, -a] == [a,-a,a,-a]
```

```
Main> :set prover=abc
Main> :prove theorem1 
*** An error occurred.
***  Failed to start the external solver: fd:10: hGetLine: end of file
***  Make sure you can start "/home/tommd/.cabal/bin/abc"
***  from the command line without issues.
Main> 
[tommd@vodka]~/tmp% abc
UC Berkeley, ABC 1.01 (compiled May 26 2015 16:16:08)
abc 01> ***EOF***
```

We can get more information from a direct invocation:

```
Main> :set prover=offline
Main> :set smtfile=/tmp/foo.smt2
Main> :prove theorem1
Main> ^C
% abc -S '%blast &sweep -C 5000; &syn4 ; &cec -s -m -C 2000' < /tmp/foo.smt2
abc: src/base/wlc/wlcReadSmt.c:303: Smt_PrsBuildConstant: Assertion `fFound' failed.
zsh: abort (core dumped)  abc -S '%blast &sweep -C 5000; &syn4 ; &cec -s -m -C 2000' < /tmp/foo.smt2
```

vs

```
Main> :set prover=z3
Main> :prove theorem1 
Q.E.D.
```

**Comment by LeventErkok** [comment]
@TomMD 

I just tried on my box, and actually ABC proved it just fine.

One difference though, I have:

```
% abc
UC Berkeley, ABC 1.01 (compiled Mar 15 2015 21:17:20)
```

So perhaps something went bad recently on the ABC land.

There was a similar issue filed for ABC here: https://bitbucket.org/alanmi/abc/issue/30/smt-lib-reader-issues#comment-17625693

Can you file it there together with the .smt file generated to see what Alan has to say?

**Comment by LeventErkok** [comment]
@TomMD 

Indeed, I just upgraded my ABC:

```
$ abc
UC Berkeley, ABC 1.01 (compiled May 27 2015 19:53:10)
```

and it does indeed fail as Tom described. So, looks like ABC suffered a bug sometime between March 15th and May 27th in processing SMT-Lib files. Please provide that data to Alan.

I'm closing this ticket as this is not an SBV issue. Re-open if it proves otherwise!

**Comment by TomMD** [comment]
Thank you Levent.

The new issue for interested parties: https://bitbucket.org/alanmi/abc/issue/35/smt-lib-reader-regression
