### ISSUE TITLE
SBV->C: Unexpected: mkConst: False

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#174]
C code generation fails for functions that use symbolic values of type `SBool`. For example:

    compileToC Nothing "foo" $ do { b <- cgInput "b"; cgOutput "x" (ite b 0 1 :: SWord8) }

    *** Exception: SBV->C: Unexpected: mkConst: False

It seems that function `mkConst` in `Data.SBV.Compilers.C` is to blame; I suspect that the comment, "Note that this automatically takes care of the boolean (1-bit) value problem..." is no longer valid.

**Comment by LeventErkok** [comment]
Indeed, the code predated the KBool.. Fixed now.
