### ISSUE TITLE
LOr, LAnd

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#177]
As evoked in a former ticket ( https://github.com/LeventErkok/sbv/issues/175#issuecomment-114613678 ) 
Now, SBV does not handle logical operators (&& ||). It converts them automatically in bitwise version before doing anything about it.

The fact is that the typing makes impossible to write something like 1 || 98, we can only have logical operation on booleans. This means that proving a theorem on a bitwise logical expression on booleans implies the same result when replacing all operators with their lazy logical variants (which is not the case if we allow logical for non boolean, 2 & 1 = 0 --> false whereas 2 && 1 != 0 --> true) (the proof can be obtained by structural induction on the expression using the extended boolean tables of the operator regarding the galois lattice of values, cf at the end*). The idea would be to reconvert back logical operators that have been converted in bitwise for analysis purpose into logical for the compilation, which will not affect its soundness, but only its completeness (raise false alarms only, cf at the end). Of course, this is only valid if there is a strong type system, preventing the use of logical operators on non boolean types. This will allow to have a more precise behviour of the program, having compiled && into && and || into || (not & and |). This makes the program more logical.

*An other note : this depends on the galois lattice used for the abstraction of the boolean values. 
If we work on a lattice (B, F, V, T) in French (Bottom, Faux, Vrai, Top), this gives the following table for & and &&. (It has to be checked wheter the galois lattice used is intuitive and can correspond to a similar pattern).
c = a & b, d = a && b
abcd
BBBB
BFBB
BVBB
BTBB

FBBF    --> Different : False alarm raised
FFFF
FVFF
FTFF

VBBB
VFFF
VVVV
VTTT

TBBB
TFFF
TVTT
TTTT

For
c = a | b, d = a || b
BBBB
BFBB
BVBB
BTBB

FBBB
FFFF
FVVV
FTTT

VBBV --> Different : false Alarm raised in this case
VFVV
VVVV
VTVV

TBBB
TFTT
TVVV
TTTT

**Comment by LeventErkok** [comment]
I made some changes to the C-translator so boolean operators are translated using `&&` and `||`. Example:

```haskell
 compileToC Nothing "foo" $ do  x <- cgInput "x"
y <- cgInput "y"; cgReturn (bnot (x ||| y) .== bnot x &&& bnot y)
```

**Comment by Varmin** [comment]
That was exactly what I was looking for. Logical Or/Ands on non boolean variables can produce some terrible bugs/gotchas. It's better not to allow them.

Thanks.
