### ISSUE TITLE
Double includes

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#179]
Hi,

Is it possible to delete the double includes in the .c files ? I made a first try [there](https://github.com/Copilot-Language/sbv-for-copilot/commit/5164099f2ea60febdf580dcaafed69ff5b2e42d3), and it seems to work (since the header files are already included in the internal.h file).

Thanks.

**Comment by LeventErkok** [comment]
@Varmin 

Commit https://github.com/LeventErkok/sbv/commit/3f87db138d91c341c45aea0e65de49d0e0398f09 should take care of multiple-includes.. Can you give it a test and close this ticket if it all works fine?

**Comment by Varmin** [comment]
It seems ok. Thanks.
