### ISSUE TITLE
Floating point operations

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#182]
As evoked there : https://github.com/LeventErkok/sbv/issues/175

It seems that there are no floating point operation on non constant values. 

Indeed : Sval is defined as 

-- | The "Symbolic" value. Either a constant (@Left@) or a symbolic
-- value (@Right Cached@). 
data SVal = SVal !Kind !(Either CW (Cached SW))

And in model.hs :

-- | Lift a float/double unary function, only over constants
lift1FNS :: (SymWord a, Floating a) => String -> (a -> a) -> SBV a -> SBV a
lift1FNS nm f sv
  | Just v <- unliteral sv = literal $ f v
  | True                   = error $ "SBV." ++ nm ++ ": not supported for symbolic values of type " ++ show (kindOf sv)

I just managed to force that in Copilot by calling each floating function as an external function (but it is as bad as saying that sin is a random function, maybe we could make it more precise by saying that it is a random function that has its values in [-1;1] in the model checker, and then compile it anyways). The biggest problem is that sin/cos/... in C are machine dependant (each architecture has its own implementation, either directly on the hardware or by software tricks and those do not always have the behavior expected : https://randomascii.wordpress.com/2014/10/09/intel-underestimates-error-bounds-by-1-3-quintillion/ ).

Thanks.

**Comment by LeventErkok** [comment]
Hmm; any reason why you're not using 'SFloat' and 'SDouble'? Going through SV's is really only intended for bit-vectors that are not natively supported by SBV, i.e., when you need `SWord11` for instance. When SBV supports a type directly, as in `SFloat`/`SDouble` those should always be preferred.

Let me know if that doesn't work for you for some reason.

@brianhuffman I'm not convinced the dynamic-interface needs to support types that SBV already supports fully; but maybe there's good reason to complete the missing bits?

**Comment by LeventErkok** [comment]
@Varmin Is this still an issue? Are the floating-point operations working OK for you?

**Comment by Varmin** [comment]
I managed to bypass it (actually I asked the user to provide an implementation of each function, and by default it uses the standard implementation of the libc). I'll do some more investigation on it, but I think that it can be considered as closed.

**Comment by LeventErkok** [comment]
OK closing this ticket now. Please re-open if further issues arise.
