### ISSUE TITLE
Adding labelling in the expression

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#185]
As evoked there https://github.com/LeventErkok/sbv/issues/175#issuecomment-116636944
It would be fun (and useful for traceability) if it is possible to add an operator (or even a new construct in the language) that has the type String -> SBV a -> SBV a that does nothing except printing a comment in the code where is comes to be evaluated (something like a trace function, but instead of printing of stdout, it prints in the form of a comment inside the code produced).

This would be useful for checking the traceability of an expression, and studying how the constructs we give to SBV are managed and then reorganized in the final C code.

I added a labelling for Copilot ( https://github.com/Copilot-Language/copilot-language/commit/bff96ff813c05c94a158e91841f39ae193beb55a ) on the file level (using addDeclaration), but it cannot label anything inside a function, so the traceability is at the level function. It would be nice if we can go deeper in the labelling of the function.

Thanks.

**Comment by LeventErkok** [comment]
@Varmin Example:

```haskell
compileToC Nothing "foo" $ do x <- cgInput "x"; 
                                                  cgOutput "z" (label "this is two plus x" (x+2::SFloat))
```

generates:

```C
void foo(const SFloat x, SFloat *z)
{
  const SFloat s0 = x;
  const SFloat s2 = s0 + 2.0F;
  const SFloat s3 = s2 /* this is two plus x */;

  *z = s3;
}
```

Let me know if this is sufficient for your purposes.

**Comment by Varmin** [comment]
I tested it, and it seems to work well. 

Thanks.
