### ISSUE TITLE
Common subexpression elimination ?

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#186]
Hi,

It seems that there is a common subexpression optimization in the code produced (I suppose that it is in SBV, given the Copilot does not implement common-subexpression elimination), which make the ACSL contract false : 
We have the following declaration : 

      const SDouble s8 = s7 / s5;

instead of the following (probably he guessed that ext_sqrt_0 == ext_sqrt_1) :

       const SDouble s8 = s0 / s5;

Is there a way to deactivate it, even if the code produced is slower ?

Thanks.

Here is the source file : 

```C
/* File: "observer_debug001.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*@
 assigns \nothing;
 ensures \result == (((((ext_sqrt_0) / (ext_maximum_time_for_horizontal_violation))) * (((ext_minimal_horizontal_separation) - (ext_sqrt_1)))));
*/
SDouble observer_debug001(const SDouble ext_sqrt_0,
                          const SDouble ext_maximum_time_for_horizontal_violation,
                          const SDouble ext_minimal_horizontal_separation,
                          const SDouble ext_sqrt_1)
{
  const SDouble s0 = ext_sqrt_0;
  const SDouble s5 = ext_maximum_time_for_horizontal_violation;
  const SDouble s6 = ext_minimal_horizontal_separation;
  const SDouble s7 = ext_sqrt_1;
  const SDouble s8 = s7 / s5;
  const SDouble s9 = s6 - s7;
  const SDouble s10 = s8 * s9;

  return s10;
}
```

**Comment by LeventErkok** [comment]
SBV does indeed to aggressive CSE. But it would *never* guess that `ext_sqrt_0` quals `ext_sqrt_1`; if such is the case, that would be a gross bug.

I'm not exactly following what the issue is here. Can you reduce it to something that is directly exhibited from SBV, without going through CoPilot? What's the SBV code that gives rise to the above C program?

**Comment by Varmin** [comment]
Actually, after more investigation, it seems that there was a serious bug in the Copilot backend sending the code to SBV (corrected https://github.com/Copilot-Language/copilot-sbv/commit/6bc043117eac17e918ac7a6363b866058911e59f ). 

So it seems that this was not due to a too much aggressive optimization, but to a bug from Copilot.

Thanks.
