### ISSUE TITLE
Symbolic equality is disallowed

### ISSUE THREAD

**Issue by wdanilo** [LeventErkok/sbv#187]
Hello! This might not be a bug, maybe the usage is wrong. I want to check if forall `x` and `y` with given constrains `x + y = y + x`, where `+` is a "plus operator", not addition. I mean, I want to create contexts, about the `+` expression (like associativity, identity etc) and then check for further equalities, like check if `a + (b + c) == (a + c) + b`. 

I was trying to accomplish it using something like:

```haskell
main = do
    let x = forall "x"
    let y = forall "y"
    out <- prove $ (x .== x)
    print "end"
``` 

but it seems we cannot use the `.==` operator on symbolic values. Is this a missing feature or wrong usage?

**Comment by LeventErkok** [comment]
Your use of the API isn't quite right. The simplest way to prove mathematical equalities would be to use simple functions. For instance, associativity over unbounded Integers can be expressed this way:

```haskell
prove $ \x y z -> x + (y + z) .== (x + y) + (z :: SInteger)
```

If you need a more programmatic interface (and sometimes you will), then you can use the `Symbolic` monad, thusly:

```haskell
plusAssoc1 = prove $ do x <- sInteger "x"
                        y <- sInteger "y"
                        z <- sInteger "z"
                        return $ x + (y + z) .== (x + y) + z
```

I'd recommend browsing through many of the examples provided in the hackage site to get familiar with the API: https://hackage.haskell.org/package/sbv

Of course, feel free to post further questions here too.
