### ISSUE TITLE
Changing the linker

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#188]
Hi. Is it also possible to add the possibility to change the linker (for cross compilation purposes), as it was done for the compiler in the Makefile ?

Thanks.

**Comment by LeventErkok** [comment]
I'm not a Makefile expert; do you know if this is possible via a conditional assignment like we did with CC? If that works we can do a similar trick. Otherwise, we'll need to figure out how to do so.

**Comment by Varmin** [comment]
Yes I tried to do it just like the CC, and it worked fine. You just have to add a question mark in front of AR and ARFLAGS.

**Comment by LeventErkok** [comment]
Hmm; I'm not following.

AR and ARFLAGS are for the archiver; when we generate a lib file, when used with `compileToCLib`.

But your original message was about the linker, not the archiver. Did you mean the archive utility in the first place?

**Comment by Varmin** [comment]
Ah yeah sorry. I didn't notice. It's indeed about the archiver I'm talking about (I use armv7a-unknown-linux-gnueabi-ar instead of ar).

**Comment by LeventErkok** [comment]
that makes sense now. ok; I'll do the changes shortly.

**Comment by LeventErkok** [comment]
@Varmin Just committed a fix; please test and let me know if all is well

**Comment by Varmin** [comment]
I tried it on two computer, and it worked really well. I do not have that much examples to run it on, but I assume that the tests done are sufficient.

Thanks.
