### ISSUE TITLE
Signum

### ISSUE THREAD

**Issue by Varmin** [LeventErkok/sbv#189]
I was looking at the code generated by the signum operator, and it seems to do something quite strange : 

  signum a
    -- NB. The following "carefully" tests the number for == 0, as Float/Double's NaN and +/-0
    -- cases would cause trouble with explicit equality tests.
    | hasSign a = ite (a .> z) i
                $ ite (a .< z) (negate i) a
    | True      = ite (a .> z) i a
    where z = genLiteral (kindOf a) (0::Integer)
          i = genLiteral (kindOf a) (1::Integer)

This compares to zero, and if it is neither greater or smaller than 0 it returns this number (instead of something else like 0). Is this voluntary (what should the function signum do in case of floats numbers that are NaN or Inf) ?

Thanks.

**Comment by LeventErkok** [comment]
Here's the Haskell definition of signum for Floats:

```haskell
    signum x | isNegativeZero x = x
             | isNaN x          = x
             | x == 0           = 0
             | x > 0.0          = 1
             | otherwise        = negate 1
```

So, you have to be really careful around `+/-0`; which I do believe the above definition correctly captures. Did you find a case where it behaves incorrectly?

**Comment by Varmin** [comment]
Ah ok, I see better now. I was just wondering at how it was defined in case of infinites, but it seems that it works well with the above definition.

Thanks.

**Comment by LeventErkok** [comment]
Floats are always tricky; so do report if you find any discrepancy..
