### ISSUE TITLE
Remove GHC 7.8 compat layers

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#200]
There's quite a bit of code in SBV to make it compile with GHC 7.8; added by @acfoltzer acfoltzer to maintain Cryptol's commitment to GHC 7.8 series. Adam volunteered to remove all that code once Cryptol goes 7.10 only as well. This ticket tracks that removal.

Thanks Adam!

**Comment by acfoltzer** [comment]
:laughing: can't wait!

**Comment by acfoltzer** [comment]
And closed with 9fe5f61050cc4a4f9c9d63432bd2cb81a5d96253
