### ISSUE TITLE
Move to tasty for the test-suite

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#212]
Our HUnit based test infrastructure, while adequate, isn't the easiest to use. I'm not sure how much benefit we would get, but moving to tasty (as we did in sbvPlugin) would make the test-code a lot cleaner and easy to work with. Something to tackle on a rainy day..

**Comment by kanishka-azimi** [comment]
I can attempt this a bit, to get familiar with the project as a whole.

**Comment by LeventErkok** [comment]
By all means! Do take a look at how I structured the test suite for sbvPlugin: https://github.com/LeventErkok/sbvPlugin

Ideally, I'd like SBV to use exactly the same structure as sbvPlugin. In particular, I would like the

     Executable SBVUnitTests

part to be removed from the cabal file: https://github.com/LeventErkok/sbv/blob/master/sbv.cabal#L142

But feel free to structure it in any way that makes sense to you.

Thanks!

**Comment by kanishka-azimi** [comment]
Fortunately or unfortunately, I have written a few tasty test suites by now (including for some peers at work that didn't believe in testing at all (: ), so what I produce will look like what you expect.

I strangely enjoy adding tests, mostly seeded from taking a formal verification class a while back and seeing the possibilities that tests can lead up to eventually.

**Comment by LeventErkok** [comment]
Excellent. Here's something to think about:

- When we run the test locally, we want the "entire" suite: Those that require an SMT solver to be available as well as those that don't. (There's quite a number of both kinds)

- When we push to github, Travis automatically picks up the push and runs the test suite. On the travis site there is no SMT solver installed. So, we have to arrange for only those test that don't require a solver to run.

Currently, this is handled rather by a kludge:

 - This runs everything: https://github.com/LeventErkok/sbv/blob/master/sbv.cabal#L142
 - This runs all the tests that don't require a solver to be present: https://github.com/LeventErkok/sbv/blob/master/sbv.cabal#L216

Ideally, I'd like to get rid of the SBVUnitTests executable completely, and somehow arrange the test suite so when running local everything gets run, but on Travis only the non-solver tests are run.

But I'm also open to a totally new way of structuring the tests, and you seem to have thought about this before. So, feel free to propose a completely different structure, so long as it addresses the issue of local (with solver), and remote (without solver) discrepancy.

**Comment by kanishka-azimi** [comment]
Been there (:. I usually use a flag with two test-suite stanzas. The flag
enables the integration test suite stanza, and the flag defaults to
disabling. A makefile helps provide handy targets with the appropriate flag
setting when developing locally, running full test suite locally, or
running under CI.

**Comment by LeventErkok** [comment]
Fantastic, there's indeed a Makefile that does something very similar: 

  - Runs the "internal" suite, i.e., no solver: https://github.com/LeventErkok/sbv/blob/master/Makefile#L47
  - Runs the "external" suite, i.e., with the solver: https://github.com/LeventErkok/sbv/blob/master/Makefile#L39
  - Runs the "doctests" (only locally): https://github.com/LeventErkok/sbv/blob/master/Makefile#L33

If you can make all these happen but without all these kludges, that'd be fantastic. But the main objective is really getting rid of the `SBVUnitTest` executable from being built and distributed.

**Comment by LeventErkok** [comment]
Another idea might be to convince Travis to install a copy of Z3 somehow, I think there are some tricks you can play to get it to do so. But I'm not convinced this is the right thing to do. (In particular, it would increase build times significantly.) Just tossing that as an idea; not necessarily a requirement.

**Comment by kanishka-azimi** [comment]
I will resume Monday, got some minimal time in today getting familiar and building with `stack`, two notes for approaching external dependencies:
- One can build a mock or a very limited power in-memory solver that always succeeds for the sake of running the tests. reflex library builds a full in-memory version of a "host" to test the rest of their system, if you skim the reflex library test sources
- Some people host compiled executables for download during travis test runs, you could potentially host the solver executables you need, if there is no direct link to them already, then download and cache them in the Travis runs. I don't know Travis extensively, but you might be able to configure the test runs so that it runs all the faster tests first in separate jobs, and then run the slow extensive test last, allowing you to get feedback from the earlier successes/failures earlier.

**Comment by LeventErkok** [comment]
The test suite crucially depends on the existence of a full-fledged solver.. (And most likely Z3 actually.) So, a mock solver wouldn't really work.

I'd suggest let's go with the "no-solver" tests on travis, full-tests locally option first, I'd say; as it currently stands. Once we replicate the current functionality, we can think about improving it by hosting a Z3 executable perhaps.
