### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by expipiplus1** [LeventErkok/sbv#214]
The link to http://smtlib.cs.uiowa.edu/theories/Reals.smt2 in the documentation here https://hackage.haskell.org/package/sbv-5.9/docs/Data-SBV.html#g:10 is no longer working.

Perhaps the link should point to this page: http://smtlib.cs.uiowa.edu/theories-Reals.shtml

**Comment by LeventErkok** [comment]
@expipiplus1 Thanks for the report.. Indeed there were a bunch of broken links reported a little while ago: #210 

I've since fixed all the links in HEAD; just didn't make it to hackage yet.

**Comment by LeventErkok** [comment]
@expipiplus1 SBV 5.10 is now on hackage, with all the broken links fixed. Please do report if you notice any further link/doc issues. Thanks!

[Hackage hasn't built the documentation for 5.10 yet; but I'm hoping it'll show up shortly.]

**Comment by LeventErkok** [comment]
There was a snafu with 5.10; so 5.11 is now on hackage..

**Comment by expipiplus1** [comment]
cool stuff, thanks!
