### ISSUE TITLE
maximumOr

### ISSUE THREAD

**Issue by tomjaguarpaw** [LeventErkok/sbv#220]
Could we please have a function like this?  I'm happy to submit a PR if you tell me the name you want for it and which module it should go in.

    -- | The maximum of the list, or the default value if the list is empty.
    smaximumOr :: SBV.OrdSymbolic a => a -> [a] -> a
    smaximumOr def xs = case xs of
      [] -> def
      _  -> foldl1 SBV.smax xs

**Comment by LeventErkok** [comment]
Your definition can be simplified to:

```
sMaximumOr = foldl smax
```
I usually shy away from adding such definitions as `foldl smax` is quite a Haskell idiom; but if you want you can submit a PR and put it in `Data/SBV/BitVectors/Model.hs` together with similar functions like `allEqual` etc; and export from `Data.SBV`.

**Comment by tomjaguarpaw** [comment]
Only if some element of the list is greater than or equal to `def`.  But actually your version is closer to what I want anyway, thanks.
