### ISSUE TITLE
Matrix support

### ISSUE THREAD

**Issue by lauratitolo** [LeventErkok/sbv#221]
In our language Copilot (https://github.com/Copilot-Language) we use the SBV library to generate C code corresponding to a given Copilot program, and to verify properties on it.
Lately, we are trying to include in Copilot support for matrices of (floating-point) numbers in order to model some control theory problem.
To this end, it would be great to have support for matrices of symbolic values in the SBV library.
In particular, we would need a data type SMatrix a b (similar to the SArray a b data type) which maps into SMT-lib arrays of the form (Array Int (Array Int a)) where a can be Int or Real.  We would also need the corresponding C code generation (I think that we would need the counterpart of cgInputArr, cgOutputArr, etc… for matrices).

Terms of the form (Array Int (Array Int Int)) and (Array Int (Array Int Real)) are handled by the logics AUFLIA and AUFLIRA, respectively.
Below, an example of some matrices properties that we are interested in. The function leq2 checks if a matrix m1 is less or equal to a matrix m2, while the function same-size, checks if two matrices have the same number of colums  and rows.

```
(set-logic AUFLIRA)
(declare-const c (Array Int Real))
(declare-const d (Array Int Real))
(declare-const a (Array Int (Array Int Real)))
(declare-const b (Array Int (Array Int Real)))

(declare-fun cols ((Array Int (Array Int Real))) Int)
(declare-fun rows ((Array Int (Array Int Real))) Int)

(define-fun same-size ((m1 (Array Int (Array Int Real))) (m2 (Array Int (Array Int Real)))) Bool
  (and (= (cols m1) (cols m2)) (= (rows m1) (rows m2)) )
)

(define-fun leq ((a1 (Array Int Real)) (a2 (Array Int Real))) Bool
        (forall ((i Int)) (<= (select a1 i) (select a2 i)))
)

(define-fun leq2 ((m1 (Array Int (Array Int Real))) (m2 (Array Int (Array Int Real)))) Bool
        (forall ((i Int)) (leq (select m1 i) (select m2 i)))
)

(assert (= (cols a) 3))
(assert (= (cols b) 3))
(assert (= (rows a) 2))
(assert (= (rows b) 2))

(assert (forall ((m (Array Int (Array Int Real))) (n Int))
           (forall ((idx Int) (a (Array Int Real)))
              (and (= (cols (store m idx a)) (cols m) )
                   (= (rows (store m idx a)) (rows m) )) )
        )
)

(assert (same-size (store a 1 (store c 1 3)) (store b 1 (store d 1 1))))
(assert (leq2 (store a 1 (store c 1 3)) (store b 1 (store d 1 1))))

(check-sat)
```

**Comment by LeventErkok** [comment]
@lauratitolo Thanks for the description.

Note that your SMTLib contains quantified assertions; SBV has no means to create such assertions; so I'm not sure if that'll be a showstopper for you.

Even in the simplest case, it would help me a lot to see example SBV code that you tend to write that uses one-dimentional `SArray` construct; both in theorem proving and code-generation. It doesn't need to be complicated, just the sort of thing you typically need. Based on that, I'll see how to generalize that to multiple-dimensions. If you could provide SBV code samples of that (hopefully without any Copilot specific code to keep it simple), that'd be a good starting point to investigate how to go about this.

**Comment by LeventErkok** [comment]
@lauratitolo Closing this, seems inactive. Please re-open if this is still an issue and/or you have further comments.
