### ISSUE TITLE
Optimizing with variables of different types

### ISSUE THREAD

**Issue by tomjaguarpaw** [LeventErkok/sbv#228]
The current optimization functions ('minimize` etc.) only deal with `n` variables all of the same type.  Is it possible to mix types?

**Comment by LeventErkok** [comment]
Just like #227, this is certainly possible; but it's hard to come up with a "generic" enough API to be included with SBV. The expectation is that users implement their own search strategy on top of SBV, as all the necessary bits and pieces are available to them.

Happy to help if you try it out and run into any difficulties.
