### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#235]
@brianhuffman @robdockins @acfoltzer 

We haven't made a release in quite some time, as the changes were rather small. But I'm noticing that there is enough there by now to warrant a new release.

I'm intending to do one sometime this weekend, unless you guys are working on anything and would like me to hold off. Let me know!

**Comment by LeventErkok** [comment]
Released 5.13 today on hackage.

**Comment by acfoltzer** [comment]
Thanks, Levent!
