### ISSUE TITLE
MonadFix instance for Symbolic?

### ISSUE THREAD

**Issue by rohit507** [LeventErkok/sbv#236]
This would be quite nice to have though I've not tested whether it would work. That said, everything is lazy and the derived instance for `ReaderT State IO` should work fine. 

Alternately, exporting the constructor for Symbolic in Data.SBV.Internals would allows us to add a Standalone Deriving clause to that effect.

**Comment by rohit507** [comment]
Nevermind, it's not working quite as straightforwardly as I hoped. I'll see if I can fix it and make a pull request if I can.

**Comment by LeventErkok** [comment]
@rohit507 Aside from implementation, I'm curious what the use case would be for a MonadFix instance for Symbolic. If you can provide an example where it comes in handy, I'd like to see it.
