### ISSUE TITLE
Constant folding fails for svRotateLeft and svRotateRight on zero-width arguments

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#240]
As you can see, `svShiftLeft` does constant-folding properly on a 0-width concrete argument, but `svRotateLeft` yields a symbolic result. See also GaloisInc/Cryptol#397.
```
Prelude Data.SBV.Dynamic> svShiftLeft (svInteger (KBounded False 0) 0) (svInteger (KBounded False 3) 3)
0 :: SWord0
Prelude Data.SBV.Dynamic> svRotateLeft (svInteger (KBounded False 0) 0) (svInteger (KBounded False 3) 3)
<symbolic> :: SWord0
```
I suspect this is caused by the use of `svRem` with a modulus of 0 in the definition of `svRotateLeft`.

**Comment by LeventErkok** [comment]
Quite right. Looks like the dynamic interface did *not* follow the regular SBV semantics here. To wit:

```
Prelude Data.SBV> (3 :: SWord8) `sQuotRem` (0 :: SWord8)
(0 :: SWord8,3 :: SWord8)
```

But:

```
Prelude Data.SBV.Dynamic Data.SBV> let x = svInteger (KBounded False 3) 3
Prelude Data.SBV.Dynamic Data.SBV> let y = svInteger (KBounded False 3) 0
Prelude Data.SBV.Dynamic Data.SBV> x `svQuot` y
<symbolic> :: SWord3
Prelude Data.SBV.Dynamic Data.SBV> x `svRem` y
<symbolic> :: SWord3
```

(Looks like you we also missed `svQuotRem`..)

I think the dynamic versions should follow suite and implement:

```
 svQuotRem x 0 = (0, x)
```

essentially. But perhaps you had a good reason for not doing so?

**Comment by LeventErkok** [comment]
@brianhuffman @yav @acfoltzer 

Hey guys.. I'm planning to do a new SBV release in the next week or so. Do you want to address this ticket? Or anything else you want to sneak in before the release happens?

**Comment by TomMD** [comment]
CCing @atomb here too since I've seen messages from him regarding Cryptol maintenance.

**Comment by LeventErkok** [comment]
@brianhuffman SBV 7.0 release is pending, so I pushed a fix for this to make the semantics of these dynamic operations the same as those of their typed counterparts.

I can't tell for sure if this'll fix the issue in Cryptol of course, but the expressions reported in this ticket now behave properly. Feel free to re-open the ticket if the semantics is still not quite right.
