### ISSUE TITLE
Data.SBV.Dynamic.svIsSatisfiableInCurrentPath counterexample?

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#249]
This may simply be my lack of Haskell knowledge, but is it possible to get a counterexample when using `svIsSatisfiableInCurrentPath`?

Assume `svIsSatisfiableInCurrentPath` is being used to check for an error condition somewhere deep in the code. Currently, when I use it I am able to print an error that something went wrong, but I can't give the user any leads on where to look for the problem. Something like this:

```haskell
check :: SVal -> Symbolic ()
check a = do
  assertion_fails <- svIsSatisfiableInCurrentPath a
  return $ if assertion_fails then error "oh no!" else ()
```

Is it possible to print out a satisfying input instead?

**Comment by LeventErkok** [comment]
Not currently; the internal-sat check throws out the model and simply returns a bool. However, we can add a function that returned the model rather easily.

But this sounds like a weird thing to do: If you cared about the model itself, wouldn't you just pose this as a satisfaction problem in the first place? If you can describe use case, perhaps we can come up with a different alternative.

**Comment by jpziegler** [comment]
Basically, in my application, new `svBool` instances are introduced dynamically during execution. Each of these represent the creation of a temporary, virtual wire. This wire is used in various computations, after which it is "terminated". Upon termination, it must have the same value that it started with. It is possible for the user to make a mistake which results, for some inputs, in an improper termination.

This means that it is not obvious how to pose a relevant satisfaction problem, since these temporary wires are generated dynamically and aren't directly available as inputs or outputs.

Is this is sufficiently clear? Any ideas?

**Comment by LeventErkok** [comment]
@jpziegler It's really hard to make a suggestion without knowing any further details. But in either case, I think returning the model would be just fine in that context.

In fact, I just pushed a change to github, which changes the signature:

```
svIsSatisfiableInCurrentPath :: SVal -> Symbolic Bool
```
to:

```
svIsSatisfiableInCurrentPath :: SVal -> Symbolic (Maybe SatResult)
```

The idea is that we'd return `Nothing` if it's not satisfiable, and a regular `SatResult` (which you can then extract a model out of) if it is satisfiable.

Can you give that a try and see if it works for you? You'll have to build out of github, I hope that's OK.

**Comment by jpziegler** [comment]
Wonderful!

Using my existing installation, I tested against the following dummy version with the same type signature:
```haskell
svIsSatisfiableInCurrentPath' :: SVal -> Symbolic (Maybe SatResult)
svIsSatisfiableInCurrentPath' a = do
  b <- svIsSatisfiableInCurrentPath a
  return $ if b then Just undefined else Nothing
```
I altered my code to fit, and it typechecks and seems to behave properly. Along the lines of:
```haskell
check :: SVal -> Symbolic ()
check a = do
  ms <- svIsSatisfiableInCurrentPath a
  return $ case ms of
    Just s -> error (show s)
    Nothing -> ()
```
Presumably, when I actually have access to the model, it will print a nice counterexample. I'll go ahead and close. When I'm able to test the new code, if there are any problems, I can reopen.

I'll also look into putting together a better description of the problem.

**Comment by LeventErkok** [comment]
Great! Let me know if you see any issues.

**Comment by jpziegler** [comment]
Following up: Finally got a chance to test the "real" version of `svIsSatisfiableInCurrentPath` and it works like a dream! My proof attempts now generate an error when an invalid state is detected and print a counterexample to go along with it. Much easier to debug now!

**Comment by LeventErkok** [comment]
@jpziegler Fantastic! I'm afraid I've some bad news though.. :-)

SBV 7.0 is coming out in a few days. And the function `svIsSatisfiableInCurrentPath` is removed from the API. The reason for this is that I've rewritten the entire backend of SBV to support what I call user queries. In this mode, you'll be able to maintain a connection to the SMT solver, and issue arbitrary SMTLib commands. Here's a simple example: https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Examples/Queries/AllSat.hs

Unfortunately `svIsSatisfiableInCurrentPath` no longer makes sense in this new setup. You can of course just *not* upgrade SBV, but if and when you do, you'll have to move to using the new query style..  And I'd strongly recommend moving to SBV 7.0: The Query mode is the right way to do what you wanted in the first place, and I'm more than happy to help out with the details. Actually, I'd strongly encourage you to upgrade and move to the new style, as I think you'll find it more suitable for your needs.

Happy to answer any questions regarding this change. While it'll be a bit of work to move to the new system, I do believe it's the right direction to go. Feel free to ask any questions you might have, or let me know if you run into any issues.
