### ISSUE TITLE
Retrieving an Unsat Core

### ISSUE THREAD

**Issue by rohit507** [LeventErkok/sbv#257]
Does SBV have an accepted method for retrieving an unsat core? Ideally in some way that can allow us to map those cores back into haskell-space? 

Manually reading them has helped us more-quickly identify the reasons why some of our problems are UNSAT, but it would be nice to do so algorithmically.

**Comment by LeventErkok** [comment]
I think this is a great idea.. Just added an implementation of unsat-cores, can you build from github and give it a shot? I'd like to know that it serves your purposes and gets some testing before released.

Here's an example use case to get you started: https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Examples/Misc/UnsatCore.hs

Let me know what you think!

**Comment by rohit507** [comment]
Oh that's awesome, let me play with it a bit and see how I could make use of it.

**Comment by LeventErkok** [comment]
@rohit507 Any feedback? I'm planning to make a release in the next few weeks, so I'd like to make sure it's working well for you.

**Comment by rohit507** [comment]
Yup, it's working brilliantly for me. I've got a toy version of the tool i'm working on [here](https://github.com/rohit507/sbv-synthesis-toy) if you want to take a look. I'm still working on finding the time to add a few more parts to the system, and add the pseudo-incrementality for those tests.

**Comment by LeventErkok** [comment]
@rohit507 That looks cool, though it's a bit difficult to follow. I'd be interested to hear more about it when you write some documentation!

Also, if you could tell me your full name, I'd like to add it to acknowledgements section.

Regarding incrementality: I'm not sure if you mean something else: But I'm working on adding incrementality in the "incremental" branch; though it's not quite ready for public consumption yet. I'll ping when it's good enough to test.

**Comment by rohit507** [comment]
Oh sure, I'm just working on a version that repeatedly runs separate
problems in a way that could be converted to something genuinely
incremental. Documentation as well.

Also my name is "Rohit Ramesh".

Rohit.

**Comment by LeventErkok** [comment]
Cool. I'm closing this ticket. I'll ping you separately on the "interactive" issue when that becomes a bit more mature.

**Comment by LeventErkok** [comment]
@rohit507 Note that extraction of unsat-cores just changed slightly, here's the new style:

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Examples/Misc/UnsatCore.hs#L15-L25

This will be released in the next Hackage release (6.2); but if you build from github (master branch), you might have to modify your code slightly.
