### ISSUE TITLE
distinct for SymbolicEq

### ISSUE THREAD

**Issue by arrowd** [LeventErkok/sbv#264]
It would be nice to have ability to perform a `distinct` operation from SMTLib2 standard, like this http://rise4fun.com/Z3/RtS5

Currently I have to do

forM_ (combinationsOf2 vars) $ \[x, y] -> constrain $ x ./= y

**Comment by LeventErkok** [comment]
Any reason you can't use [allDifferent ](https://hackage.haskell.org/package/sbv-6.0/docs/Data-SBV.html#v:allDifferent)?

     constrain $ allDifferent xs

should do it, I think.

**Comment by arrowd** [comment]
Hum. The list of `vars` from my example above is very large. I suspect, this becomes a bottleneck for a solver, and using builtin `distinct` should help that. Judging from `allDifferent` implementation, it should generate the same long chain of inequalities for all vars combinations. Am I mistaken?

**Comment by LeventErkok** [comment]
Looking at Z3 code: https://github.com/Z3Prover/z3/blob/master/src/ast/rewriter/bool_rewriter.cpp#L804

There seems to be some rewrites first, which are unlikely to apply in the case of SBV as the simple equalities would've dropped out on the Haskell side as well. So, it would end up simply generating the same chain, unless you have more than 4294967295, the default value of the parameter `blast_distinct_threshold`.

Of course, the bottleneck would be in sending the formula to the solver; and I doubt in the actual solving process itself. Do you have any evidence to suggest otherwise?

In either case, it is perfectly OK for SBV to send down a call for `distinct` too: It would cut down on the communication for sure, which is always a good thing. I can take a look at it later tonight, most likely.

**Comment by LeventErkok** [comment]
@arrowd I've added the `distinct` function as we discussed: https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Core/Model.hs#L500-L509

Can you build from github and give it a shot? I'd like to hear, especially, if you find that it performs measurably better for your use case. (And of course that it works correctly!)

**Comment by LeventErkok** [comment]
@arrowd On second thought, it's a wart that we have two functions (`allDifferent`) and (`distinct`), that have different types, but are very similar in their operation. I've an idea to merge the two by putting them directly into the `EqSymbolic` class. Please hold off testing till I get implemented.

**Comment by LeventErkok** [comment]
@arrowd Ok, changes pushed. `allDifferent` is gone; and `distinct` is introduced, which should do what you wanted. I'd be really glad to hear if it does the job as you intended.

Also, if you can tell me your full name, I'd like to put it in the acknowledgments list. (I can't tell from your github profile.)

Feel free to close this ticket based on your findings, or report further issues!

**Comment by arrowd** [comment]
That certainly improved things! `compileToSMTLib` for my problem had following stats:

execution time:
average: 4,82916666666667 s
stdev: 0,3759037419186 s

allocations:
average: 3.262.824.326 bytes
stdev: 449.881 bytes

Now it is

execution time:
average: 3,54458333333333 s
stdev: 0,460613760358811 s

allocations:
average: 1.130.396.379 bytes
stdev: 4.325.184 bytes

This didn't helped with my problem though, but that's unrelated. In short, this is awesome, but is moving `compileToSMTLib` into `Internal` necessary? I've been often using it as debugging means.

My name is Gleb Popov, thanks for working on this.

**Comment by LeventErkok** [comment]
That's good to hear.. If you find other issues/improvements please get back in touch.

Regarding the move of `compileSMTLib` to `Internal`: I've received feedback that `Data.SBV` can be quite intimidating to people; as it exports a lot of stuff. I agree with that to a certain degree: When I show people SBV and point to the Haddock documentation, there's so much stuff there it's hard to get a feeling of what's important.

Note that you can get the same functionality like this:

```
    satWith z3{smtFile = Just "myfile.smt2"} property
```

which is actually a lot easier to use and doesn't require an import. Let me know if that doesn't work for you for whatever reason.
