### ISSUE TITLE
Possible side project: Embed SBV via hint

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#272]
Possible side project; perhaps even as a separate package that uses sbv underneath.

Use the infrastructure supported by hint: https://hackage.haskell.org/package/hint

The idea is that you'd run SBV just as usual, but then drop into a read-eval-print loop of sorts as SBV switches to query mode. Then the user can send strings down to the solver, using SBV functions directly.

Not sure how much ROI would this have, and hint is a huge dependency; but could be a fun side project if anyone is interested.

**Comment by LeventErkok** [comment]
This is surely an overkill! Closing.

**Comment by TomMD** [comment]
I rather like the idea... though it certainly isn't an sbv "issue".  Thanks for letting me pilfer your idea...

**Comment by LeventErkok** [comment]
@TomMD If you are interested in this line of thinking, I've got a better "idea" that you are more than welcome to steal.

Rewrite sbvPlugin (https://hackage.haskell.org/package/sbvPlugin) using Conal's lambda-ccc (https://github.com/conal/lambda-ccc).

If you can do that, and assuming it works, I think sbvPlugin would become a viable project for people to use in "real life." See this talk by Conal for details: https://www.youtube.com/watch?v=vzLK_xE9Zy8

I'd be interested in collaborating on this, if someone takes the charge.
