### ISSUE TITLE
Add 7.1 to Stackage

### ISSUE THREAD

**Issue by vimuel** [LeventErkok/sbv#296]
Latest version on Stackage is 5.14, would be great to have 6.1.

**Comment by LeventErkok** [comment]
Yes indeed. Unfortunately this is blocked by https://github.com/GaloisInc/cryptol/issues/424

Hopefully, Cryptol will get a release soon at which point stackage will keep up.

@acfoltzer @atomb @brianhuffman

**Comment by vimuel** [comment]
Thank you for that information @LeventErkok.

I won't close the issue for now, in case others have the same question, but feel free to close it if you want.

**Comment by LeventErkok** [comment]
@vimuel Yes.. I'll keep this open till we get a recent version on stackage. Good to know there are people out there who want this, thanks for getting in touch.

**Comment by LeventErkok** [comment]
A new Cryptol release is pending soon, per Aaron.. That should resolve this problem.

**Comment by vimuel** [comment]
Thanks for the update. Feel free to close this.

**Comment by LeventErkok** [comment]
Opened a pull request: https://github.com/fpco/stackage/pull/2692

**Comment by LeventErkok** [comment]
It's there! https://www.stackage.org/nightly-2017-08-07/package/sbv-7.1

Hopefully it won't be dropped again..
