### ISSUE TITLE
Incorrect implementation of `svSetBit` (?)

### ISSUE THREAD

**Issue by robdockins** [LeventErkok/sbv#320]
The current implementation of `svSetBit` seems like it is incorrect.

```
-- | Set a given bit at index
svSetBit :: SVal -> Int -> SVal
svSetBit x i = x `svXOr` svInteger (kindOf x) (bit i :: Integer)
```

This instead implements a bit flip operation.

Related: it would be nice to have a 'clear' operation and also an 'update' operation (copy the value of a symbolic bit into a word).

**Comment by LeventErkok** [comment]
@brianhuffman 

Quite right.. I pushed a fix: https://github.com/LeventErkok/sbv/commit/f54cf2a7b808cbcba44cbf05836bdecd5ec3ad40

Note that this is only used from the dynamic interface. (`Data.SBV.Dynamic`) Hopefully Cryptol didn't use this function? Would be good to check on your side.

For the regular SBV side, the functions are just `setBit` and `clearBit` and they are correctly implemented. (I hope!) There is also `setBitTo` that implements the combination, when we want to jam a bit value to a particular position. I think your `update` is essentially shift-right and an and with 1? Not sure if it should go into the library, as there are myriads of other things that can be written. But please feel free to submit a patch if it simplifies life elsewhere.

**Comment by LeventErkok** [comment]
@robdockins I'm closing this as resolved, feel free to reopen. I'll release 7.1 soon, which will include this patch.

**Comment by robdockins** [comment]
Thanks Levent.  Searching the Cryptol codebase suggests that we weren't already using `svSetBit`, so that's good.
