### ISSUE TITLE
Test suite improvements

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#321]
- Solver-arithmetic tests (`TestSuite.Basics.ArithSolver`) causes issues on remote hosts:
         - This is a very heavily loaded test with lots of calls to Z3.
         - Remote hosts usually time-out since they are impoverished machines/VMs with low memory.
         - The environment variable `SBV_HEAVYTEST_PERCENTAGE` controls what percentage of these tests we run on a given remote build. See `.travis.yml` and `.appveyor.yml` files for current values.
         - When run locally, we of course run everything.
         - Would be nice if we can run full (or at least larger) test suites on remote machines too.

- Arithmetic/constant folding tests:
       - Right now we're always testing with "fixed" values.
       - There's a quickcheck based suite as well, but we need to port our tests to use this interface. Note that QC is usually more expensive since it tests 100 cases; for constants we actually pick very few things! A balancing act is needed.
       - In fact, it would be good to overhaul that part of the test-suite and do dynamic cases too.

- Dynamic interface tests
       - Test suite has almost no tests for the dynamic interface.
       - Since Cryptol is the main customer for this interface, anytime they test, we get "free" testing.
       - Would be nice if we had our own tests, however.

-  More doctests
       - The code has several instances of test cases sprinkled.
       - At least some can be turned into multi-line doctest instances. 

- Float/Double -> Integer/Real conversion tests are currently commented out, because they aren't supported by Z3 (or Mathsat). Eventually we should turn these on. See the code in `SBVUnitTest/TestSuite/Basics/ArithSolver.hs`

 - fpRem tests take a looong time, so significantly reduced. Search for `vsFPRem` in `SBVUnitTest/TestSuite/Basics/ArithSolver.hs`

 - Remote quickchecks: Currently quickcheck tests only run locally, since it adds too much to the load. Perhaps we can use a limited number of tests and run them remotely as well, once the quick-check suite is well established.

 - Use tasty/discover: https://hackage.haskell.org/package/tasty-discover

**Comment by kanishka-azimi** [comment]
>- Would be nice if we can run full (or at least larger) test suites on remote machines too.

In a haskell reddit comment last year, someone mentioned that they went all out on their test suite, distributing them to a few spot EC2 instances with each test run. Maybe a corporate sponsor will provide you with a budget for spot EC2 instances or beefier account on Travis?

**Comment by LeventErkok** [comment]
That'd be nice, but I don't see it happening anytime soon. I know of a few commercial endeavors using SBV to a certain extent, but I'm not aware of anyone willing to put up the money/infrastructure to do so.

If this was paid work, I'd actually start from scratch and redesign SBV and it's test-suite, but there just isn't enough impetus to do so and it is a lot of work to do for free!

**Comment by LeventErkok** [comment]
As SBV matures, this is less of an issue; and I've kind of given up on being able to run tests on CI. (Remote machines are just not powerful enough. Furthermore, getting nightly z3 installations is always problematic, and even simple changes cause a lot of trouble as they provide different--but just as valid--counterexamples.)

A fresh rewrite SBV can probably benefit from a different approach to how tests are structured to accommodate for these, but for the time being there isn't really an actionable item here for SBV to tackle.
