### ISSUE TITLE
unknown parameter 'global_declarations' using Z3 4.4.1

### ISSUE THREAD

**Issue by peddie** [LeventErkok/sbv#324]
I've tried running the first optimization example given [in the haddocks](https://hackage.haskell.org/package/sbv-7.1/docs/Data-SBV.html#g:34) in `ghci`:

```
> optimizeWith z3 { verbose = True } Lexicographic $ \x y -> minimize "goal" (x+2*(y::SInteger))
** Calling: z3 -nw -in -smt2
[GOOD] ; Automatically generated by SBV. Do not edit.
[GOOD] (set-option :print-success true)
[FAIL] (set-option :global-declarations true)
*** Exception: 
*** Data.SBV: Unexpected non-success response from Z3:
***
***    Sent      : (set-option :global-declarations true)
***    Expected  : success
***    Received  : (error "line 2 column 33: unknown parameter 'global_declarations'
***                Legal parameters are:
***                  auto_config (bool) (default: true)
***                  debug_ref_count (bool) (default: false)
***                  dump_models (bool) (default: false)
***                  memory_high_watermark (unsigned int) (default: 0)
***                  memory_max_alloc_count (unsigned int) (default: 0)
***                  memory_max_size (unsigned int) (default: 0)
***                  model (bool) (default: true)
***                  model_validate (bool) (default: false)
***                  proof (bool) (default: false)
***                  rlimit (unsigned int) (default: 4294967295)
***                  smtlib2_compliant (bool) (default: false)
***                  timeout (unsigned int) (default: 4294967295)
***                  trace (bool) (default: false)
***                  trace_file_name (string) (default: z3.log)
***                  type_check (bool) (default: true)
***                  unsat_core (bool) (default: false)
***                  verbose (unsigned int) (default: 0)
***                  warning (bool) (default: true)
***                  well_sorted_check (bool) (default: false)")
***    Exit code : ExitFailure (-15)
***
***    Executable: /usr/bin/z3
***    Options   : -nw -in -smt2
***
*** Backend solver reports it does not support this option.
*** Check the spelling, and if correct please report this as a
*** bug/feature request with the solver!

CallStack (from HasCallStack):
  error, called at ./Data/SBV/SMT/SMT.hs:722:61 in sbv-7.1-DmFNfpnQ7TK901eHoOi0Da:Data.SBV.SMT.SMT
```

I'm using Z3 version 4.4.1, which [seems to be the default in most versions of debian](https://packages.debian.org/search?suite=all&arch=any&searchon=names&keywords=z3):

```
$ z3 --version
Z3 version 4.4.1
```

Has something changed, or are there some versions of Z3 that SBV is not compatible with?

**Comment by LeventErkok** [comment]
Latest release of SBV relies on a much newer version of Z3 than 4.4.1, unfortunately; Z3 folks have been making a lot of changes that SBV takes advantage of, but their releases haven't kept up.

Would it be possible for you to get a copy from here: https://github.com/Z3Prover/bin/tree/master/nightly

That would fix the issue; you can also directly build from their sources if you like.

**Comment by peddie** [comment]
Thanks for the amazingly fast turnaround.  I now found the minimum required version on the github website, but might it make sense to add it to the haddock documentation as well?

**Comment by LeventErkok** [comment]
Z3 moves fast, and in fact some changes they put in are precisely to support SBV use cases. But I agree it would be good to mention the fact that you need a recent version. Please feel free to update the docs and send a pull request!

**Comment by peddie** [comment]
Please see https://github.com/LeventErkok/sbv/pull/325 for a tiny documentation change.
