### ISSUE TITLE
Optimisation problems don't work

### ISSUE THREAD

**Issue by mrd** [LeventErkok/sbv#326]
I've copied an example from the SBV source and tried to run it:

```
problem :: Goal
problem = do [x1, x2] <- mapM sReal ["x1", "x2"]

             constrain $ x1 + x2 .<= 10
             constrain $ x1 - x2 .>= 3
             constrain $ 5*x1 + 4*x2 .<= 35
             constrain $ x1 .>= 0
             constrain $ x2 .>= 0

             maximize "goal" $ 5 * x1 + 6 * x2

main = optimize Lexicographic problem
```

Nothing happens, the program just sits there. Examining the transcript, I find that the final command issued by SBV is `minimize`. But that is not enough for Z3, it also needs a satisfiability check in order to do anything, such as calculate values for the objectives.

```
; [17:50:00.555] Sending:
(minimize s12)
```

I modified the transcript and added `(check-sat)` and that seemed to push Z3 into actually doing something.

I've tried this on sbv-7.1 as well as the latest git master.

**Comment by LeventErkok** [comment]
I suspect your Z3 version is rather old. Unfortunately Z3 folks didn't have an official release in a long time, and SBV relies on rather the cutting edge of Z3.

Can you try after installing a more recent version of Z3? You can get a recent release from: https://github.com/Z3Prover/bin/tree/master/nightly. Alternatively, you can build Z3 from their sources located at https://github.com/Z3Prover/z3 as well; but if one of the nightly builds work for you, that should fix the problem.

Let me know if upgrading the Z3 doesn't solve the problem.

**Comment by mrd** [comment]
Yup, I had 4.5 installed, got the latest git and it works. New issue though, I will open a separate one for that.
