### ISSUE TITLE
Universally-quantified constraints cause optimisation problem

### ISSUE THREAD

**Issue by mrd** [LeventErkok/sbv#327]
Going to work with this rather trivial example that has universal quantifiers in the constraints (but not the optimisation goal):
```
do
    a <- sInteger "a"
    [b1, b2] <- sIntegers ["b1", "b2"]
    x <- forall "x" :: Symbolic SInteger
    constrain $ 2 * (a * x + b1) .== 2
    constrain $ 4 * (a * x + b2) .== 4
    constrain $ a .>= 0
    minimize "goal" $ a
```

This produces a transcript containing `(declare-fun s15 (Int) Int)` to track the goal. It then tries to `(assert (= s0 s15))` but this is an error for Z3 because `s15` is supposed to have a parameter.

I modified the transcript so that `s15` was defined as `(declare-fun s15 () Int)` and then added the usual `(check-sat) (get-model)` commands, and Z3 was perfectly happy with it when I ran it, producing the expected model.

I looked at `addSValOptGoal` but I can't quite pick out from the source code why SBV is adding this unwanted parameter to `s15`.

**Comment by LeventErkok** [comment]
Thanks for the report. This is definitely an issue.

The interaction between quantifiers and optimization is something I neglected so far; clearly not every quantified formula can be optimized (for instance if `a` above itself is universally quantified), and how skolemization interacts with optimization is something I need to sit down and figure out. The above serves as a good example of what should be possible.

In the meantime, if you move the "goal" before the quantifier, your example should run as is. That is make sure the universals come at the very end. (The call to `minimize` itself creates an existential variable.) So, if you write it like this:

```
do
    a <- sInteger "a"
    [b1, b2] <- sIntegers ["b1", "b2"]
    minimize "goal" $ a
    x <- forall "x" :: Symbolic SInteger
    constrain $ 2 * (a * x + b1) .== 2
    constrain $ 4 * (a * x + b2) .== 4
    constrain $ a .>= 0
```

it should work. I need to experiment this a bit to find out exactly when to generate the goal variable in the presence of quantifiers.

**Comment by mrd** [comment]
Thanks. That does work when the goal is a trivial term. Unfortunately if the goal is a compound term then it gets confused again because it binds the intermediate variables inside of the `forall` but tries to assert them outside of the `forall`, e.g. if I minimise `a * 2` then:

```
(assert (forall ((s6 Int))
            (let ((s4 (* s0 s3)))
            (let ((s7 (* s0 s6)))
            (let ((s8 (+ s1 s7)))
            (let ((s9 (* s3 s8)))
            (let ((s10 (= s3 s9)))
            (let ((s12 (+ s2 s7)))
            (let ((s13 (* s11 s12)))
            (let ((s14 (= s11 s13)))
            (let ((s16 (>= s0 s15)))
            (and s10 s14 s16))))))))))))
; [14:26:59.345] Received: success
; [14:26:59.346] Sending:
(assert (= s4 s5))
; [14:26:59.347] Received: (error "line 28 column 11: unknown constant s4")
```

This example will probably have to await a more thorough bugfix based on what you said.

**Comment by LeventErkok** [comment]
Quite right.. I'm not sure how to fix it yet though.. What SMTLib *should* we generate for such a term? It's not clear to me right now how to process queries with arbitrary nesting of quantifiers.

I'd appreciate any ideas you might have!

**Comment by mrd** [comment]
Probably that so long as the goal doesn't involve the universal it should be defined outside of the scope of the `forall`. I'm currently working around the problem by adding yet another `helper` variable and using constraints of the following form:

`(desiredGoal &&& helper .== 0) ||| (not desiredGoal &&& helper .== 1)`

Then `Pareto` optimisation minimising `helper` seems to get the job done. Well, so far, anyway. The important part is that the `helper` variable is an existential defined at the top-level so the generated `assert` and `minimize` statements aren't out of scope.

**Comment by LeventErkok** [comment]
Thanks! Yes, I think we can do a little better here. If nothing, we should be able to recognize and issue a proper error message, instead of sending something bogus to the solver.

**Comment by LeventErkok** [comment]
I'm not sure there's much we can do here, unfortunately. You could've easily asked to minimize `2*x`, for instance; which is simply not translatable. In fact, reviewing the code, I see that I was barely aware of this issue and added code to reject universals when optimization is being done:

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Provers/Prover.hs#L213-L227

But that code is not quite right since it merely checks that the goal variable itself is not universally quantified, which just isn't enough. I intend to make that check stronger, which will reject all these expressions.

Of course, that doesn't address your issue: Clearly optimization is possible in some "quantified" situations, but not in general. Unfortunately SBV currently either generates multiple `assert`s when there are no universals, or just one big giant `assert` if there are any universals present. We need to do better scope management. I'll give it some more thought.

**Comment by LeventErkok** [comment]
@mrd I think I've a solution that will properly recognize such cases and do the "right thing.." Hopefully sometime later today it'll be checked in.

**Comment by LeventErkok** [comment]
@mrd I just put in a bunch of changes that should make optimization with universals work better. There might still be some rough edges though. Can you give it a shot and let me know how it goes?

**Comment by LeventErkok** [comment]
@mrd Just pushed an extra check that was needed; if you already built, please rebuild to make sure all the checks are in place. Thanks!

**Comment by LeventErkok** [comment]
@mrd Is this working as expected now? I'm intending to make a new release pending the closure of this ticket. Thanks.

**Comment by mrd** [comment]
Ah sorry it's a bank holiday weekend here.

Last time I checked `assertSoft` was working again, yes, and I didn't need to use my workaround.

**Comment by LeventErkok** [comment]
OK to close this ticket then?

**Comment by mrd** [comment]
Yes I suppose so. I should note that `assertSoft` only works when used in combination with `optimize` but perhaps that is intended behaviour.

**Comment by LeventErkok** [comment]
That's correct.. `assertSoft`/`minimize`/`maximize` are only valid in an `optimize` call. These follow the semantics as described in http://rise4fun.com/Z3/tutorial/optimization.

**Comment by LeventErkok** [comment]
@mrd sbv 7.2 is now released on Hackage which contains the fix for this issue.
