### ISSUE TITLE
optimization never returns

### ISSUE THREAD

**Issue by dmwit** [LeventErkok/sbv#328]
(Apologies up front if this I've done something stupid. This is my first time trying to get sbv to do optimization.)

In the documentation for optimization, it suggests the following example:

    optimize Lexicographic $ \x y -> minimize "goal" (x+2*(y::SInteger))

When I try this myself, it never returns. The transcript of the verbose version looks like this:

    > optimizeWith z3{verbose=True} Lexicographic $ \x y -> minimize "goal" (x + 2*(y :: SInteger))
    ** Calling: z3 -nw -in -smt2
    [GOOD] ; Automatically generated by SBV. Do not edit.
    [GOOD] (set-option :print-success true)
    [GOOD] (set-option :global-declarations true)
    [GOOD] (set-option :smtlib2_compliant true)
    [GOOD] (set-option :diagnostic-output-channel "stdout")
    [GOOD] (set-option :produce-models true)
    [GOOD] (set-logic ALL) ; has unbounded values, using catch-all.
    [GOOD] ; --- uninterpreted sorts ---
    [GOOD] ; --- literal constants ---
    [GOOD] (define-fun s_2 () Bool false)
    [GOOD] (define-fun s_1 () Bool true)
    [GOOD] (define-fun s2 () Int 2)
    [GOOD] ; --- skolem constants ---
    [GOOD] (declare-fun s0 () Int)
    [GOOD] (declare-fun s1 () Int)
    [GOOD] (declare-fun s5 () Int) ; tracks user variable "goal"
    [GOOD] ; --- constant tables ---
    [GOOD] ; --- skolemized tables ---
    [GOOD] ; --- arrays ---
    [GOOD] ; --- uninterpreted constants ---
    [GOOD] ; --- user given axioms ---
    [GOOD] ; --- formula ---
    [GOOD] (define-fun s3 () Int (* s1 s2))
    [GOOD] (define-fun s4 () Int (+ s0 s3))
    [GOOD] (assert s_1)
    [GOOD] (assert (= s4 s5))

...and there it hangs. z3 appears to be waiting for something more: the process just lies around, not using CPU nor memory. Running it by hand and dumping the commands above has a similar effect: it just sits there waiting, as if I hadn't yet asked a question. Yet I believe the question has at least been asked, since when I hit Ctrl-C, it reports:

    *** Exception: 
    *** Error     : user interrupt
    *** Executable: /usr/bin/z3
    *** Options   : -nw -in -smt2
    *** Request   : (minimize s5)
    ***
    *** Giving up!

    CallStack (from HasCallStack):
      error, called at ./Data/SBV/SMT/SMT.hs:626:68 in sbv-7.1-ClytQNNbBjjIuaWRXHAsKy:Data.SBV.SMT.SMT

In case it matters: z3 version 4.5.0, ghci 8.0.1, sbv 7.1.

**Comment by LeventErkok** [comment]
Yep.. Unfortunately, Z3 4.5.0 is way too old; SBV's optimization routines rely on changes they are yet to officially release.

Can you get a more recent version from here: https://github.com/Z3Prover/bin/tree/master/nightly

That should solve the problem. If not, let me know!

**Comment by LeventErkok** [comment]
Incidentally, Z3 folks are planning to do an official release early October: https://github.com/Z3Prover/z3/issues/1231

**Comment by dmwit** [comment]
Looks like that was the issue, thanks!
