### ISSUE TITLE
A better path for ABC?

### ISSUE THREAD

**Issue by weaversa** [LeventErkok/sbv#338]
Since `z3` has an `aig` tactic, a better path for using `abc` might be to have `z3` do the translation from SMT2 to AIGER and then call `abc` on the resulting formula.

The rationale here is that `abc`'s SMT2 support is incomplete (and occasionally incorrect), and `z3` will is more likely produce a correct AIG.

**Comment by weaversa** [comment]
Turns out `boolector` can also dump AIGER since version 2.1.1. However, as a `cryptol` user, I'm _forced_ to have `z3`, whereas `boolector` is optional.

**Comment by LeventErkok** [comment]
I agree that connection to ABC isn't as good as it can be. But I'm thinking making those changes in sbv is the right way to go. For one thing it's rather fragile: Any changes to those tools can make things go wrong and impossible to debug.

I think a better way to go would be to use the following two environment variables:

-    SBV_ABC                    --> Path to ABC Executable 
-    SBV_ABC_OPTIONS    --> options to pass

The idea is to write a "wrapper" for ABC, and use the above two environment variables to point SBV to the wrapper appropriately.

All the wrapper needs to do is to read an SMT-Lib script from its std-input, and print out results to standard-output. Internally, it can call boolector, z3, write-files, do anything it wants; and eventually calling ABC. This would give you the most flexible way of using ABC with no high-level changes.

I've done this in the past when I was debugging certain interfaces, though in those cases the wrapper was merely for printing out some debugging info, filtering unwanted output from solvers out etc. Nothing as fancy as what you intend to do, but it should just work.

Let me know if you try this and see any issues. I'm sure Cryptol folks (@brianhuffman @acfoltzer) would be interested in helping out too!

**Comment by weaversa** [comment]
After some investigation, SBV_ABC_OPTIONS can be changed to support bypassing ABC's reading of SMT2 by using something like:

```
boolector -dai < test.smt > test.aig && abc -c "&r test.aig; &sweep -C 5000; &syn4; &cec -s -m -C 2000; write_cex \"test.cex\""
```
and then munging the counterexample back into the form that SBV expects. I haven't completed it, but it seems possible.

Obviously this is not seamless across operating systems, so Windows users would have to find another way to do this. The best path forward might be for ABC to integrate Boolector's SMT translation capability.

**Comment by LeventErkok** [comment]
Glad to hear! Direct support in ABC would be nice indeed, perhaps Alan can be persuaded to implement by sharing code from boolector? I believe they both projects are open source these days.

**Comment by LeventErkok** [comment]
@weaversa I'm inclined to close this ticket, given the outlined work-around. Is there anything else SBV can do to make that path easier?

**Comment by weaversa** [comment]
Hi Levent. I don't think so. I'll close. Thanks!
