### ISSUE TITLE
More stable model extraction

### ISSUE THREAD

**Issue by reinerp** [LeventErkok/sbv#340]
As far as I can tell from the examples, to write correct model extraction code from a `SatResult`, I have to ensure that my `parseCWs` function extracts the `CW`s in the same order that my calls to `exists` declared them. If I extract them in the wrong order, it seems like I'll either get a crash (kind mismatch) or junk results.

Can the library provide some assistance to me in getting these correct? For example, some type (or some typeclass) which describes both a sequence of `exists` calls and `parseCWs` calls and ensures by construction that they match?

**Comment by LeventErkok** [comment]
I agree that 'parseCWs' isn't very friendly to use, and the user has to be quite aware of how the variables were declared. That's rather fragile. However, with SBV > 7.0, the use of the query mode provides a much better way to extract values. The function you are looking for is `getValue`, found here: https://github.com/LeventErkok/sbv/blob/5e3f0b6fc0b7d427b918b863463d57258cc3eef3/Data/SBV/Control/Utils.hs#L310

The class `SMTValue` provides all the base types you can use: https://github.com/LeventErkok/sbv/blob/5e3f0b6fc0b7d427b918b863463d57258cc3eef3/Data/SBV/Control/Utils.hs#L265-L307 

Here's an example that might illustrate the technique better: https://hackage.haskell.org/package/sbv-7.4/docs/src/Data.SBV.Examples.Queries.AllSat.html#demo

I'd recommend using the query mode and the model extraction facilities there, as opposed to the old way of doing things via `parseCW`. Let me know if you try that and see any problems!

**Comment by reinerp** [comment]
Looks great, thanks. I hadn't even looked at the Data.SBV.Control module!

Is there a way for the SMT solver to report "this variable is completely unconstrained, i.e. I didn't need to make an assignment to it in order to satisfy the expression"? I'm not seeing this in the SBV type signatures, and I'm not sure if this is even something the SMTLIB API exposes.

**Comment by LeventErkok** [comment]
Unfortunately no. When they present models, SMT solvers will typically provide a full-model for all variables. Even if there might be support for such a feature in individual solvers, it is not exposed by SMTLib in any way. This is actually quite a common question to ask; getting finite/symbolic models. For instance, you might also want to know that `x` can be anything, and `y` is `x+1` and things like that. None of that is supported by SMTLib nor any of the mainline solvers I'm afraid.

**Comment by LeventErkok** [comment]
@reinerp I'm assuming this issue is now resolved? I'm planning to do a release in the next week or so and would like to make sure the concerns are addressed before doing so.

**Comment by reinerp** [comment]
Yes, resolved. Thank you!
