### ISSUE TITLE
String logic API readiness

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#357]
@joelburget

Joel: I've added a few extra functions, which essentially allow for looking at the elements of a string. (As 8-bit values.)

See here: https://github.com/LeventErkok/sbv/commit/6f418dae390b4ba00de100caccd31028eb71a40c

Can you do a review? Feel free to suggest/implement other API that might come in handy, or better names for some of the new functionality. Any feedback is most welcome.

Once this goes thru some testing, I think we can merge to master.

**Comment by joelburget** [comment]
This is really nice. The code looks good to me. I haven't needed any other functionality beyond this.

**Comment by LeventErkok** [comment]
I think some sort of `map` and `filter` would be nice, but I'm not quite sure how to implement it. Perhaps they can be done for a fixed set of functions, though the utility of that is probably not worth the cost. I'll think some more about it.

**Comment by LeventErkok** [comment]
Also of possible interest: Functions that characterize 'characters' (`isUpper`, `isLower`, ... etc.)

**Comment by LeventErkok** [comment]
Lots of new functions added! I think the API is now in good shape.
