### ISSUE TITLE
Expose the `Metric` typeclass

### ISSUE THREAD

**Issue by taktoa** [LeventErkok/sbv#360]
The `Metric` typeclass (in which the `minimize` and `maximize` functions are methods) is not exposed to the end user, which is rather annoying, as it means you cannot add it as a constraint. If the goal is to prevent users from writing new instances, perhaps you could expose a closed type family like this:

```
{-# LANGUAGE KindSignatures, TypeFamilies #-}

module Example (foo, HasFoo) where

import Data.Kind (Constraint)

class Foo a where
  internalFoo :: a

instance Foo Int    where internalFoo = 5
instance Foo Bool   where internalFoo = True
instance Foo Double where internalFoo = 5.0

type family HasFoo (a :: *) :: Constraint where
  HasFoo a = Foo a

foo :: (HasFoo a) => a
foo = internalFoo
```

**Comment by LeventErkok** [comment]
No problem exporting `Metric`, just committed it actually. What exactly is your use case? I'd like to know.

**Comment by taktoa** [comment]
I'm using SBV (Z3) for pseudo-boolean integer programming during the `SelectBest` phase of my [equality saturation implementation](https://github.com/taktoa/eqsat/blob/deda8c75b6e1ef9bbc1d89821f003f9e12892363/library/EqSat.hs#L348-L421) and I'd like my algorithm to be generic over the symbolic numeric domain used by the performance heuristic (`Domain d` is a constraint synonym for `(Num d, SBV.SymWord d, SBV.Metric d)`, and yes I know that that use of `SymWord` does not have any instances; I'm still figuring out exactly what it should be).

**Comment by LeventErkok** [comment]
Nice. Please get in touch if you find other shortcomings/issues in SBV.
