### ISSUE TITLE
Code-generation and integer literals

### ISSUE THREAD

**Issue by peddie** [LeventErkok/sbv#375]
I have the following function:

    f :: SInt8 -> SBool
    f int = (0 :: SInt64) .< (ite (int ./= int) (0 :: SInt64) (-9223372036854775808 :: SInt64) :: SInt64)

(The self-comparison is needed to prevent SBV from simply inlining the result!)

I can prove something about the function for all inputs, specifically that it always returns false, as expected:

    >>> prove $ do { input <- sInt8 "input"; return $ f input .== false }
    Q.E.D.

I asked SBV to emit the corresponding C code

    compileToC (Just "sbv-example") "example" $ do { int <- cgInput "integer"; cgOutput "bool_out" $ f int }

which looked sensible (interesting that SBV can eliminate the self-comparison but not the comparison between two literals):

    void example(const SInt8 integer, SBool *bool_out)
    {
      const SBool s3 = 0x0000000000000000LL < -0x8000000000000000LL;

      *foo = s3;
    }

When I ran the driver function, I was surprised to see

    peddie@jaidee:sbv-example$ make
    cc -Wall -O3 -DNDEBUG -fomit-frame-pointer -c example.c -o example.o
    cc -Wall -O3 -DNDEBUG -fomit-frame-pointer -c example_driver.c -o example_driver.o
    cc -Wall -O3 -DNDEBUG -fomit-frame-pointer example.o example_driver.o -o example_driver
    peddie@jaidee:sbv-example$ ./example_driver
    example(-28, &bool_out) ->
      foo = 1

How can this return `true`, when we proved it's always `false`?

It seems to have something to do with the integer literal `-0x8000000000000000LL` getting implicitly typecast by the C compiler. (`-9223372036854775808` is the most negative value that can be represented as a `long long int`, and also the number with the largest absolute value; `9223372036854775808` is one too many because of 0.) I think the hex representation is interpreted as the counting value, not the bit pattern, of the number, but either way, it ends up too big to represent as a signed `long long int` in spite of its `LL` suffix, so the compiler converts it to unsigned, which means the comparison with `0x0LL` will be an unsigned comparison and return `true`.

I'm not sure what the best way to fix this is.  This could happen even when a literal is compared to a value, so I think if this literal comparison were eliminated during code generation, it would just make the problem less common.  If I explicitly cast every literal, e.g. `(SInt64)(-0x8000000000000000LL)`, it seems to fix the problem in this instance, but I'm not 100% confident this is the way to go.  Maybe just emitting the decimal value would work?

I'm using SBV 7.5, GHC 8.2.2 and Z3 4.6.0.

**Comment by LeventErkok** [comment]
Thanks for the analysis; indeed this is a corner case that needs to be fixed.

Another issue here is that SBV should've actually constant-folded the whole thing away; I need to look at why that's not happening two; so there are two issues here that need addressing.

**Comment by peddie** [comment]
Thanks for the quick reply.  If you can suggest the "right way" to fix the literal output, I can try to make a patch for it.

**Comment by peddie** [comment]
Please have a look at https://github.com/LeventErkok/sbv/pull/377 -- happy to modify it as you see fit; this fixes the original problem for me.  (It's still undergoing CI testing.)

Regarding elimination of two constant literals, I originally had to keep the self-comparison of the argument in my expression to prevent that exact elimination from happening, so at least it can happen at the top level of an expression.  Perhaps it's somehow hidden from further analysis when the code-generation system eliminates the self-comparison.

**Comment by LeventErkok** [comment]
I'm not sure if casting is always 100% guaranteed. But I think we're in luck, because these constants are defined in `stdint.h` header, which we're already including. So, we should use:

```
SInt8 --> INT8_MIN
SInt16 --> INT16_MIN
SInt32 --> INT32_MIN
SInt64 --> INT64_MIN
```

And that should take care of it. Can you do this instead?

**Comment by LeventErkok** [comment]
Also; can you file another ticket as to why the comparison of two literals isn't compiled away? That should automatically happen.

**Comment by peddie** [comment]
I updated the patch to use the `INTX_MIN` approach.  Please have a look.

https://github.com/LeventErkok/sbv/issues/379 is for the optimization issue.

**Comment by peddie** [comment]
Looks good to me.  Thanks for the quick turnaround.  Your solution is nicer anyway.

**Comment by LeventErkok** [comment]
Your patch was most welcome! Thanks for creating it. Much appreciated.

SBV is always open for contributions; if you see anything fishy please report and/or submit a patch!
