### ISSUE TITLE
code generate call to function whose result is a mutable argument

### ISSUE THREAD

**Issue by ghorn** [LeventErkok/sbv#380]
I'm using SBV only for its C code generation, and I wanted to add a call to an external C interpolation function which looks like this:

```
void some_function(const double * input0, const double * input1, double * output);
```

One of the inputs is a static array which I want to hardcode, and the other is a symbolic input. The output is an argument to the function and I'm not sure if `cgUninterpret` can handle this. What I want to write is a function that looks like:

```
wrapSbvInterpolationCall :: [Double] -> [SBV Double] -> [SBV Double]
wrapSbvInterpolationCall dataToHardcode input = ?
```

Is this currently possible with SBV?

**Comment by LeventErkok** [comment]
`cgUninterpret` is pretty flexible, and you can definitely hack it to generate pretty much anything you want.

(Also see `cgAddDecl`, and `cgAddLDFlags`, and `cgAddPrototype` for various hooks into generating code/flags.)

Perhaps something like the following work?

```haskell
import Data.SBV
import Data.SBV.Tools.CodeGen

import Data.List (intercalate)

interpolate :: [Double] -> SDouble -> SDouble
interpolate tbls = cgUninterpret "C_INTERPOLATE" c h
  where h i = literal (sum tbls) / i
        c   = [ "double c_interpolate(double *data, double input) {"
              , "  double sum = 0;"
              , "  int i;"
              , "  for (i = 0; i < 5; ++i) sum += data[i];"
              , "  return sum / input;"
              , "}"
              ]

dataToHardCode :: [Double]
dataToHardCode = [1, 2, 3, 4, 5]

genCCode :: IO ()
genCCode = compileToC (Just "test") "test" $ do
                cgAddDecl [ "SDouble tbl[] = {" ++ intercalate ", " (map show dataToHardCode) ++ "};"
                          , ""
                          , "#define C_INTERPOLATE(i) (c_interpolate(tbl, i))"
                          , ""
                          ]
                x <- cgInput "x"
                cgReturn (interpolate dataToHardCode x)
```

**Comment by LeventErkok** [comment]
There might e a way. Can you give me a concrete example and how you'd like it to work from SBV? Working on a real example always helps.

**Comment by ghorn** [comment]
Since you asked I'll just paste the whole problem so that I don't miss something.

My main constraint is that the type level type signature should be:
`interpolate :: CInterpolantData -> [SBV Double] -> [SBV Double]`

Another constraint is that there is no native implementation for the haskell part of `cgUninterpret`, only a foreign call, so it only works on `Double` not `SDouble`. If this means that I can't evaluate any more, only code generate, then so be it.

```haskell
-- all the data needed to call the foreign interpolation function
data CInterpolantData
  = CInterpolantData
    { ciNDims :: Int
    , ciNOutputs :: Int
    , ciGrid :: SV.Vector CDouble
    , ciOffset :: SV.Vector Int64
    , ciValues :: SV.Vector CDouble
    , ciLookupModes :: SV.Vector Int64
    , ciIW :: SVM.IOVector Int64
    , ciW :: SVM.IOVector CDouble
    }

-- this wraps a foreign import ccall and unsafePerformIO
wrapForeignInterpolation :: CInterpolantData -> [Double] -> [Double]
wrapForeignInterpolation = undefined

-- make a unique string name
hashCInterpolantData :: CInterpolantData -> String
hashCInterpolantData = undefined

interpolate :: CInterpolantData -> [SBV Double] -> [SBV Double]
interpolate dataToHardcode = cgUninterpret funName c h
  where
    -- this wraps a foreign import - there is no way to do it natively
    h :: [SBV Double] -> [SBV Double]
    h i = map literal . wrapForeignInterpolation . map unliteral

    funName = "interpolate_" ++ hashCInterpolantData dataToHardcode

    c :: [String]
    c =
      [ "#include \"my_c_interpolation.h\""
      , ""
      , "double " ++ funName ++ "(const double * const input, double * output) {"
      , "  // hardcoded inputs"
      , "  const int64_t ndim          = " ++ show      (ciNDims       dataToHardcode) ++ ";"
      , "  const double  grid[]        = " ++ showArray (ciGrid        dataToHardcode) ++ ";"
      , "  const int64_t offset[]      = " ++ showArray (ciOffset      dataToHardcode) ++ ";"
      , "  const double  values[]      = " ++ showArray (ciValues      dataToHardcode) ++ ";"
      , "  const int64_t lookup_mode[] = " ++ showArray (ciLookupModes dataToHardcode) ++ ";"
      , "  const int64_t noutputs      = " ++ show      (ciNOutputs    dataToHardcode) ++ ";"
      , ""
      , "  // mutable work arrays"
      , "  int64_t iw[" ++ show (SVM.length (ciIW dataToHardcode)) ++ "];"
      , "  double   w[" ++ show (SVM.length (ciW dataToHardcode)) ++ "];"
      , ""
      , "  // call my function"
      , "  my_interpolation(input, ndim, grid, offset, values, input, lookup_mode, noutputs, iw, w);"
      , "}"
      ]
      where
        showArray x = "{" ++ intercalate ", " (map show (SV.toList x)) ++ "}"

doCg :: CInterpolantData -> SBVCodeGen ()
doCg cinterpolantData = do
  inputs <- cgInputArr 2 "in"
  let y :: [SBV Double]
      y = interpolate cinterpolantData inputs
  cgOutputArr "out" y

main :: IO ()
main = do
  cinterpolantData <- newCInterpolant "linear" [[0,1,2],[0,10]] [1,2,3,4,5,6]
                      :: IO CInterpolantData
  compileToC (Just "test") "test" (doCg cinterpolantData)
```

**Comment by LeventErkok** [comment]
Thanks! This helps.

Would it be possible for you to create a standalone example that I can load/run? (I understand it may not generate correct C for the time being.)

That would allow me to experiment and see if we can do this somehow.

**Comment by ghorn** [comment]
Here you go: https://gist.github.com/ghorn/724f24b48dc8b9dd6105fe3bdd9b732a

It fails with
```
StandaloneExample.hs:43:30: error:
    • No instance for (Uninterpreted ([SBV Double] -> [SBV Double]))
        arising from a use of ‘cgUninterpret’
```

**Comment by LeventErkok** [comment]
Thanks! Let me think about this a bit and see if we can somehow support it.

**Comment by LeventErkok** [comment]
Am I interpreting this correctly:

```
    ciNDims = 2  --> Number of inputs that the external C function expects
  , ciNOutputs =3 --> Number of outputs that will be produced by the C function
````

**Comment by ghorn** [comment]
yes

**Comment by LeventErkok** [comment]
There's really no official way to do this, since SBV's uninterpreted functions are designed to match functions of SMTLib, and to a large extent these return precisely one value. ("Void" returns, or multiple return values are possible with the fancier data-type declarations these days, but SBV doesn't support those for a variety of reasons.) In particular, there is no notion of a "function" that takes a "reference" parameter; so SBV's `Uninterpreted` class don't even bother supporting any such value, let alone lists of arguments of arbitrary lengths.

Having said that, I think one can still "hack" to generate the required code, since you *do* know the number of inputs and number of outputs.  It'll probably look super ugly too, but perhaps you don't care since it's merely generated code. I'll give it a shot to see if I can concoct something, for the sake of curiosity if nothing else.

**Comment by LeventErkok** [comment]
@ghorn Any feedback on this? I'm intending to make a release soon; possibly over the weekend, and would like to make sure this is taken care of.

**Comment by LeventErkok** [comment]
@ghorn I'm about to make a release of SBV. Is there any action item we have on this ticket? I'm happy to leave it open, but would be nice to get any changes in this release if you've any requests.

**Comment by LeventErkok** [comment]
@ghorn I'm preparing for a new release. Since I haven't heard anything back from you, I'm assuming this issue is no longer present. Feel free to reopen if there's anything we can do on the SBV side to support your use case.

**Comment by ghorn** [comment]
Do you think it's possible to use the idea I wrote above to return multiple elements by value in a struct? Re-pasting:

> I was wondering since it is possible for smtlib to return arrays, how to do something analogous in C. One option would be to have structs containing arrays and return these instead:
> 
> typedef struct {
>  double values[4];
> } Double4Struct;
> 
> Then you could just cast those things to arrays and dereference the individual elements directly? You might have to code generate a lot of extra structs though.

**Comment by LeventErkok** [comment]
@ghorn 

Not directly from SBV. But you can have your own wrappers:

This code:

```haskell
main :: IO ()
main = compileToC (Just "test") "test" $ do
           x <- cgInput "x"
           cgOutputArr "res" $ [x, (x+1), (x+2), (x+3::SDouble)]
```

Generates:

```C
#include "test.h"

void test(const SDouble x, SDouble *res)
{
  const SDouble s0 = x;
  const SDouble s2 = s0 + 1.0;
  const SDouble s4 = s0 + 2.0;
  const SDouble s6 = s0 + 3.0;

  res[0] = s0;
  res[1] = s2;
  res[2] = s4;
  res[3] = s6;
}
```

Now you can imagine using `cgAddDecls` to call `test` and get the results and wrap it in your `Double4Struct` etc.

This is clumsy and obviously not well integrated with the rest of the system; but it can be used to generate code that can be called from other C infrastructure.

Any other way of doing this would require introducing `struct` types to SBV for code generation purposes, and that sounds like a can of worms to me due to allocation/freeing and all that issues.
