### ISSUE TITLE
typo in documentation: hexPuzzle

### ISSUE THREAD

**Issue by pjljvandelaar** [LeventErkok/sbv#386]
On line 62 of https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/Puzzles/HexPuzzle.hs numners should be numbers.

```
62 -- | Use 8-bit words for button numners, even though we only have 1 to 19. 
```

**Comment by LeventErkok** [comment]
@pjljvandelaar Thanks! If you tell me your full name, I can add you to the "THANKS" list.

**Comment by pjljvandelaar** [comment]
I am Pierre van de Laar and already on your thanks list...

**Comment by LeventErkok** [comment]
Well, thanks again than!
