### ISSUE TITLE
Generated `Makefile` does not contain `-lm` when needed

### ISSUE THREAD

**Issue by peddie** [LeventErkok/sbv#389]
If I code-generate functions which contain operations like `fpAbs` (which corresponds to `fmax()`/`fmaxf()` in C) or `sqrt`, the generated `Makefile` can't build the driver functions out of the box; it fails because `-lm` is needed in the link command.

I looked at making a patch to do this nicely, but this requires a new information flow that I'm not sure how to handle (`Data.SBV.Compilers.C.genMake` needs to know whether any such functions are involved in any of the functions it's building).  I can still do it if you can provide some guidance regarding how this should work.  The other option is to just always append `-lm` to the generated link command, and it will be superfluous in some cases.

**Comment by LeventErkok** [comment]
Good point. Actually, this is precisely why we have the `cgAddLDFlags` function:

https://github.com/LeventErkok/sbv/blob/a5f76e90983230cc6acc7c3eedc31d1ed16208a9/Data/SBV/Compilers/CodeGen.hs#L198-L200

I'm not sure if the ROI is there to extract this info and supply it automatically. It can surely be done, but sometimes just giving the user a hook is the cheapest/right thing to do. (For instance, different compilers/OSs; Windows/OSX/Linux etc.; which might have slightly different flags.)

Do you think we still need something automatic? Or do you think `cgAddLDFlags` is sufficient?

**Comment by peddie** [comment]
If you think it's not worth it, it's no big deal.  I currently use `cgAddLDFlags` but thought I'd mention that it doesn't just work automatically in all cases.  What do you think of https://github.com/LeventErkok/sbv/pull/390 ?

**Comment by LeventErkok** [comment]
@peddie Here's the relevant code. Did I miss any?

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Compilers/C.hs#L967-L987

**Comment by peddie** [comment]
That covers everything I'm aware of.  Nice one!

**Comment by LeventErkok** [comment]
Great. Closing this one then.
