### ISSUE TITLE
Using Symbolic and Query in a monad transformer stack

### ISSUE THREAD

**Issue by bts** [LeventErkok/sbv#391]
Hi Levent,

I noticed that #329 describes a situation similar to what @joelburget and I have encountered trying to use `Symbolic` and `Query` in the presence of `ExceptT`, to handle something "going wrong" while building up an analysis. I figure that we could share the best approach we've found so far, and that this could potentially provide some helpful feedback to the development of sbv, or perhaps you have a tip that could help us improve our approach.

For a while we used an approach similar to @bch29's [use of exceptions](https://github.com/LeventErkok/sbv/issues/329#issuecomment-326247068):

> I've worked around it for now by throwing the error from ExceptT into Symbolic's underlying IO then catching it when I run the transformer stack. This feels ugly but it works fine for now. It would be helpful if Symbolic became a monad transformer so I could put ExceptT inside it and avoid the issue that way.

except that we used an `MVar` that we'd write to within `Symbolic` when we encountered a failure.

We've since moved to an adaptation of sbv's internal [`runWithQuery`](https://github.com/LeventErkok/sbv/blob/dc5e36c7dfcd3ae7e40503d3bb172968948d7b1c/Data/SBV/Provers/Prover.hs#L499-L503) that works over a monad transformer containing `Symbolic` as the base monad. With this [new function](https://github.com/kadena-io/pact/blob/ec71d54995d1ad10bb3227c67f56a0ba43e14249/src/Pact/Analyze/Check.hs#L216-L240), we encapsulate a pattern that has at least been useful in our application -- separating our use of sbv into three phases:

1. Doing some initial "allocation" in `Symbolic` to produce an "environment"
2. Performing an analysis (using the environment) that results in a `Provable`
3. Querying (also with access to the environment) to build a more useful model to report back to clients.

At least as it's implemented here, we allow something to "go wrong" in any of the three stages.

Also note that instead of using `Provable a`, we simplified the function to just assume `Symbolic (SBV a)` because that's all that we needed in our codebase. Accordingly we removed `runWithQuery`'s dispatch to `forSome_` vs `forAll_` because those are both just `id` in the `Symbolic (SBV a)` case. Lastly, also specific to our implementation, we happen to use a datatype `data Goal = Validation | Satisfaction` that you can ignore:

```haskell
runAndQuery
  :: forall env r t.
   ( MonadTrans t
   , MFunctor t
   , Monad (t Symbolic)
   )
  => Goal                           -- ^ are we using sat or valid?
  -> t Symbolic env                 -- ^ initial setup in Symbolic
  -> (env -> t Symbolic (SBV Bool)) -- ^ produces the Provable to be run
  -> (env -> t SBV.Query r)         -- ^ produces the Query to be run
  -> t IO r
runAndQuery goal mkEnv mkProvable mkQuery = hoist runSymbolic comp
  where
    cfg :: SBV.SMTConfig
    cfg = SBV.z3

    runSymbolic :: Symbolic a -> IO a
    runSymbolic s = fst <$>
      SBVI.runSymbolic (SBVI.SMTMode SBVI.ISetup (goal == Satisfaction) cfg) s

    comp :: t Symbolic r
    comp = do
      env <- mkEnv
      void $ lift . SBVI.output =<< mkProvable env
      hoist SBV.query $ mkQuery env
```

As an example, you might imagine the `t` in this code concretized to something like `ExceptT AppFailure`.

I don't know how hard it would be, but have you considered adding something like a `MonadSymbolic m` and a `SymbolicT` to sbv? I suppose that functions like the methods in `SymWord` might then produce these abstract, rather than concrete, symbolic computations.

Anyhow, hopefully this is helpful in some way.

Thanks again for sbv!
Brian

**Comment by LeventErkok** [comment]
I suppose we can start with something like:

```haskell
newtype SymbolicT m a = Symbolic (ReaderT State m a)

type Symbolic a  = SymbolicT IO a
```

And see where it takes us. I suspect we would need a `class Symbolic` to make this all work, but it's hard to predict how smooth the transition would be without trying it.

I'd encourage you to create a branch and see where it takes you. I'd be happy to merge it back to master if it ends up being more-or-less backwards compatible. (By that, I mean existing code should either work unmodified, or the modifications required should be more or less syntactic.)

Without doing such an experiement and seeing how it looks, I hesitate to comment on how it might turn out. But I'll keep an eye on it if I ever get a chance to refactor the code base.

**Comment by bts** [comment]
OK great. I will try to play with this; hopefully soon. Thanks!

**Comment by LeventErkok** [comment]
@bts Did you get a chance to try this out?

**Comment by bts** [comment]
@LeventErkok I have not yet tried this out, but the code I'm working on would definitely improve if we had `SymbolicT` -- I will try to revisit this soon.

**Comment by LeventErkok** [comment]
All good to go on this!
