### ISSUE TITLE
Metric instances for wide bit vectors

### ISSUE THREAD

**Issue by danr** [LeventErkok/sbv#399]
Hi,

I'm defining instances for `Int256` and `Word256` but I'm stuck at defining the `Metric` instances. The provided instances are defined in `Data.SBV.Core.Model` using `addSValOptGoal`, but this function is not exported. Is there a way to access this or a similar function using the API?

Thanks!

**Comment by danr** [comment]
For the record, this is how I'm defining the `Int256` instance:

```haskell
import Data.SBV as SBV
import qualified Data.SBV.Internals as SBV
import Data.SBV.Dynamic (SVal)
import Data.SBV.Tools.Overflow

import Data.DoubleWord

instance SymWord Int256 where
  mkSymWord = SBV.genMkSymVar (KBounded True 256)
  literal = SBV.genLiteral (KBounded True 256)
  fromCW = SBV.genFromCW

instance HasKind Int256 where
  kindOf _ = KBounded True 256

instance SDivisible (SBV Int256) where
  sQuotRem = SBV.liftQRem
  sDivMod = SBV.liftDMod

instance SFiniteBits Int256 where sFiniteBitSize _ = 256

instance ArithOverflow SymI where
  bvAddO = l2 bvAddO
  bvSubO = l2 bvSubO
  bvMulO = l2 bvMulO
  bvMulOFast = l2 bvMulOFast
  bvDivO = l2 bvDivO
  bvNegO = l1 bvNegO
```

**Comment by LeventErkok** [comment]
Just exported it from `Data.SBV.Internals`. Let me know if that doesn't suffice.

**Comment by danr** [comment]
Thanks, that does the trick :v:

**Comment by LeventErkok** [comment]
Wonderful. Let me know if you see any other issues.
