### ISSUE TITLE
Start using new boolector

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#403]
There's a new github release of boolector; start using that!

**Comment by danr** [comment]
Do you communicate with boolector using their api or using SMTLIB? 

I see that they have functions for overflow checking but it differs a bit from how z3 does it: there is not separation between underflow and overflow, it's just one bit: http://fmv.jku.at/boolector/doc/cboolector_index.html#c.boolector_smulo

**Comment by LeventErkok** [comment]
Unfortunately SBV connection to Boolector is now broken for v3.0.0 of boolector, due to: https://github.com/Boolector/boolector/issues/8

**Comment by LeventErkok** [comment]
Thanks to quick-fix from Boolector folks, SBV now works with their latest version!

@danr If you have other ideas to try regarding the overflow checking, please follow up separately with a different ticket. I'm always interested in doing such experiments as they point out issues on both SBV and solvers themselves, which is always a good thing.
