### ISSUE TITLE
Use safe-exceptions for exception handling

### ISSUE THREAD

**Issue by ocharles** [LeventErkok/sbv#410]
Currently, it seems that you are just using `Control.Exception` with `catch` and `SomeException`. This means that asynchronous exceptions get slurped up by calls to `runSMT`, rather than propagating correctly. For example:

```
                *** Error     : KillSwitchEngaged
                *** Executable: /nix/store/84q71lm7h512zm86pmzq7my70m12bfmf-z3-4.7.1/bin/z3
                *** Options   : -nw -in -smt2
                *** Request   : (check-sat)
                ***
                *** Giving up!
                
                CallStack (from HasCallStack):
                  error, called at ./Data/SBV/SMT/SMT.hs:629:68 in sbv-7.8-GBHYUUNXFOsHghUpALGscq:Data.SBV.SMT.SMT (
                *** Error     : KillSwitchEngaged
                *** Executable: /nix/store/84q71lm7h512zm86pmzq7my70m12bfmf-z3-4.7.1/bin/z3
                *** Options   : -nw -in -smt2
                *** Request   : (check-sat)
                ***
                *** Giving up!
                
                CallStack (from HasCallStack):
                  error, called at ./Data/SBV/SMT/SMT.hs:629:68 in sbv-7.8-GBHYUUNXFOsHghUpALGscq:Data.SBV.SMT.SMT)
```

`KillSwitchEngaged` is being thrown to a thread running `runSMT` as an asynchronous exception (to cancel the thread), but `sbv` has slurped up my asynchronous exception and turned it into a synchronous `error` call.

**Comment by LeventErkok** [comment]
Instead of calling `error`, I can simply print this and throw the exception back up. Would that work for you?

**Comment by ocharles** [comment]
Not quite. The point is anything that is an async exception should only be seen by your library, and never caught. Notice how in http://hackage.haskell.org/package/safe-exceptions-0.1.7.0/docs/Control-Exception-Safe.html#g:2 - none of the "catch" functions will catch asynchronous exceptions - this is the right way to do things. For cleanup it's fine to *see* an asynchronous exception (e.g., [`with-exception`](http://hackage.haskell.org/package/safe-exceptions-0.1.7.0/docs/Control-Exception-Safe.html#v:withException)) as the exception doesn't get lost.

I think your best option really is to just drop in `safe-exceptions` which makes the right decisions. If you don't want to incur that dependency: anywhere you `catch` `SomeException`, you should test that `SomeException` to see if it's an asynchronous exception (by casting to `SomeAsyncException`, see reference [here](http://hackage.haskell.org/package/safe-exceptions-0.1.7.0/docs/src/Control-Exception-Safe.html#isAsyncException)), and if it is just rethrow it (as done [here](http://hackage.haskell.org/package/safe-exceptions-0.1.7.0/docs/src/Control-Exception-Safe.html#catch]).

**Comment by LeventErkok** [comment]
@ocharles Give it a try now. If it's still not working as expected, patches are most welcome.

**Comment by ocharles** [comment]
That looks much, better - thanks! I probably can't try this until Monday, but I'll report back then.

**Comment by LeventErkok** [comment]
Great. Looking forward to hearing what you find out.

**Comment by ocharles** [comment]
This works perfectly now, thanks!

**Comment by LeventErkok** [comment]
Excellent! Please keep reporting these corner cases; very useful. Thanks.
