### ISSUE TITLE
Do we want bounded recursion?

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#425]
@joelburget 

Curious what you think about this; not directly related to sequences/strings, but one can imagine a combinator of this form can be useful in certain contexts:

```haskell
{-# LANGUAGE FlexibleContexts #-}

import Data.SBV

bfix :: (SymWord a, Uninterpreted (SBV a -> r)) => Int -> String -> ((SBV a -> r) -> (SBV a -> r)) -> SBV a -> r
bfix bound name f x
  | isConcrete x = g x
  | True         = unroll bound x
  where g        = f g
        unroll 0 = uninterpret name
        unroll i = f (unroll (i-1))
```

For instance, given this combinator we can define:

```haskell
fac :: SInteger -> SInteger
fac = bfix 10 "fac" fact
 where fact f n = ite (n .== 0) 1 (n * f (n-1))
```

Then we can prove things like:

```haskell
*Main> prove $ \n -> n .>= 1 &&& n .<= 9 ==> fac n .== n * fac (n-1)
Q.E.D.
```

Or similarly, find bugs within the unroll count of 10 (or any other bound we might choose).

This can be used in coordination with sequences; a more general form of `bfoldr` and `bfoldl`.

I hate to add extra functionality that have no actual practical use cases; but if this sounds like something useful we can add it. Of course, users can define this for themselves; nothing here actually requires any internal SBV coding, but that's besides the point.

**Comment by joelburget** [comment]
I think I feel similarly -- this looks useful but I don't currently have a use-case where I need it. Maybe @bts has one?

This seems quite related to the [recursive function theory](https://github.com/Z3Prover/z3/commit/c7d0d4e191f214cf60f0b75d3d64351d9a537b43) which is in z3 4.8.3 (as of a few days ago), though I'm not sure if it provides benefits over your approach.

> a more general form of `bfoldr` and `bfoldl`

This argument is convincing to me. I'm somewhat in favor adding `bfix` on aesthetic grounds.

**Comment by LeventErkok** [comment]
@joelburget @bts 

No harm in adding indeed; though it'd be great if it came with a good example. I'll keep this ticket here till we have something reasonable. All ideas are welcome!

**Comment by LeventErkok** [comment]
@joelburget Just had a look at the z3 link you provided for the new handling of recursive functions; indeed it is precisely the same idea. I've first heard of this trick back in early 2000's, where people used the abstraction of the recursive call to memoize recursive functions by changing the "fixed-point" operator. It's interesting to see the idea re-occuring in the SMT domain now. As usual, good ideas get re-discovered over and over in multiple domains. Cool.

It would be really nice if SBV was actually able to spit out function definitions directly; but that's a whole another can-of-worms, and would require major surgery on the code base and usage models. But as SMT solvers do start supporting recursive functions more robustly, that sort of a shift seems inevitable. The same applies to abstract-data-types as well.

**Comment by LeventErkok** [comment]
Note that if we let go of the "concrete runs complete" requirement, we can define this more simply:

```haskell
bfix :: Uninterpreted a => Int -> String -> (a -> a) -> a
bfix bound name f = unroll bound
  where unroll 0 = uninterpret name
        unroll i = f (unroll (i-1))
```

Perhaps this version is better. Or maybe we should have both. It's hard to judge when there aren't any compelling use cases.
