### ISSUE TITLE
Why are many examples gone in 7.12?

### ISSUE THREAD

**Issue by buggymcbugfix** [LeventErkok/sbv#426]
There were a bunch of examples up to version 7.11 that suddenly disappeared in version 7.12, but the changelog doesn't mention this. I found these examples extremely useful. Why are there much fewer examples now?

**Comment by LeventErkok** [comment]
They're still all there. If you go to hackage page: https://hackage.haskell.org/package/sbv

They're all listed in the `Documentation.SBV.Examples` hierarchy now; perhaps that's the confusion?
