### ISSUE TITLE
SBV runtime crash

### ISSUE THREAD

**Issue by buggymcbugfix** [LeventErkok/sbv#427]
The following causes SBV to crash:

```haskell
data IntX = IntX (Maybe Integer) deriving (Eq, Ord, Data, Read, Show, SymWord, HasKind)

instance Num IntX where
  (+) (IntX x) (IntX y) = IntX $ (+) <$> x <*> y
  (*) (IntX x) (IntX y) = IntX $ (*) <$> x <*> y
  fromInteger = IntX . Just

ex1 = sat $ do
  x :: SBV IntX <- free "x"
  return $ x .== x + 1

main :: IO ()
main = print =<< ex1
```

```
sbv.hs: SBV.SMT.SMTLib2.cvtExp.sh: impossible happened; can't translate: s0 + s1
CallStack (from HasCallStack):

  error, called at ./Data/SBV/SMT/SMTLib2.hs:681:13 in sbv-7.12-9AiNAYtrUhB8YA6mr6BTn4:Data.SBV.SMT.SMTLib2
```

(I'm trying to encode extended integers/naturals in SBV, but I'm probably doing it wrong—see related StackOverflow question [here](https://stackoverflow.com/questions/53444430/encoding-extended-naturals-in-sbv).)

**Comment by LeventErkok** [comment]
SBV is essentially telling you that it doesn't know how to turn your `IntX` to a symbolic value. The derived instance of `SymWord` is not sufficient here since they're only intended for uninterpreted types. Unfortunately, there isn't a good way to detect that at compile time.

I'll answer your stack-overflow question shortly to describe how this can be done in detail.

**Comment by LeventErkok** [comment]
Yes! Error messages can always be improved. Now we get:

```
*** Exception:
*** Cannot translate operator        : +
*** When applied to arguments of kind: IntX
*** Found as part of the expression  : s0 + s1
***
*** Note that uninterpreted kinds only support equality.
*** If you believe this is in error, please report!
```

That can still be confusing, but at least a bit more informative.

Note that the moment you said:

```
data IntX = IntX (Maybe Integer) deriving (Eq, Ord, Data, Read, Show, SymWord, HasKind)
```

SBV decided to translate `IntX` as an uninterpreted kind. (Unfortunately the class hierarchy isn't smart enough to later tell you you can't do arithmetic on these types. Perhaps a better design can handle that.)
