### ISSUE TITLE
Support for Sets

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#443]
z3 has builtin support for set operations, `complement`, `subset` etc.; which makes it possible to do efficient (?) set operations that is impossible to do with good old sequences or functions. (Sequences can't do efficient membership, nor things like complement. Functions can't do things like subset while remaining a pure API as it would require higher order term etc.)

Would be nice to figure out the details of z3 support and add them directly to SBV.

**Comment by LeventErkok** [comment]
Here're the operations to support, and their translations:

```
## Declaration
(declare-fun a () (Array Int Bool))
(assert (= a a))


### Empty set
((as const (Array Int Bool)) false)

### Full set
((as const (Array Int Bool)) true)

### Addition
(store a 1 true)

### Deletion
(store a 1 false)

### Membership
(select a 1)

### Intersect
(intersect a a)

### Union
((as union (Array Int Bool)) a a)

### Subset
(subset a a)

### Difference
(difference a a)

### Complement
(complement a)
```

Note that arrays are used as the backbone here, with some extra operations baked-in. This will be interesting as it isn't clear how to deal with counter-example values here. We might have to implement some extra array-value parsing.

**Comment by LeventErkok** [comment]
@bts @joelburget 

Hi Joel, Brian: The set API is now good to go. If you've any comments before I put this in a release (anything missing or not quite correctly done), I'd love to hear it. See the two files:

   [Data.SBV.Set](https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Set.hs)
    [Documentation.SBV.Examples.Misc.SetAlgebra](https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/Misc/SetAlgebra.hs)

**Comment by joelburget** [comment]
Hi Levent, I played with the set API a bit. I didn't find anything missing or incorrect. I was pleasantly surprised how much you're able to prove (in the `SetAlgebra` module). Looks great -- thanks for adding this!

**Comment by LeventErkok** [comment]
Great! I want to add a few more tests to the test-suite; but otherwise I'll call the API finalized then.

**Comment by LeventErkok** [comment]
Done!
