### ISSUE TITLE
Sum types (previously "using generics in `HasKind` and `SymVal`?")

### ISSUE THREAD

**Issue by joelburget** [LeventErkok/sbv#447]
Hi Levent,

I've been working on an experiment adding sum types to sbv. My motivation for sums is to try doing program synthesis in sbv. I think @bts also has a use-case he needs sums for.

The [initial prototype](https://github.com/LeventErkok/sbv/compare/master...joelburget:sum-types) just has support for the sum of two types, ie `Either`. I stopped there basically because that's the only sum type Haskell has built in (contrast with all the built-in tuple types we currently support). It would be possible, but a bit awkward to define more sbv-specific sum types, like:

```haskell
data Sum3 a b c
  = In1 a
  | In2 b
  | In3 c
```

But I'd rather not bake this type in to sbv.

It occurred to me that using GHC generics, we could support user-defined types in a generic way. So I put together this [gist showing my approach](https://gist.github.com/joelburget/aa5d08affa6bda1f05bd73bc505b8542). All the generics wrangling is for this payoff:

```haskell
data Sum3 a b c
  = In1 a
  | In2 b
  | In3 c
  deriving (Generic, HasKind', SymVal')
```

Some notes:

1. The default implementations for `kindOf`, `mkSymVal`, `literal`, and `fromCV` use GHC generics. I prefer this over the use of `Data.Data`, `Show`, and `Read`, though it's a breaking change and not without tradeoffs.

1. This gist doesn't yet handle symbolic constructors and eliminators (which will be tricky).

1. This code in the gist will probably do something bad when handling the `List` type defined at the bottom. There are two possible fixes:
   1. Figure out how to disallow recursive uses of the data type being defined. Note: `Generic` / `type Rep` don't distinguish between these two uses of `K1` ("Constants, additional parameters and recursion of kind *") in the same way that `Generic1` / `type Rep1` distinguish between `Par1` ("Used for marking occurrences of the parameter") and `Rec1` ("Recursive calls of kind * -> *"). I'm confused about why this is.
   1. (I'd like to do this eventually) Just support recursive data types. In this case we'd have to bound the solver.

So, this is kind of a nebulous issue to gauge your interest in a few paths forward:

1. Support for just `Either` a la my initial prototype.

1. Separately, we could use GHC Generics for default instances where `Data.Data`, `Show`, and `Read` are used today. I'm not sure this seems worth it on its own.

1. Work on the more ambitious approach to supporting data types in general via `Generic`.

I'd love your thoughts on which, if any, of these paths seem worthwhile.

**Comment by joelburget** [comment]
Levent,

Thanks for the helpful feedback. I agree with you about generics. The types involved are complicated enough that generics would be very hard to get right.

It would still be very helpful for us to be able to lift `Either` into `SBV`, which is actually the only sum type my branch currently supports (I'm distinguishing between my [branch of sbv](https://github.com/joelburget/sbv/tree/sum-types) and the gist I also posted). It includes a [`case_`](https://github.com/joelburget/sbv/blob/546cdae5ab7be46595e50a175b55ec05c7110a22/Data/SBV/Sum.hs#L84-L91) like you mentioned. Yesterday my hope was that we could be more ambitious with generics, but we would actually be able to do everything we need via just `Either`.

The motivation is similar to our motivation for adding tuples -- I'd like to be able to model functions `f :: [Either a b] -> c`. Like you said, `Either a b` could be modeled as `(Bool, a, b)`, but it would be simpler for us to model directly. Plus it just seems right to have coproducts given that we have products.

**Comment by LeventErkok** [comment]
Great! I think this keeps things simple.

You should call `case_`  simply `either`. Maybe the type itself should be called `SEither` to indicate that it's not some arbitrary coproduct.

Another nice thing to have it is something that corresponds to the `Maybe` type; but perhaps that can be easily modeled by `SEither a ()`? Or do you think it warrants a separate type of its own? It'd be bad to have too many things, but I'd say option is perhaps even more important than the sum type, purely from a practical perspective.

**Comment by joelburget** [comment]
I just opened a PR with symbolic `Either` and `Maybe`. I decided to treat `Maybe` separately, since we want `SBV (Maybe a)` to make sense and I'd rather not defined an sbv-only `type Maybe a = Either () a`.

**Comment by LeventErkok** [comment]
Looks great!

Is the `Maybe` kind checked in? I didn't see it in the diffs.

I do want to make a few changes; mostly cosmetic. I think you have all the push-rights now. Can you push it to a branch on github? I'll then work on that and merge to master.

**Comment by meditans** [comment]
I'm glad this issue has just been made, because I've been mumbling on how to add support for some class of datatypes via generic (feel free to move this comment elsewhere if it does not fit here!):

basically what I would like is integrating in sbv, via generics, every datatype which is transitively composed of simple types (like Int, Strings etc - I've done similar work on this kind of datatypes in [unification-sop](https://github.com/meditans/unification-sop)). This issue taught me that the problem is the treatment of sum types, but I'd like some more comment on this quote:

> To me, it feels like without a good story on deconstructing, it's really painful to use. To really properly do this, we would really need something that corresponds to a case statement. One that can bind variables. Unfortunately, this is impossible to do in Haskell; and the best option is to resort to either TH or some other pre-processor;

Could you do a practical example on the problems that emerge and how @joelburget solved them in the `Either` case?

Regarding recursive types,

> Then there's the whole saga of recursive types of course; which is best avoided in my opinion given the state of the art in SMT solvers.

Are these problem avoided enough if one could put a limit on the height of the terms?

Regarding:
> Another idea can be to map sum-types to tuples, with a valid bit for each component; and maintain the invariant that precisely one of those valid-bits is true at all times. I've some experience with this encoding in a different system and it actually works relatively well.

How would this type be encoded?
```haskell
data Foo  = FooI Int | FooR String Foo
```

I'd really like to try my hand to add some generic support (or joining existing efforts), and as a first step I'd like to understand better the nuances of the problem.

Thanks!

**Comment by joelburget** [comment]
> Could you do a practical example on the problems that emerge and how @joelburget solved them in the `Either` case?

I solved them in the `Either` case by writing the constructors and eliminator by hand.

```haskell
-- | Construct an @SBV (Either a b)@ from an @SBV a@
left :: forall a b. (SymVal a, SymVal b) => SBV a -> SBV (Either a b)

-- | Construct an @SBV (Either a b)@ from an @SBV b@
right :: forall a b. (SymVal a, SymVal b) => SBV b -> SBV (Either a b)

-- | Case analysis for symbolic 'Either's. If the value 'isLeft', apply the
-- first function; if it 'isRight', apply the second function.
either
  :: forall a b c.
     (SymVal a, SymVal b, SymVal c)
  => SBV (Either a b)
  -> (SBV a -> SBV c)
  -> (SBV b -> SBV c)
  -> SBV c
```

Compare with the same functions for `Maybe`:

```haskell
-- | Construct an @SBV (Maybe a)@ from an @SBV a@
just :: forall a. SymVal a => SBV a -> SBV (Maybe a)

-- | Construct an @SBV (Maybe a)@ holding 'Nothing'
nothing :: SymVal a => SBV (Maybe a)
nothing = literal Nothing

-- | Case analysis for symbolic 'Maybe's. If the value 'isNothing', return the
-- default value; if it 'isJust', apply the function.
maybe
  :: forall a b.
     (SymVal a, SymVal b)
  => SBV b
  -> (SBV a -> SBV b)
  -> SBV (Maybe a)
  -> SBV b
```

These are mechanically derivable, but it's not easy with GHC generics (I'm not sure why Levent said it's impossible -- maybe he can elaborate).

> How would this type be encoded?

We can encode most of `Foo`, but we don't currently have a way to encode the recursive part.

```haskell
type SFoo = SBV (Bool {- validity bit -}, Integer, (String, ???))
```

**Comment by joelburget** [comment]
@LeventErkok There is no explicit `Maybe` kind -- I used `KSum` for both `SEither` and `SMaybe`.

I pushed to the `sum-types` branch, but I think I have one more commit to push with some cleanups.

**Comment by LeventErkok** [comment]
@joelburget I see.. Cool. Yes, please keep pushing to `sum-types` and rebase to master and send me a note when you think it's good to go. I should have time over the weekend to merge it back in. Much appreciated!

I think we can close this pull request now. Right?

**Comment by meditans** [comment]
@joelburget thanks for the explanation, in fact writing the eliminator is a bit of a hassle, but as you said it's possible with some TH. Now I understand @LeventErkok 's comment about another package similar to the lens generators.

Regarding a way to encode the recursive part, what's wrong with the following approach? (I'm using `generic-sop` as it's more clear to read in a gist).

```haskell
import           Generics.SOP
import           Data.SBV

data Term a
  = Con (SBV a)             -- ^ A value for the `base` types
  | Rec (SOP Term (Code a)) -- ^ The constructor, and recursive subterms
```

Then a `Term Foo` could contain the payoff you indicated in your answer, including the `validity bit`, which is encoded in the number of the constructor used in the SOP. What do you think?

@LeventErkok feel free to close the issue as far as I'm concerned, would another issue be good to continue to explore the design space?

**Comment by meditans** [comment]
What should be the link, if there is one, between the phantom parameter in `SBV` and the `SVal` inside? Why couldn't we just say `SBV Foo`, @joelburget?

**Comment by LeventErkok** [comment]
Hi Carlo,

Thanks for joining the effort and chiming in.

Joel answered your questions mostly, but let me add a few thoughts. It comes to the fact that we can *not* write the following, currently:

```haskell
f :: SInteger -> SIntger
f 0 = 5
f 1 = 7
f x = x+1
```

Nor we can write the following"

```haskell
f :: SInteger -> SInteger
f x = case x of
         0 -> 5
         1 -> 7
         x -> x+1
```

We cannot even write the following, unless we're willing to resort to `RebindableSyntax`:

```haskell
f :: SInteger -> SInteger
f x = if x .== 0 then 5 else if x .== 1 then 7 else x+1
```

(And I'm really going to object to any uses of `RebindableSyntax`; but that's a different story.)

This is all OK when the types are numbers etc., which can just use chain of `ite` calls. Ugly, but it does work.

When you introduce arbitrary `Sum` types, however, this all breaks down. You end up defining equivalents of Haskell's `maybe` or `either` functions; or in general try to functionalize it. You completely lose pattern matching. And there is no way in Haskell to "overload" case expressions. (Wouldn't be that desirable anyhow.)

That's what I meant when I said "impossible."

For recursive types: It's just a losing story. Doing anything with a recursive type requires recursive functions that are almost always not symbolically terminating; and thus you end up creating bounded versions. (What you referred to as "maximum depth.") It sure works, but it completely misses the point of having a recursive type in the first place. Even with Joel's list abstraction (which I love by the way!), you can't even define simple functions like `map`, `filter`, `fold` etc. or do anything interesting. (Try writing the `reverse` function, for instance, for an `SList` type. It's impossible to do so.) Even if you could, it's extremely unlikely the SMT solver will be able to do anything interesting with that, as reasoning would require quantified axioms.

Until the day comes where SBV produces actual `define-fun`, `define-fun-rec` constructs SMTLib, I think it's best to avoid additional complexity by going the Generics route as the payoff is just not there. And for SBV to generate `define-fun`, `define-fun-rec` or `match` constructs, it'd need a heart and liver transplant all at the same time. A complete redesign, almost.

But that shouldn't discourage you from experimenting. Please fork off the repo, see what you can add, and how things go. Show us some example proofs and we'll see how it goes. Joel definitely surprised me with his tuples and lists (which are limited in expressive power but quite intriguing nonetheless), and I'd love to be pleasantly surprised again.

**Comment by joelburget** [comment]
@LeventErkok branch `sum-types` looks good now

**Comment by LeventErkok** [comment]
@joelburget 

This is now merged. I ended up making a bunch of changes though. The big one is, I opted for separate kinds for `KEither` and `KMaybe`; allowing us to generate two distinct SMTLib types and keep them separate. I think this is more intuitive.

I also added a few other API functions, and reworked the internals to support Z3 and CVC4. (Though haven't tested CVC4 all that well; most everything seems to work with z3.)

Do give it a shot and see if it works for your cases; and please let me know if there's anything fishy. I'm working on a few other features, but I expect 8.1 to go out soon enough once you give this a green light and close this ticket!

**Comment by joelburget** [comment]
Thanks for the improvements, Levent. Especially CVC4 support. Everything looks good to me.
