### ISSUE TITLE
Automatically uniquify user names

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#458]
@joelburget 

SBV should simply make user names unique instead of rejecting duplicates; there are good use cases for using "prefix" like naming convention and nothing internally really relies on uniqueness of these names (except in model extraction; which is really ok.) So, instead of rejecting, we should uniquify automatically.

Joel: I already pushed the commit for this; give it a try and let me know if it works as expected.

**Comment by LeventErkok** [comment]
@joelburget Did you get a chance to try this? I'd like to make sure this one works as expected before 8.1 is out.

**Comment by joelburget** [comment]
I didn't get the chance to try it yet but I'll let you know hopefully tomorrow.

**Comment by joelburget** [comment]
Just tried this out and it works great!

**Comment by LeventErkok** [comment]
Cool! 8.1 will ship within a week.
