### ISSUE TITLE
We need conversion safety predicates!

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#462]
@peddie 

Currently, the `IEEEFloatConvertible` class performs conversions from/to floats and doubles and other types. But the way it's constructed, it is subject to the following restrictions:

    1. If the input is `NaN`, `+oo`, or `-oo`, then the result is undefined.
    2. If we convert the input to an integral value in the same type (in the sense of `fpRoundToIntegral` and that value doesn't fit into the target type, then the result is undefined.

And when we say 'undefined', we really mean it: There are absolutely no guarantees that what Haskell does, what SMTLib does, and what the C-translation produces agree in any way.

This is OK from a design perspective as it keeps things simple. (See #456 for a plethora of issues!).

But we should also provide predicates to catch these cases. The first case is easy, we already have `fpIsNan`, `fpIsInfinite`, `fpIsPositive`, `fpIsNegative` so user can catch those cases and spit out whatever they want. But for the second case of rounding and then falling out-of-bounds, we have no predicates whatsoever. Note that these predicates will have to consider what the rounding-mode is, as the range will change based on that.

NB. Even if we had these predicates, I'd submit that the undefined behavior should be kept. Trying to be clever here and mapping these values to something predetermined just complicates matters.

So, we should figure out what these bounds are, and provide the following four predicates:

```
    sFloatUnderflows  :: IEEEConvertible a => RoundingMode -> SFloat  -> SBool
    sFloatOverflows   :: IEEEConvertible a => RoundingMode -> SFloat  -> SBool
    sDoubleUnderflows :: IEEEConvertible a => RoundingMode -> SDouble -> SBool
    sFDoubleOverflows :: IEEEConvertible a => RoundingMode -> SDouble -> SBool
```

Note that these can be added outside of SBV; and @peddie if you end up defining these please ping me to see if we can add them to SBV proper; or at least make it available to people via an additional Hackage package. We'll cross that bridge when we come to it.

**Comment by LeventErkok** [comment]
Some notes.

It's really tricky to get these bounds. Here's an example where even Boost gets it wrong: https://svn.boost.org/trac10/ticket/12252

Since this ticket is 3 years old, I'm not sure if we can actually validate the bounds that we can get from z3 somehow. Frustrating!

**Comment by LeventErkok** [comment]
Our bound finder is producing unexpected values. Here's the simplified example:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV

findBounds = do x <- sFloat "x"
                y <- sInt32 "y"

                constrain $ sFromIntegral y .== fpRoundToIntegral sRNE x

                maximize "x-max" x
                maximize "y-max" y

m = optimizeWith z3{printBase=16} Lexicographic findBounds
```

This prints:

```
Optimal model:
  x     = 2.1474836e9 :: Float
                  3  2          1         0
                  1 09876543 21098765432109876543210
                  S ---E8--- ----------F23----------
          Binary: 0 10011110 00000000000000000000000
             Hex: 4F00 0000
       Precision: SP
            Sign: Positive
        Exponent: 31 (Stored: 158, Bias: 127)
       Hex-float: +0x1p31
           Value: +2.1474836e9 (NORMAL)
  y     =  0x7fffffff :: Int32
  x-max =  0xcf000000 :: Word32
  y-max =  0xffffffff :: Word32
```

which suggests `0x1p31` is safe to convert in `RNE` to `Int32`. But it just isn't:

```
*Main> satWith z3  $ \x y -> (x .== (0x1p31::SFloat)) .&& ((y :: SInt32) .== fromSFloat  sRNE x)
Satisfiable. Model:
  s0 = 2.1474836e9 :: Float
  s1 =           0 :: Int32
```

Clearly z3 hit undefined behavior here and got as a 0. Indeed, this is what MathSAT says:

```
*Main> satWith mathSAT   $ \x y -> (x .== (0x1p31::SFloat)) .&& ((y :: SInt32) .== fromSFloat  sRNE x)
Satisfiable. Model:
  s0 = 2.1474836e9 :: Float
  s1 = -2147483648 :: Int32
```

Looks like MathSAT is being a bit more "realistic" perhaps, but still indicates we're not getting the correct bound.

Matt's analysis from MPFR showed that the actual bound is: `0x1.fffffep+30`. Let's try that:

```
*Main> satWith z3   $ \x y -> (x .== (0x1.fffffep+30::SFloat)) .&& ((y :: SInt32) .== fromSFloat  sRNE x)
Satisfiable. Model:
  s0 = 2.1474835e9 :: Float
  s1 =  2147483520 :: Int32
```

(And MathSAT agrees with z3 on this one.) This makes a lot more sense, because this is really the largest `Int32` we can hit coming from an `SFloat`.

But I just can't get z3 to produce the constant `0x1.fffffep+30` no matter what I tried. Not sure if it's a bug in z3, or we're hitting some sort of an undefined behavior. Mystery!

**Comment by LeventErkok** [comment]
@peddie 

Hi Matt.. See my notes above regarding how we should proceed with this. I'm stumped as to why z3 isn't producing the correct value: clearly we're hitting some undefined behavior but I can't pinpoint where it's coming from. Your guesses are most welcome!

Regarding the constant `0x1.fffffep+30` you found from MPFR: How did you determine that? I googled a bit but didn't hit anything that explicitly mentions this value. Perhaps we should somehow get MPFR to spit out these values and call it a day?

**Comment by peddie** [comment]
I tried adding a round-trip constraint to the optimization problem, but it didn't help.  The goal was to ensure that whatever integer we produce by rounding maps to the same floating-point value if we call `sFromIntegral`.  I listed an example on the old ticket where Z3 can both optimize a number and prove that the result doesn't satisfy the optimization problem.  Maybe trying to replicate that program in plain SMTLIB could shed some light on the issue.  I vaguely wonder whether there is something like in Haskell going on, where rounding to integer goes via a larger precision format first and then gets a (defined) modulo applied to it.

[Here is the up-to-date version of my MPFR program (in C)](https://gist.github.com/peddie/6309d1b12711acef0206f7fdf6afe931).  Note that it's using an MPFR which I modified to add `fits_uchar_p()` and `fits_schar_p()`.  These functions are generated by the same macro that generates `fits_ushort_p()` and `fits_sshort_p()`, so I didn't have to do any hard work to get them.

MPFR's implementation of `RoundNearestTiesToAway` (`MPFR_RNDNA`) is still experimental (not exported publicly), and it doesn't seem to give the answers I'd expect, so **I'm not sure how to get the constants for this mode yet**.  They also provide a bonus mode `RoundAwayFromZero` (`MPFR_RNDA`) which doesn't correspond to anything in the IEEE standard.  I printed it out anyway as it should agree with `RoundTowardPositive` and `RoundTowardNegative` in the appropriate cases, so I found it useful to double-check by inspection.

Other, ill-formed ideas for how to attack these constants if the current approaches don't work out:
 - Do a manual binary search with non-z3 solvers and compare optimization results
 - Use several solvers and see whether they agree about how to round the MPFR constants and whether they disagree about how to round the `nextafter()` value
 - Find another arbitrary-precision float library which supports `RoundNearestTiesToAway` (and can double-check MPFR)
 - Hand-write predictions for the missing constants for mode `MPFR_RNDNA` and see whether the undefined behavior sanitizer complains as expected
 - Learn enough Coq to use [Flocq](http://flocq.gforge.inria.fr)

**Comment by LeventErkok** [comment]
Cool ideas! Coq would be really nice if we can get it to spit out the bounds.

I've been looking at the z3 source code to see if I can get some inspiration and found this gem:

https://github.com/Z3Prover/z3/blob/master/src/ast/fpa/fpa2bv_converter.cpp#L3290-L3308

Obviously, they're doing some serious computation there, looking at both pre-rounding and signedness to decide if things fit. Unfortunately, I can't quite tell how they're doing it exactly, but it's obvious a lot of work went into that piece of code.

I'll keep digging with some reduced capacity, and hopefully, we'll have our verified predicates one way or the other in the interim. Please keep me posted with your progress.

**Comment by peddie** [comment]
I'm out of time to work on this today, but here's my summary.

### Coq

Flocq does not deal with rounding to integers.  CompCert has an extension that does, but it only uses round-toward-zero mode.  CompCert's license is not free in general, but it is free for research and education, and the file in question has a GPLv2 header, so this might still be an option (albeit labor-intensive -- do you know any Coq?).

### Another arbitrary-precision library

Surveyed CLN, libbf, arbitraire, arb.  None has built-in functionality analogous to `mpfr_fits*()`.

### Plain C

I wrote [yet another search program (sorry)](https://gist.github.com/peddie/be312db949d12a8914a6a638ceef2d40), this one using only plain C99.  I did this because I couldn't remember why I had rejected it last week.  

Many of the resulting constants (but not all) agree with MPFR.  In fact, many (all?) of the ones that disagree actually agree with my original blast-based Z3 search program's output.  This makes me wonder whether the Z3 team are using the same algorithm to determine whether it can be rounded: look at the floating-point value corresponding to the extreme value for the type and compare any candidate float to this to determine whether it can be rounded.  For example, **independent of rounding mode**, `UINT32_MAX` is `4294967295`; when cast to a float, it becomes `0x1p+32` (`4294967296.0`).  So if you have `0x1p+32`, it's no bigger than the float representation of `UINT32_MAX`.  But `0x1p+32` shouldn't round back to `UINT32_MAX`; it's bigger than `UINT32_MAX` by 1 (whether or not we round with `rintf()`; it's the same answer)!  I think this issue is the main remaining source of disagreement between methods.

My system C library and man pages don't have anything corresponding to `RoundNearestTiesToAway` either.
