### ISSUE TITLE
Diophantine equation example

### ISSUE THREAD

**Issue by dixonary** [LeventErkok/sbv#463]
There seem to be a couple of small things with the diophantine equation example which could be improved upon:

1. The commentary for `basis` states:

`...if it's least according to the lexicographic order using the ordinary less-than relation.`

This is incorrect - it would imply that [2,1] > [1,2] when in fact they are incomparable. We use the natural (componentwise) ordering that a <= b iff a_i <= b_i everywhere.

2. Line 60 of the basis function reads:

```return $ ok as .&& (ok bs .=> as .== bs .|| sNot (bs `less` as))```

and later

``` as `less` bs = sAnd (zipWith (.<=) as bs) .&& sOr (zipWith (.<) as bs)```

These could both be simplified to only using less-than-equal, since it's effectively ruling out the equal case in `less` and then introducing it again.

Please correct me if I'm wrong on either of these? Otherwise I'm happy to submit a PR with the amended version.

**Comment by dixonary** [comment]
( for the avoidance of doubt, it's this example: https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/Existentials/Diophantine.hs )

**Comment by LeventErkok** [comment]
I'll have to look at this in detail to remember the details, but PR's are always welcome. Please submit one.

**Comment by LeventErkok** [comment]
PR merged
