### ISSUE TITLE
Division of minimum signed integer by negative one causes SIGFPE in generated C code

### ISSUE THREAD

**Issue by peddie** [LeventErkok/sbv#468]
SBV's generated C code already protects against divide (or mod)-by-zero:

    const SInt32  s601 = (s599 == 0) ? INT32_MIN : (INT32_MIN % s599);

But if `s599` is `-1` here, this can also cause a fatal exception.  This is because the negation of `INT32_MIN` cannot be represented in an `int32_t`; it is `INT32_MAX + 1`.

GHC's solution is to define `minBound / -1` to be `minBound` again (and `mod minBound (-1)` to be 0).  This matches the behavior of `gcc` and `clang` when the `-fwrapv` switch is enabled (the result is technically undefined behavior in C).

Perhaps the generated code should read more like the ungainly

    const SInt32 s601 = (s599 == -1) ? 0 : ((s599 == 0) ? INT32_MIN : (INT32_MIN % s599));

and require a further check on the dividend if it's not a constant.  The predicates can be pulled out into preceding graph nodes, but the actual operation cannot be for obvious reasons.

**Comment by LeventErkok** [comment]
Seems like GHC is throwing an error as well:

```haskell
Prelude Data.Int> (minBound :: Int8) `div` (-1)
*** Exception: arithmetic overflow
```

This seems to be one of those cases where it's just "undefined"; except SMTLib seems to set it to `-1`.

We can still fix the C code generator of course; just not sure how much ROI there is when something is so ill-defined. What do you think?

**Comment by peddie** [comment]
I misspoke -- division does indeed give an overflow exception.  But not modulus:
```
Prelude> (minBound :: Int) `mod` (-1)                
0
Prelude Data.Int> (minBound :: Int8) `mod` (-1)
0
```
This one seems defined enough to make the generated code match.  But I agree about division; there seems to be no hope there.

**Comment by LeventErkok** [comment]
Ah I see. So, is SBV generating the correct code for `mod`? What goes wrong?

**Comment by peddie** [comment]
Sorry; my title is inaccurate.  The original example was about `mod`, and it gives me a `SIGFPE` when compiled with clang on debian x86_64.

**Comment by LeventErkok** [comment]
Hmm; I'm confused:

```haskell
Prelude Data.SBV.Tools.CodeGen Data.SBV> compileToC (Just "test") "foo" $ do { cgSetDriverValues [-128]; x <- cgInput "x"; cgReturn (x `sMod` (-1::SInt8))}
Creating directory "test"..
Generating: "test/Makefile"..
Generating: "test/foo.h"..
Generating: "test/foo_driver.c"..
Generating: "test/foo.c"..
Done.
```

And:

```
~/test>make
cc -Wall -O3 -DNDEBUG -fomit-frame-pointer -c foo.c -o foo.o
cc -Wall -O3 -DNDEBUG -fomit-frame-pointer -c foo_driver.c -o foo_driver.o
cc -Wall -O3 -DNDEBUG -fomit-frame-pointer foo.o foo_driver.o -o foo_driver
~/test>./foo_driver
foo(-128) = 0
```

How can I replicate your result? (I'm on MacOSX, But I don't think that should matter.)

**Comment by peddie** [comment]
It seems I jumped to the conclusion that this was just due to the behavior of `%`.  My original failure was in the middle of a large body of generated code; the line I pasted was reported by gdb after SIGFPE was thrown, and the instruction reported is `idiv %ecx`.  `s599` (in `%ecx`) in that example was `-1`.

Stranger still, this block of code was compiled with `-fwrapv`, which should avoid problems.

I'll continue trying to understand how this exception was generated, but it seems like this bug report is inaccurate and can be closed if you like.  I apologize for not providing a minimal reproducible example straight out of the gate.

**Comment by LeventErkok** [comment]
No worries. Do report again if you find out what's going on here. I wouldn't be surprised if SBV generated less than kosher code with respect to all these overflows and undefined behaviors.

Closing this ticket; but feel free to open a new one as you make progress.
