### ISSUE TITLE
CVC4 can be build with floating point support

### ISSUE THREAD

**Issue by mgudemann** [LeventErkok/sbv#469]
Newer versions of CVC4 can be build with support for `symfpu` which adds floating point support. I think it would make sense to add something like a `cvc4fp` `SMTConfig` with `supportsIEEE754` capabilities.

**Comment by LeventErkok** [comment]
Thanks, fixed.

Note that you *can* change the capabilities on the fly. If you need to use a hackage release or can't build from github sources for some reason, you can work-around this as follows:

```haskell
import Data.SBV
import Data.SBV.Internals

cvc4FP :: SMTConfig
cvc4FP = cvc4 {solver = (solver cvc4) {capabilities = (capabilities (solver cvc4)) { supportsIEEE754 = True }}}
```

Then:

```haskell
*Main> satWith cvc4FP $ \x -> x ./= (x::SFloat)
Satisfiable. Model:
  s0 = NaN :: Float
```

**Comment by mgudemann** [comment]
@LeventErkok great, thanks!

> Note that you can change the capabilities on the fly.

sure, but I wasn't sure whether people using `sbv` were aware of that capability!

best wishes

**Comment by LeventErkok** [comment]
You're right; this isn't a well-advertised capability. But seriously; hopefully it isn't needed very often.
