### ISSUE TITLE
"Unsupported interactive/query mode feature" error

### ISSUE THREAD

**Issue by arrowd** [LeventErkok/sbv#472]
In my application I had something like

loop = do
  ...
  runSMT $ do
    x <- exists_
    query $ do ...

I pushed `runSMT` out of the loop and reorganized code a bit hoping it would make solver preserve knowledge and speed up solving my problem. However, this lead to following SBV error:

```
CallStack (from HasCallStack):
  error, called at ./Data/SBV/Core/Symbolic.hs:810:20 in sbv-7.13-7fbM68Edjzd98OPvnfLJx:Data.SBV.Core.Symbolic
CallStack (from -prof):
  Data.SBV.Core.Symbolic.noInteractive (Data/SBV/Core/Symbolic.hs:(810,1)-(813,96))
  Data.SBV.Core.Symbolic.modifyState (Data/SBV/Core/Symbolic.hs:(820,1)-(825,39))
  Data.SBV.Core.Symbolic.internalConstraint (Data/SBV/Core/Symbolic.hs:(1235,1)-(1241,28))
  Data.SBV.Core.Symbolic.imposeConstraint (Data/SBV/Core/Symbolic.hs:(1226,1)-(1231,98))
  Data.SBV.Core.Model.constrain (Data/SBV/Core/Model.hs:1812:4-82)
  Main.шагДифф.sbvSik (Main.hs:(158,5)-(216,41))
  Main.шагДифф.sikVarM (Main.hs:(219,5)-(225,48))
  Main.шагДифф (Main.hs:(149,1)-(256,15))
  Main.расчет.\ (Main.hs:97:75-98)
  Utils.iterateForM (Utils.hs:(15,1)-(18,40))
  Data.SBV.Core.Symbolic.runSymbolic (Data/SBV/Core/Symbolic.hs:(1120,1)-(1188,18))
  Data.SBV.Provers.Prover.runSMTWith (Data/SBV/Provers/Prover.hs:506:1-66)
  Data.SBV.Provers.Prover.runSMT (Data/SBV/Provers/Prover.hs:502:1-33)
```

Is it a bug in SBV, or it isn't allowed to interleave actions in `query` mode and then create new variables with `exists`?

**Comment by LeventErkok** [comment]
Can you post an example that I can actually load? This should work just fine.

As a general guideline, you should use `freshVar`: http://hackage.haskell.org/package/sbv-8.3/docs/Data-SBV-Control.html#v:freshVar to create new variables in the query mode.

**Comment by LeventErkok** [comment]
Is this still an issue?

Here's an example usage:

https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/Puzzles/HexPuzzle.hs#L89-L122

As you can see `runSMT` is outside, and inside the loop you call `freshVar` to allocate new variables as needed.

Hope it helps. If you still have issues, please send a snippet of code that I can actually load and see the error message myself.

**Comment by arrowd** [comment]
Here is a minified test case I came up with:

```
test = do
    newSik <- exists_ :: Symbolic SReal
    constrain $ newSik .>= 0

    query $ do
        constrain $ newSik .<= 100

        checkSat

    newSik <- exists_ :: Symbolic SReal
    constrain $ newSik .>= 0

    query $ do
        constrain $ newSik .<= 100

        checkSat

    return ()
```

I'm using `sbv-7.13`, BTW.

**Comment by LeventErkok** [comment]
The issue here is that `runSMT` and `query` should be in 1-1 correspondence. Note how you have two calls to `query`. You should think of each `query` call as a *live* connection to the backend solver. Once you're out of its scope, the solver dies. In general, once you're in the query mode, you should stay in there. (Unfortunately, this isn't enforced by the type system: There are ways to do so, but it's not cheap.)

So, you should code your example like this:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV
import Data.SBV.Control

test = runSMT $ do
    newSik <- exists_ :: Symbolic SReal
    constrain $ newSik .>= 0

    query $ do
        constrain $ newSik .<= 100

        io . print =<< checkSat

        newSik :: SReal <- freshVar_
        constrain $ newSik .>= 0
        constrain $ newSik .<= 100

        io . print =<< checkSat
```

which prints:

```
*Main> test
Sat
Sat
```

Note the use of `freshVar_` once you're in the query mode.

Hope this helps! Feel free to ask further questions if you run into issues.

**Comment by arrowd** [comment]
Thanks for explanation!
