### ISSUE TITLE
Minimum integers, C compilers and SIGFPE

### ISSUE THREAD

**Issue by peddie** [LeventErkok/sbv#474]
This is the return of #468, now with minimal reproducible example.  I apologize for the delay, but I had to build some additional infrastructure to be able to automatically reduce failing test cases that died due to signals like `SIGFPE`.  I believe I've finally got to the bottom of this mystery.

    > let g input = (minBound :: SInt32) `sMod` input
    > sat $ free_ >>= constrain . (.==) (g (-1))
    Satisfiable. Model:
      s0 = 0 :: Int32
    > (minBound :: Int32) `mod` (-1)
    0
    > compileToC (Just "test") "test_g" $ do { cgSetDriverValues [-1]; input :: SFloat <- cgInput "input";  cgReturn $ g input }

This produces the following code:
```
SInt32 test_g(const SInt32 input)
{
  const SInt32 s0 = input;
  const SBool  s2 = s0 == 0x00000000L;
  const SInt32 s4 = (s0 == 0) ? INT32_MIN : (INT32_MIN % s0);
  const SInt32 s5 = s2 ? INT32_MIN : s4;
  const SBool  s6 = s5 > 0x00000000L;
  const SBool  s8 = s5 < 0x00000000L;
  const SInt32 s10 = s8 ? -0x00000001L : s5;
  const SInt32 s11 = s6 ? 0x00000001L : s10;
  const SBool  s12 = s0 > 0x00000000L;
  const SBool  s13 = s0 < 0x00000000L;
  const SInt32 s14 = s13 ? -0x00000001L : s0;
  const SInt32 s15 = s12 ? 0x00000001L : s14;
  const SInt32 s16 = (- s15);
  const SBool  s17 = s11 == s16;
  const SInt32 s18 = s0 + s5;
  const SInt32 s19 = s17 ? s18 : s5;
  const SInt32 s20 = s2 ? INT32_MIN : s19;

  return s20;
}
```
Now when I run it:
```
peddie@jaidee:test$ make
cc -Wall -O3 -DNDEBUG -fomit-frame-pointer -c test_g.c -o test_g.o
cc -Wall -O3 -DNDEBUG -fomit-frame-pointer -c test_g_driver.c -o test_g_driver.o
cc -Wall -O3 -DNDEBUG -fomit-frame-pointer test_g.o test_g_driver.o -o test_g_driver
peddie@jaidee:test$ ./test_g_driver 
Floating point exception
```

The interesting thing here is the contrast with your example from the previous ticket, where the input was the numerator and the `-1` was known at compile time; that code did not lead to an exception.  In this case, where the `-1` is not known, `SIGFPE` occurs.  I tried playing with `-fwrapv`, `-fno-builtin` and changing whether the function source and the input value appear in the same file.  None of these parameters has any effect with either gcc 8.3.0 or clang 7.0.1-8.

It seems that [this behavior has been reported before](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=30484), and it's not SBV's fault but GCC's (and clang's for being bug-compatible).  

I would like to work around this behavior in my application, but it's difficult to do so at the moment, because if I guard against the exception with `ite`, testing the denominator, this bogus instruction will still get called before my guard comes into play in the SSA-form code that SBV emits.  Can you suggest a better way to ensure SBV generates code that never runs such an unsafe `%` operation, or does the fact that this behavior is baked into the two main compilers and can't be worked around with compiler flags provide enough motivation for SBV's code generation to provide this safety guarantee itself?

For what it's worth, `sDiv` can also produce this exception, I think because it's implemented via `quotRem`.

**Comment by LeventErkok** [comment]
Indeed, it is really not easy to work around this. There's an "implicit" assumption that either all functions are total, OR we already know all the partiality/exceptional cases and do the "right" thing in SBV. Obviously, this case is neither. We can change the code generator to catch this case explicitly and spit out the right code; though that is really costly as it would incur a performance penalty for every single division for this one case.

I think your best bet is to use the `cgUninterpreted` function, like this:

```Haskell
import Data.SBV
import Data.SBV.Tools.CodeGen

protectedMod :: SInt32 -> SInt32 -> SInt32
protectedMod = cgUninterpret "PROTECTED_MOD" cCode hCode
  where hCode = sMod
        cCode = ["#define PROTECTED_MOD(x, y) ((((x) == INT32_MIN) && ((y) == (-1))) ? 0 : ((x) % y))"]

g :: SInt32 -> SInt32
g input = minBound `protectedMod` input

toC = compileToC (Just "test") "test_g" $ do
        cgSetDriverValues [-1]
        input <- cgInput "input"
        cgReturn $ g input
```

Obviously, you can replace `cCode` with whatever you want; including full-blown function definitions, performing other tricks as you wish, or call some other third party library function.

I'm not a big proponent of `cgUninterpret` as you're essentially telling SBV "trust me," but in this particular case its use seems justified. And you can selectively apply it when you are most concerned.

Would this help?

**Comment by peddie** [comment]
> I think your best bet is to use the cgUninterpreted function

That's what I was afraid of.  OK, if this is the best way to attack it, I'll continue down the macro route.  In view of SBV's focus on defined semantics, might these irritating corner cases deserve a note in the documentation, alongside the explanation of the closure using zero?

**Comment by LeventErkok** [comment]
Sure; feel free to submit a pull request! More documentation is always welcome.

**Comment by LeventErkok** [comment]
@peddie I'm planning to make a release sometime later this week. Would be great to have this documented in the code somewhere if you can write a few sentences or so. (Either send a PR or just send me the relevant text and I'll add it to the code.)

**Comment by peddie** [comment]
@LeventErkok I appreciate the reminder.  Please see https://github.com/LeventErkok/sbv/pull/476 for some documentation changes, or feel free to close that and reinterpret the text as you see fit.  Thanks as always for your responsiveness.

**Comment by LeventErkok** [comment]
Looks great! Thanks.
