### ISSUE TITLE
Troubleshooting sbv

### ISSUE THREAD

**Issue by KeesBleijenberg** [LeventErkok/sbv#492]
I installed z3 (version 4.1) on my windows 7 computer. 
I add the the directory where z3.exe is in, to the path environment variable. 
I add package sbv to package.yaml. 
The main program:
import Documentation.SBV.Examples.Puzzles.Sudoku

main :: IO ()
main = sudoku puzzle1

It compiles without errors.
When I run the program I get:
Solving the puzzle ...

And the program hangs or is busy. But no solution in a fraction of a second.
What is wrong and how can I troubleshoot this kind of problems. 
How can I see what is sent to z3?

Kees

**Comment by LeventErkok** [comment]
Try the following program:

```haskell
import Data.SBV
import Documentation.SBV.Examples.Puzzles.Sudoku

main :: IO ()
main = test puzzle1

test :: Puzzle -> IO ()
test p@(i, f) = do putStrLn "Solving the puzzle.."
                   model <- getModelAssignment `fmap` satWith z3{verbose=True} ((valid . f) `fmap` mkExistVars i)
                   case model of
                     Right sln -> dispSolution p sln
                     Left m    -> putStrLn $ "Unsolvable puzzle: " ++ m
```

It should show you exactly what it's sending to z3 and receiving back. What do you see?

**Comment by LeventErkok** [comment]
Also, probably upgrade your `z3` something more recent. `4.1` is quite old.

**Comment by KeesBleijenberg** [comment]
I run your program and get:
Solving the puzzle..                                   
** Calling: z3 -nw -in -smt2                           
[GOOD] ; Automatically generated by SBV. Do not edit.  
[GOOD] (set-option :print-success true)                
[FAIL] (set-option :global-declarations true) 

I will upgrade z3.
Kees

**Comment by KeesBleijenberg** [comment]
I've upgraded to z3 version 4.8.6 and everything works fine.

**Comment by LeventErkok** [comment]
Great! Feel free to reach out if you’ve any other issues.
