### ISSUE TITLE
More dynamically solving sudoku's

### ISSUE THREAD

**Issue by KeesBleijenberg** [LeventErkok/sbv#493]
I'am new to SBV. This is not a 'issue' but more a question. I don't know a good place to pose these questions. 
My first question is: Where can I post SBV questions? 
I've looked at the example code for solving sudoku's. All the examples know up front how many symbolic variables it needs. So, if I have another sudoku, I have to alter the source and recompile. What can I do if I read sudoku's from a file? 
I encountered another problem with calcudoku's. A calcudoku can contain a area where the sum of the cells in the area needs to be say 12. For checking whether a sum area is valid, I need something like sum [SWord8] .== 12. This does not compile. Is this a limitation of sbv (or Z3)?

Kees

**Comment by LeventErkok** [comment]
You can post questions here, or on stack-overflow; using the sbv tag: https://stackoverflow.com/questions/tagged/sbv

You can easily allocate as many variables as you want by calling `sWordN` functions; something like:

```
  mkVars n = do syms <- mapM sWord8_ [1..n]
                             ... use syms ...
```

and you can determine `n` by "parsing" the input file etc.; using regular Haskell idioms.

`sum` over words should work just fine:

```haskell
Prelude Data.SBV> sat $ \x y z -> sum [x, y, z] .== (12 :: SWord8)
Satisfiable. Model:
  s0 =  0 :: Word8
  s1 =  0 :: Word8
  s2 = 12 :: Word8
```

If you post a minimal code segment that illustrates the issue you have, I can help out.

**Comment by LeventErkok** [comment]
@KeesBleijenberg I think this one is resolved. Feel free to open new issues if you see them, or post questions on stack-overflow as needed.
