### ISSUE TITLE
enable custom instances of `SolverContext`

### ISSUE THREAD

**Issue by mpdairy** [LeventErkok/sbv#499]
I have a monad that wraps `SolverT` in a `ReaderT` and `StateT`. I tried to create an instance of `SolverContext` for my monad and I did so for every function of `SolverContext` by lifting the `SolverT` into my monad. But I can't write one for `contextState`, which is kept in a hidden package. Is that hidden for a reason?

**Comment by LeventErkok** [comment]
Not really. We can export it from `Data.SBV.Internals`. Feel free to send a patch!

**Comment by mpdairy** [comment]
Oh, actually it is already exported from `Data.SBV.Internals`, I was trying ti import it from some other module where just `contextState` was hidden. I don't recall which module that was and can't seem to find it now.

**Comment by LeventErkok** [comment]
Ah quite right. It exports everything in `Data.SBV.Core.Data` which includes `contextState`.

There might be other stuff that's not exported though. If you find that's the case, feel free to modify `Data.SBV.Internals` and send a pull request.
