### ISSUE TITLE
Converting from Dynamic SVals to SWords to use bitvector operations

### ISSUE THREAD

**Issue by mpdairy** [LeventErkok/sbv#501]
I have to use the `Dynamic` module to create SVals of bitvectors at runtime (using the `Bounded` kind). I was hoping I could promote these SVals to SWords and then use the bitvector operations on them.  I seem to be able to use `SomeNat`and the width of the `Bounded` kind to get the `Nat` type I need to specify the `SWord`, but then I can't satisfy some of the other constraints in your bitvector functions. For example, `IsNonZero` seems to be defined internally and I don't know how I'd "prove" my type isn't a Zero nat. The same goes for the more complex constraints, like `((i + m) - n) <= 0` in `bvDrop`, though I think those are externally defined in GHC.TypeNats so I could eventually figure out how to prove those.

Is there some way to do this? Here's the function I was fiddling with, trying to make a version of bvDrop that took an Int and an SVal:

```
trydrop :: Int -> SVal -> SVal
trydrop n bv =
  case SBV.kindOf bv of
    KBounded signed width ->
      case someNatVal (fromIntegral width) of
        Nothing -> P.error "sorry"
        (Just (SomeNat (_ :: Proxy m))) ->
          unSBV $ SBV.bvTake (Proxy :: Proxy m) (SBV bv :: SWord m)
    _ -> P.error "oh well"
```

For now I'm ignoring the `n` and I changed it to just call `bvTake` since it had less constraints than bvDrop.

**Comment by LeventErkok** [comment]
It's best not to conflate `SVal` and `SWord` abstractions; there are many invariants and if you can help it stick to just one variant. If you need to mediate in between, there are low-level functions to do so, but honestly anytime someone asked for this it turned out that it wasn't really necessary.

Having said that, this is how I would go about coding your function. Keep in mind that going back-and-forth between `Proxy` and the statically typed vs dynamic sizes will always give you hard time, but in case that's what you need to do, this would be the idiomatic way of doing it using the dynamic interface:

```haskell
import Data.SBV.Dynamic

svalDrop :: Int -> SVal -> SVal
svalDrop n inp
   | sz <= n = error $ "Trying to drop too much: " ++ show (n, k)
   | True    = svExtract (sz - n - 1) 0 inp
  where k  = kindOf inp
        sz = case k of
               KBounded _ v -> v
               _            -> error $ "getSignSize: Not a bitvector: " ++ show k
```

Now you can do:

```
*Main Data.SBV Data.SBV.Internals> svalDrop 3 (unSBV (2 :: SWord8))
2 :: SWord 5
```

Hope that helps!
```

**Comment by mpdairy** [comment]
Ah, thanks, that's very helpful. So can I rewrite all the bitvector-related functions in `Data.SBV` in terms of SVals using the `Dynamic` module? 

And would you say it's ok to convert SVals to SStrings in order to use the `Data.SBV.Strings` module?

Also, looking at the Z3 library, they have a bunch of specific API calls for bitvector operations. Would calling these directly (say, if I used the Z3 library instead) be more efficient than using SBV's bitvec ops (and handwritten ones using calls from `Dynamic`)?

**Comment by LeventErkok** [comment]
Essentially yes. An SBV is literally defined like this:

```haskell
newtype SBV a = SBV { unSBV :: SVal }
```
So, that's exactly what's happening internally anyhow. 

But the philosophy behind SBV is that you should never use `SVal`s, unless you're building some sort of a library on top of SBV. For most uses, programmers should stick to `SWord N`, `SInt N`, `SString`, `SFloat` etc.; and never even bother knowing they can all be operated via `SVal`s. While the `Data.SBV.Internals` module allows access to do so, you should shy away from it unless there's a good reason. (In particular, SBV keeps track of a whole bunch of internal invariants, and if you use the `Internal` interface, you promise not to break them. I'd recommend against casual uses of it.)

Regarding bit-vector API that Z3 has: I'd like to know if SBV is missing any. So far as I know, SBV should provide high-level API to everything in the bit-vector logic, covering the entire set of operations. There should be no need to call Z3-specific api's at all. If you find one, add a separate ticket and we'll implement it.

**Comment by mpdairy** [comment]
So if you are doing something like program analysis, where you don't know the width of bitvectors until runtime, you recommend exclusively using SVals and the operations in the `Dynamic` module? It seems like the recommended pattern would be to use SVals long enough to marshal them into SBV types, and then use the nice type-safe parts of SBV to work with them.

**Comment by LeventErkok** [comment]
Depends on the kind of analysis you're doing. For most program analyses everything is static, and you shouldn't need anything but good old typed interface. Even in that case, I'd recommend using a union type and sticking to it:

```haskell
data Val = Val1 SWord8
               |  Val2 SString
               | Val3 SFloat
              ...
```

This looks verbose, but it does pay off as the types do end up help quite a bit. 

But if you're building a "program analysis framework" (i.e., one that others can use to build program analyzers), then you probably want to store things as `SVal`s. But again, it all depends on the specific problem. My motto is stick to the typed interface as long as possible, and avoid `SVal` unless you absolutely can't.

**Comment by mpdairy** [comment]
Yeah, that's actually what I started out doing, but there is too much boiler-plate without dependent types. I tried to abstract things out, like make a function that just handles binary integral ops `binIntegral :: SIntegral a => (SBV a -> SBV a -> SBV a) -> SymExpr -> SymExpr -> Solver SymExpr` (`SymExpr` is my version of `Val`), but `a` always ends up being ambiguous because I can't make it depend on the `SymExpr`, so I think I'd have to do a giant case split on all the possible integral value of SymExpr for every polymorphic integral SBV function I want to call.

But I think that isn't a problem with SBV, just limitations with the type system and with my knowledge of Haskell.

**Comment by LeventErkok** [comment]
Program analysis is a substantial undertaking, and I'm not surprised you have to write quite a bit of code. I don't think there's anything inherently wrong with the approach, it just is the state of affairs. Honestly, it'd have been ten times worse in any other language. Even if you have a dependently typed language (like Idris, Coq, etc.) I doubt you can get away from the complexity.

I'm closing this ticket as this isn't really SBV related. But feel free to open new tickets if you find any issues with SBV itself; bugs or otherwise.

**Comment by mpdairy** [comment]
Ok, thanks for your help! It was good to know I wasn't doing it all wrong by using the `SymExpr` union type. I seem to have gotten over the boilerplate hurdle I was having by using RankNTypes. I'm so glad I can keep using the well-typed version of SBV!
