### ISSUE TITLE
Working with non-literal constant strings and lists

### ISSUE THREAD

**Issue by andrew-wja** [LeventErkok/sbv#525]
Apologies for what seems like a very simple issue, but I spent some time trying to figure out how to get the following to work, and it seems like it should be mentioned in the documentation.

I'm trying to constrain a symbolic string to be equivalent to a known constant string.

This works: `constrain $ foo .== "test"`

However, I get a type error when I replace the constant string "test" with a variable of type `String` containing "test".

```
>     • Couldn't match type ‘[Char]’ with ‘SBV.SBV String’
>       Expected type: SBV.SBV String
>         Actual type: String
>     • In the second argument of ‘(SBV..==)’, namely ‘var’
>       In the second argument of ‘($)’, namely ‘foo SBV..== var’
>       In a stmt of a 'do' block: SBV.constrain $ foo SBV..== var
```

I have `OverloadedStrings` turned on, which I believe takes care of literal string constants like `"test"`, but to deal with `String` variables, I found that I need to use the `GHC.Exts` `IsString` class, like so:

`constrain $ foo .== (fromString var)`

The same thing happens with lists. The problem is that the `Overloaded...` extensions only handle literal constants. 

At the top of both the `Data.SBV.String` and `Data.SBV.List` modules, it is mentioned that those extensions should be used, but it would be very helpful to anyone who isn't familiar with the `Overloaded...` GHC extensions if it were mentioned that the way to turn an arbitrary *non-literal* constant `String` or `List` into an `SBV String` or `SBV List` is to call `GHC.Exts.fromString` or `GHC.Exts.fromList`. 

Alternatively, would it be possible to export `fromString :: String -> SBV String` and `fromList :: [a] -> SBV [a]` from the respective `Data.SBV` submodules? This is done by some other packages just to make it easier for new users who aren't familiar with programming with GHC extensions by providing an explicit place in the library where conversions can be invoked.

**Comment by LeventErkok** [comment]
You should use the function `literal` for this purpose:

```haskell
Prelude Data.SBV> sat $ do { foo <- sString "foo"; constrain $ foo .== literal "test" }
Satisfiable. Model:
  foo = "test" :: String
```

Note that `literal` has type `SymVal a => a -> SBV a`, meaning you can use it on all symbolic types:

```haskell
Prelude Data.SBV> sat $ do { foo <- sInteger "foo"; constrain $ foo .== literal 3 }
Satisfiable. Model:
  foo = 3 :: Integer
```

Also works for lists:

```haskell
Prelude Data.SBV> sat $ do { foo <- sList "foo"; constrain $ foo .== literal [1,2,3::Integer] }
Satisfiable. Model:
  foo = [1,2,3] :: [Integer]
```

and essentially any symbolic value. 

`OverloadedLists` and `OverloadedStrings` etc. help avoid some of these, but `literal` is the way to go in general.
