### ISSUE TITLE
Constrain UFs in Query monad

### ISSUE THREAD

**Issue by MrChico** [LeventErkok/sbv#527]
I'm trying to add an injectivity condition to an uninterpreted function which is used in a symbolic execution which happens in a `Query` monad, but I'm struggling to figure out a good way to do this.

My first idea was to use the `forAll_` quantifier to make a simple `SBool` to constrain, but I found no way to promote a `forAll_ :: a -> SymbolicT m SBool` to the `Query` monad.

Another attempt involved adding an explicit `addAxiom` referring to the uf. This turned out to not be supported:
```
      Exception:
      *** Data.SBV: Unsupported interactive/query mode feature.
      ***  Adding a new axiom:
      *** Data.SBV: Please report this as a feature request!
```

Finally, I tried adding the axiom in the `Symbolic` context which encapsulates my `Query`. But now it appears that my uf is not defined yet, and I get an unknown function/constant error from z3.

Is there a better way of doing this that I am not seeing or is this a known limitation?

**Comment by LeventErkok** [comment]
Quite right that `forAll` can not be used in the query mode, and the way SBV is architected it would be really difficult to add support for that. Will likely remain unimplemented unless a major rewrite is done.

I can add `addAxiom` in the query mode; The only reason it isn't there is because I always thought `addAxiom` to be a rather blunt ax; it does serve its purpose but it is best avoided. And in general, you should be able to add it in the Symbolic context before the query starts. To avoid the "unknown function" error, use:

https://hackage.haskell.org/package/sbv-8.6/docs/Data-SBV-Control.html#v:registerUISMTFunction

There's an example use here: https://github.com/LeventErkok/sbv/blob/master/SBVTestSuite/TestSuite/Basics/UISat.hs#L39-L51

Let me know if that solves the problem. If not, we can see how to proceed from there. (A way for me to reproduce the problem would be nice.)

**Comment by MrChico** [comment]
Adding the function with `registerUISMTFunction` does seem to allow me to define the proper axioms, but it seems that adding the axiom in the Symbolic context does not seem to be sufficient for my needs, since I am using `(reset-assertions)` to be able to explore different cases.

In more detail, in doing symbolic execution of a program I am keeping a list of pathconditions along with the state of the program, and at branching points I check whether the branching condition and the pathconditions are satisfiable. For some reason, if I use `push` and `pop` or `checkSatAssuming`, z3 hangs and is not able to resolve any queries, but `(reset-assertions)` works fine.

But since I want to constrain the uninterpreted function globally, it seems this approach no longer works. It seems that `addAxiom` in query mode would resolve this problem. Or perhaps I can use a concurrent architecture along the lines of https://github.com/LeventErkok/sbv/blob/10f410c977ba38ea23042f509d639542654b2a53/Documentation/SBV/Examples/Queries/Concurrency.hs...

**Comment by LeventErkok** [comment]
Ah, I see the problem..

Sure, I'll add `addAxiom` to the query interface, shouldn't be terribly hard. But there's a little hack you can use right now:

https://hackage.haskell.org/package/sbv-8.6/docs/Data-SBV-Internals.html#v:sendStringToSolver

This should allow you to send any arbitrary string to the solver, and honestly when I add `addAxiom` it'll essentially be doing basically what `sendStringToSolver` does with the axioms you pass on.

Give that a try.. If it solves the problem, I'll add `addAxiom` to the query mode to make it nicer. If the problem persists for other reason, then we can take it from there.

**Comment by MrChico** [comment]
Thanks @LeventErkok. `sendStringToSolver` initially gave me some synchronization errors, but using it in combination with `retrieveResponseFromSolver` seems to do the trick. z3 doesn't seem to like these uninterpreted functions much, but that's another matter

**Comment by LeventErkok** [comment]
I guess `sendRequestToSolver` would've worked as well, which sends a string and expects back to get a success response. That should get rid of the need for the call to `retrieveResponseFromSolver`.

But bottom line, this is best done by supporting `addAxiom` in the query monad. I'll add support for this shortly.

**Comment by LeventErkok** [comment]
@MrChico 

`addAxiom` should now be available in the query mode. If you can build from github master and give it a try, that'd be great. If all is well, we can close this ticket. Let me know what you find out.

**Comment by LeventErkok** [comment]
@MrChico Did you get a chance to try this out? Would be good to close this ticket.

**Comment by MrChico** [comment]
@LeventErkok I just tried this and it seems to work as expected! Thanks for the support!

**Comment by LeventErkok** [comment]
@MrChico Thanks!

If you could tell me your real name, I'd like to add it to the "Thanks" list.

**Comment by MrChico** [comment]
Sure, you can add Martin Lundfall

**Comment by LeventErkok** [comment]
Thanks!
