### ISSUE TITLE
Command invocation for boolector no longer working.

### ISSUE THREAD

**Issue by jpziegler** [LeventErkok/sbv#531]
It appears that Boolector no longer accepts the --smt2-model flag, causing it to fail when invoked by SBV. (And Cryptol.)

**Comment by LeventErkok** [comment]
This seems to be a very recent change. I'll fix it shortly.

You can "work-around" this by setting the following environment variable:

```
SBV_BOOLECTOR_OPTIONS="--smt2 -m --output-format=smt2 --no-exit-codes --incremental"
```

Can you give that a try and see if the problem goes away at least temporarily?

**Comment by jpziegler** [comment]
That works, thank you!

**Comment by LeventErkok** [comment]
Great! According to:

  https://github.com/Boolector/boolector/blob/master/NEWS#L3

this change isn't actually released officially yet. I'll wait till they do an official release to make the corresponding change in SBV. (I'm assuming you're compiling directly from their github master?) Till then, you can use the above work-around as needed.

**Comment by jpziegler** [comment]
Yes, I should have said. I built from master.

**Comment by LeventErkok** [comment]
Looks like boolector folks are moving on to bitwuzla: https://bitwuzla.github.io

I'm not sure if boolector will ever have a new release; so this ticket seems moot. I'll keep it open so when/if there's an open-source release of bitwuzla we can add support for it.

**Comment by LeventErkok** [comment]
@jpziegler Boolector 3.2.2 is recently released, and SBV updated to match the new command line params.
