### ISSUE TITLE
yices binary name depends on packaging

### ISSUE THREAD

**Issue by robdockins** [LeventErkok/sbv#533]
CF https://github.com/GaloisInc/cryptol/issues/592

Apparently different methods of distribution will result in different names for the Yices SMT executable.  With some methods it is named `yices-smt` and with others it is named `yices_smt`. (note hyphen vs underscore).  I think we can handle this on the Cryptol side by tweaking `SMTConfig` options and seeing if either one works, but I thought I would bring this up here in case you wanted to think about SBV-side solutions to this issue.

**Comment by LeventErkok** [comment]
On my mac, it's called `yices-smt2`. It's unfortunate indeed.

The classical answer to these sorts of questions in SBV is either use the:

```haskell
proveWith yices{solver = (solver yices) { executable = "/where/is/yices" }}
```

Or, use the environment variable:

```
SBV_YICES=/where/is/yices
```

in your shell before you run the program.

Their documentation on https://github.com/SRI-CSL/yices2 also refers to the executable as `yices-smt2`.

I'm not sure if there's anything we can do better here. Perhaps the best would be for the user to create a symlink to `yices_smt2` and name it `yices-smt2`.

**Comment by robdockins** [comment]
Yeah, probably just messing with the `executable` field is the best solution.
