### ISSUE TITLE
Uninterpreted Examples consistently slower than native z3

### ISSUE THREAD

**Issue by doyougnu** [LeventErkok/sbv#544]
From recent benchmarking:

```
(Mean)
Benchmark                                              sbv(ms) standalone - sbv(%)
----------------------------------------------------- -------- -------------------
Puzzles//Birthday                                        62.08             -401.77
Uninterpreted//Correctness                               24.92             -198.22
Uninterpreted//SArray                                    22.13             -170.53
Uninterpreted//SFunArray                                 21.99             -168.16
Optimizations//VM.allocate                               50.56             -158.33
Uninterpreted//noWiggle                                  19.35             -135.61
Uninterpreted//existsOk                                  18.13             -130.00
Uninterpreted//thmGood                                   18.61             -127.60
Uninterpreted//shannon                                   20.02             -126.64
Uninterpreted//univOk                                    17.38             -121.27
Uninterpreted//synthMul22                                53.75             -116.51
Uninterpreted//shannon2                                  19.07             -112.59
Optimizations//ExtField.problem                          35.14             -112.35
Optimizations//LinearOpt.problem                         36.43             -107.96
Miscellaneous//notAssoc                                  21.61             -104.56
Optimizations//Production.production                     35.50             -102.91
Miscellaneous//Complement.Empty                          14.66             -102.05
Miscellaneous//Complement.Full                           14.62             -100.47
```

We can see that Uninterpreted examples are very common in the slowest benchmarks with `sbv` about 100% slower than native `z3`, with the average overhead for any benchmark ~50% slower. For the overhead benchmarks the benchmark program is generated for `z3` and `sbv` _before_ benchmarking begins. We don't expect `sbv` to be as fast as `z3` but getting to the same order of magnitude would be good.

**Comment by LeventErkok** [comment]
There's quite a bit of bookkeeping happening with uninterpreted values, but I'm curious why the slow down is so high. When you apply an uninterpreted function, you have to "serialize" all the arguments, and that might be a bit costly. For instance, an uninterpreted function of 3 arguments runs this code with each invocation:

https://github.com/LeventErkok/sbv/blob/e8b822117bf3db248aaa274658a270d4c0d98427/Data/SBV/Core/Model.hs#L2156-L2175

That's quite a bit of work. I'm not sure if there's an obvious way to make it go faster.

Also, I wonder what the impact of this line is:

https://github.com/LeventErkok/sbv/blob/e8b822117bf3db248aaa274658a270d4c0d98427/Data/SBV/Core/Symbolic.hs#L1032

I can't imagine that being costly, but something to watch for.

**Comment by doyougnu** [comment]
Great pointers, this will be very helpful so I know what to manually CAF during profiling. Regarding the `null nm` line, this is the perfect use case for what a `paying it forward` approach, i.e., if the function already knew `nm` was not empty with a new type `NonEmptyName` then the check wouldn't be required at all. Not sure if it would yield gains here though, only profiling could tell us that.

**Comment by LeventErkok** [comment]
@doyougnu Time to close this one?

**Comment by doyougnu** [comment]
```
benchmarked Uninterpreted//SArray/standalone
time                 4.322 ms   (4.304 ms .. 4.345 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 4.375 ms   (4.351 ms .. 4.401 ms)
std dev              127.9 μs   (104.5 μs .. 168.2 μs)
variance introduced by outliers: 24% (moderately inflated)

benchmarked Uninterpreted//SArray/sbv
time                 3.162 ms   (3.157 ms .. 3.169 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 3.190 ms   (3.184 ms .. 3.198 ms)
std dev              35.04 μs   (29.05 μs .. 43.15 μs)

benchmarked Uninterpreted//SFunArray/standalone
time                 4.201 ms   (4.183 ms .. 4.223 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 4.220 ms   (4.204 ms .. 4.238 ms)
std dev              84.78 μs   (72.04 μs .. 102.4 μs)
variance introduced by outliers: 13% (moderately inflated)

benchmarked Uninterpreted//SFunArray/sbv
time                 3.082 ms   (3.079 ms .. 3.085 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 3.076 ms   (3.073 ms .. 3.080 ms)
std dev              18.41 μs   (15.30 μs .. 23.85 μs)
```

Closing this issue. Looks like the performance difference has disappeared. There could be several explanations: The latest round of performance updates, I also ran this on a different machine with more RAM and more processing power, or any of the other updates seen to the code base over the last 5 months.
