### ISSUE TITLE
doctests are turned off

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#549]
Because GHC 8.10 seg-faults with doctest on SBV. Sigh.

Turn these back on in the Makefile

Possibly related: https://github.com/sol/doctest/issues/264

**Comment by LeventErkok** [comment]
@doyougnu Just to double check here, can you see if you can replicate the seg-faults I'm seeing with doc-test after the move to GHC 8.10.1.

Here's how you can run it:

```
$ SBV_TEST_ENVIRONMENT=local cabal new-run SBVDocTest -- --fast --no-magic
Up to date
SBVDocTest: Test platform: TestEnvLocal
[1]    1714 segmentation fault  SBV_TEST_ENVIRONMENT=local cabal new-run SBVDocTest -- --fast --no-magic
```

I'm curious if you get a seg-fault as well. (I'm on a Mac, would be great to see the behavior on Linux if you have access.)

**Comment by doyougnu** [comment]
Hey Levent, 

Unfortunately I'm having trouble building `sbv` against `ghc-8.10.1` and `ghcHEAD` on nixos (my flavor of linux)

Looks like there is still some issues to work out as both of these failed with dependency constraints on `base`. I've seen a fix floating around the nix world and I'll give it a try tomorrow.

**Comment by LeventErkok** [comment]
Thanks Jeff. Please do take your time, there's no super urgency on any of this. Maybe doctest guys will figure it out first.

**Comment by LeventErkok** [comment]
Another option is to use the new doctest-extract program, which isn't yet on hackage but is a candidate. See here: https://mail.haskell.org/pipermail/haskell-cafe/2020-August/132570.html

**Comment by LeventErkok** [comment]
Upgrading to GHC 8.10.2 solved this issue.
