### ISSUE TITLE
Can't build with AppVeyor using GHC 8.10.1

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#550]
@doyougnu 

Hi Jeff,

I'm trying to "upgrade" things to 8.10.1. But the Windows build on AppVeyor CI build is failing:

 https://ci.appveyor.com/project/LeventErkok/sbv/builds/34371652

(Linux/Mac Travis builds seem to be fine, using 8.10.1: https://travis-ci.org/github/LeventErkok/sbv/builds/712996752. I can also compile it fine on my own Mac.)

I can't quite read the failure message, but something to do with `bench-show` I think. Can you take a look?

**Comment by doyougnu** [comment]
Hey Levent,

Ah great! I wanted to benchmark `sbv` with `8.10`'s new garbage collector. I think the error is from the `svg-builder` dependency in `bench-show`. Looks like `bench-show` has been tested with `ghc-8.6.5` but nothing more recent than that. I've opened an [issue](https://github.com/composewell/bench-show/issues/12 ) on the project. In the meantime I think we should disable the benchmarks for the continuous integration. I'm not very familiar with the travis setup but I think this is as easy as changing:

`cabal new-build --only-dependencies --enable-tests --enable-benchmarks -f skipHLintTester`
 to 
`cabal new-build --only-dependencies --enable-tests -f skipHLintTester`

**Comment by LeventErkok** [comment]
@doyougnu How is it that it works on Linux and Mac?

**Comment by doyougnu** [comment]
Yea good question. In the benchmark code the only platform sensitive code is in `BenchSuite/Bench/Bench.hs`:

```
...
-- | Filepath to /dev/null
devNull :: FilePath
#ifndef WINDOWS
devNull = "/dev/null"
#else
devNull = "NUL"
#endif
...
```

but it is not clear to me how this would cause a build error. I've searched both `bench-show` and `svg-builder` for anything that would be sensitive to platform and didn't find anything.

**Comment by doyougnu** [comment]
actually I think that line might be behind it, looks like it should be:

```
...
-- | Filepath to /dev/null
devNull :: FilePath
#ifdef mingw32_HOST_OS
devNull = "NUL"
#else
devNull = "/dev/null"
#endif
...
```

**Comment by LeventErkok** [comment]
Figured out why it works with Travis/Linux; because we don't build the bench-suite there.. Duh..

Checked-in a new .cabal; which hopefully should fix this issue. You can pursue this separately of course if it's of interest.

**Comment by doyougnu** [comment]
Ok, I still suspect that ifdef, in any case I opened PR https://github.com/LeventErkok/sbv/pull/551 to fix it. I thought that by doing this through a PR we could test it without merging to master.

**Comment by doyougnu** [comment]
The PR build passed but only because the benchmarks were not enabled! Looks like I wasn't fast enough. Is the easiest test here to re-enable the benchmarks on AppVeyor or what? I don't have much experience tinkering with AppVeyor or Travis.

**Comment by LeventErkok** [comment]
I'll merge your PR and let's call this done. No need to chase a windows build failure; we'll never bench it on CI there.
