### ISSUE TITLE
Use int2bv if available

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#561]
@MrChico 

CVC4 and z3 support int2bv out-of-the box.

Yices and mathsat require manual translation.

dReal doesn't support bit-vectors, and abc doesn't support unbounded integers; so no support at all for those two.

We should do this via a solver-capability, picking the correct translation.

**Comment by LeventErkok** [comment]
@MrChico

Just pushed some changes which should use the native version if available. Give it a shot and let me know if it works as expected. Thanks!

**Comment by MrChico** [comment]
Thanks @LeventErkok , this seems to work well!

**Comment by LeventErkok** [comment]
Great. Thanks!
