### ISSUE TITLE
Custom HasKind Instance For a User Defined Type

### ISSUE THREAD

**Issue by xwvvvvwx** [LeventErkok/sbv#575]
I have a custom type that wraps a few underlying SBV types:

```haskell
data Atomic
  = SymInteger (SBV Integer)
  | SymBool (SBV Bool)
  | SymBytes (SBV String)
  deriving (Show)
```

I would like to use this type as the key / value type in an SMT array, so I defined a custom `HasKind` instance as follows:

```haskell
instance HasKind Atomic where
   kindOf (SymInteger _) = KUnbounded
   kindOf (SymBool _) = KBool
   kindOf (SymBytes _) = KString
```

However when I try to construct an `SArray Atomic Atomic`, I hit the [undefined in Kind.hs](https://github.com/LeventErkok/sbv/blob/59c1cf37070a5423113f950bf071804257756c7a/Data/SBV/Core/Kind.hs#L279).

Is there a way to build a `HasKind` instance for my type, or am I just barking up the wrong tree?

**Comment by LeventErkok** [comment]
This isn't how `HasKind` is supposed to be used. In particular, `HasKind` cannot inspect the value it's looking at, and should only be determined by the underlying type. So, you can make the whole `Atomic` to have a kind, but you cannot distinguish between its constructors.

In general you do *not* want to make `Atomic` in your example symbolic; but rather use that at the Haskell level with a concrete spine that has symbolic elements attached. Of course not knowing what you are exactly trying to do makes it hard to suggest alternatives.
