### ISSUE TITLE
Enable Query mode for Boolector and Yices

### ISSUE THREAD

**Issue by doyougnu** [LeventErkok/sbv#577]
Hey Levent,

Looks like both Yices and Boolector have query mode disabled, for example `Data.SBV.Provers.Yices` :
```
yices :: SMTSolver
yices = SMTSolver {
           name         = Yices
         , executable   = "yices-smt2"
         , preprocess   = id
         , options      = const ["--incremental"]
         , engine       = standardEngine "SBV_YICES" "SBV_YICES_OPTIONS"
         , capabilities = SolverCapabilities {

...
                              , supportsGlobalDecls        = False
...
                              }
         }

```

Even though in their APIs they support query mode. What are the barriers to enabling them? Flipping the boolean allows them to be run in query mode. I've just done some simple testing and it seems ok. Do you remember why these were disabled?

If enabled, what tests would have to be added to the test suite?

**Comment by LeventErkok** [comment]
Queries are controlled by the `supportsCustomQueries` parameter. And for both Yices and Boolector, that's set to `True`.

What's not supported is calls to `pop` when `supportsGlobalDecls` is `False`. Everything else should just work. Are you seeing something different?

**Comment by doyougnu** [comment]
I was seeing an error message similar to that effect, but this may be a bug in my own code. Let me dig into it to make sure.

**Comment by LeventErkok** [comment]
In the case of `pop`; SBV needs the solver to support what's known as global-declarations. It could be the case that these solvers do support that feature now, I haven't checked in a while. If so, let's go ahead and flip the bits after verifying. See pg. 12 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf for info on `:global-declarations`

**Comment by doyougnu** [comment]
Hey Levent,

I think I understand what is going on. This might just be documentation confusion. Consider the example from `SBV.Control`:
```
test :: Symbolic (Maybe (Integer, Integer))
test = do x <- sInteger "x"   -- a free variable named "x"
          y <- sInteger "y"   -- a free variable named "y"

          -- require the sum to be 10
          constrain $ x + y .== 10

          -- Go into the Query mode
          query $ do
                -- Query the solver: Are the constraints satisfiable?
                cs <- checkSat
                case cs of
                  Unk   -> error "Solver said unknown!"
                  Unsat -> return Nothing -- no solution!
                  Sat   -> -- Query the values:
                           do xv <- getValue x
                              yv <- getValue y

                              io $ putStrLn $ "Solver returned: " ++ show (xv, yv)

                              -- We can now add new constraints,
                              -- Or perform arbitrary computations and tell
                              -- the solver anything we want!
                              push 1
                              constrain $ x .> literal xv + literal yv
                              pop 1

                              -- call checkSat again
                              csNew <- checkSat
                              case csNew of
                                Unk   -> error "Solver said unknown!"
                                Unsat -> return Nothing
                                Sat   -> do xv2 <- getValue x
                                            yv2 <- getValue y

                                            return $ Just (xv2, yv2)
main :: IO ()
main = do
  putStrLn "running"
  res <- runSMTWith yices test
  putStrLn $ show res
```
Notice that I'm running it with yices and have inserted the `push` and `pop`. This results in:
```
running
Solver returned: (10,0)
SBVBench:
*** Data.SBV: Backend solver does not support global-declarations.
***           Hence, calls to 'pop' are not supported.
***
*** Request this as a feature for the underlying solver!

CallStack (from HasCallStack):
  error, called at ./Data/SBV/Control/Query.hs:541:35 in sbv-8.9.5-inplace:Data.SBV.Control.Query
Benchmark SBVBench: ERROR
cabal: Benchmarks failed for bench:SBVBench from sbv-8.9.5.
```
which makes sense due to the globals check in `pop`:
```
-- | Generalization of 'Data.SBV.Control.pop'
pop :: (MonadIO m, MonadQuery m) => Int -> m ()
pop i
 | i <= 0 = error $ "Data.SBV: pop requires a strictly positive level argument, received: " ++ show i
 | True   = do depth <- getAssertionStackDepth
               if i > depth
                  then error $ "Data.SBV: Illegally trying to pop " ++ shl i ++ ", at current level: " ++ show depth
                  else do QueryState{queryConfig} <- getQueryState
                          if not (supportsGlobalDecls (capabilities (solver queryConfig)))
                             then error $ unlines [ ""
                                                  , "*** Data.SBV: Backend solver does not support global-declarations."
                                                  , "***           Hence, calls to 'pop' are not supported."
                                                  , "***"
                                                  , "*** Request this as a feature for the underlying solver!"
                                                  ]
                             else do send True $ "(pop " ++ show i ++ ")"
                                     restoreTablesAndArrays
                                     modifyQueryState $ \s -> s{queryAssertionStackDepth = depth - i}
   where shl 1 = "one level"
         shl n = show n ++ " levels"
```
However, this is a legal program in yices:
```
[nix-shell:~]$ yices
yices> (define y::int)
yices> (define x::int)
yices> (assert (= 10 (+ x y)))
yices> (check)
sat
yices> (show-model)
(= y 10)
(= x 0)
yices> (push)
yices> (assert (> x (+ 0 10)))
yices> (check)
sat
yices> (show-model)
(= y -1)
(= x 11)
yices> (exit)
```

If I flip the `global-declaration` boolean in `sbv` then the yices example works no problem (because its a legal yices program). Here's the relevant snippet from the `SMTLIB2` standard:

> 4.1.5    Symbol declarations and definitions
> 
> A number of commands allow the declaration or definition of a function or sort symbol.  By default, these declarations and definitions are added to the current assertion level when the corresponding command is executed.  Popping that assertion level removes them. As an alternative, declarations and definitions can all be made global by running the solver with the option :global-declarations set to true. When running with this option set, all declarations and definitions become permanent. That is, they survive any pop operations on the assertion stack as well as invocations of reset-assertions and can only be removed by a global reset,achieved with the reset command

So the current implementation of `supportsGlobalDecls` and `pop` prevent _any_ program from using `pop` if `supportsGlobalDecls = True`, whereas the description in the `SMTLIB2` standard is that any call to `pop` should be a `noop`, but should still be allowed...if I'm not mistaken.

This isn't a high ticket item for me and I'd prefer to tie up some loose ends (complete the `Text` and `rInps` refactor) before fixing it, I'm just using my forked version of `sbv` with these flags flipped for my needs and I'm not sure how useful it is for others.

**Comment by LeventErkok** [comment]
You say:

> So the current implementation of supportsGlobalDecls and pop prevent any program from using pop if supportsGlobalDecls = True, whereas the description in the SMTLIB2 standard is that any call to pop should remove assertions but not declarations or definitions, but should still be allowed...if I'm not mistaken.

I guess you meant `if supportsGlobalDecls = False.` And that is indeed the intended behavior. Note that if you just had a `push` in your SBV program, you could've just run it through yices; there wouldn't be any problems at all. But you cannot do a `pop` because the solver would forget all the initial declarations; and that'd cause the solver to error-out if you later refer to the variables defined earlier. (And at worst it'd be unsound, though I'd think that'd be rare.)

So, I don't see anything wrong with the documentation. 

The good news is that it looks like yices and boolector actually do support global-declarations these days. I just tested it. I guess when I was first adding support for them, they didn't. (This was quite a while ago.) I just pushed a fix so they're now supported. Give it a try.

**Comment by doyougnu** [comment]
Ah yes you are right, I meant `supportsGlobalDecls = False`.

> Note that if you just had a push in your SBV program, you could've just run it through yices

The program did have a `push` before the `pop`. This was my point, that any call to `pop` would be prevented even if it was balanced with a call to `push`.

In any case, your fix works great, as always thanks for the quick turn around!

**Comment by LeventErkok** [comment]
Even if push/pop are balanced, without support for global-decls SBV wouldn't work correctly: Just imagine how the constants would work if you create some after the `push`, which also gets used after the `pop`. If the solver doesn't support `globalDecls`, then it would forget the definition of that constant.

In any case, since yices/boolector do support the setting now, it's a moot point indeed.
