### ISSUE TITLE
Z3 crashes on formula generated by forall combined with sArray

### ISSUE THREAD

**Issue by frenchfrog42** [LeventErkok/sbv#587]
Hi ! It's me again with arrays, sorry.

When I declare an array, use it, and then do a "forall" it generates a "wrong" formula for Z3. But if I don't use the array (or if I use sFunArray instead of sArray) it works fine.

Here is my code :

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV

-- Wrong formula generated for Z3
sArrayDef :: SymbolicT IO SBool
sArrayDef = do
  array_  :: SArray Int32 Int32 <- newArray_ Nothing
  let array = writeArray array_ 0 0
  k_cond :: SBV Int32 <- forall_
  let cond = readArray array k_cond .== 0
  solve [cond]

-- Works fine
sArray :: SymbolicT IO SBool
sArray = do
  array_  :: SArray Int32 Int32 <- newArray_ Nothing
  let array = array_ --only difference
  k_cond :: SBV Int32 <- forall_
  let cond = readArray array k_cond .== 0
  solve [cond]

main :: IO ()
main = do
  res_array_def <- sat sArrayDef
  case res_array_def of
    SatResult (Satisfiable _ _) -> print "sFunArray is SAT"
    SatResult (Unsatisfiable _ _) -> print "sFunArray in UNSAT"
    _ -> error ""
  res_array <- sat sArray
  case res_array of
    SatResult (Satisfiable _ _) -> print "sArray is SAT"
    SatResult (Unsatisfiable _ _) -> print "sArray in UNSAT"
    _ -> error ""
```

Output of the code (the code crashes before executing the 2nd part of the code. But the 2nd part works fine)

```
*** Data.SBV: Unexpected non-success response from Z3:                                                                  
***                                                                                                                    
***    Sent      : (assert (forall ((s0 (_ BitVec 32)))                                                                 
***                            (let ((s2 (select array_1 s0)))                                                          
***                            (let ((s3 (= s1 s2)))                                                                    
***                (define-fun array_1_initializer () Bool array_1_initializer_0)                                       
***                (assert array_1_initializer)                                                                         
***                            s3))))                                                                                   
***    Expected  : success                                                                                              
***    Received  : (error "line 14 column 12: unknown constant array_1_initializer")                                    
***                                                                                                                     
***    Exit code : ExitFailure (-15)                                                                                    
***    Executable: /home/www/.local/bin/z3                                                                             
***    Options   : -nw -in -smt2                                                                                        
***                                                                                                                     
***    Reason    : Check solver response for further information. If your code is correct,                              
***                please report this as an issue either with SBV or the solver itself!
```

I encountered that issue when trying to play with array and emulate a "map". From what I understood I can do map in Z3, is there a support in SBV for that functionality ? Maybe mergeArrays ? Right now I do a map with a forall

Thanks !

**Comment by LeventErkok** [comment]
Thanks for the report. Bug reports are always welcome; so keep them coming.

Note that I removed `SFunArray` from the code-base; and the next hackage release will make that permanent.

Regarding the bug you just reported, I pushed in a fix; see if it solves them and let me know what you find out.

**Comment by frenchfrog42** [comment]
Hello ! Thanks for the quick answer !
Here is a new instance where it doesn't work

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV

-- Wrong formula generated for Z3
sArrayDef :: SymbolicT IO SBool
sArrayDef = do
  array  :: SArray Int32 Int32 <- newArray_ Nothing
  let new = writeArray array 0 (readArray array 0)
  solve [readArray new 0 .== 0]

main :: IO ()
main = do
  res_array_def <- sat sArrayDef
  case res_array_def of
    SatResult (Satisfiable _ _) -> print "sFunArray is SAT"
    SatResult (Unsatisfiable _ _) -> print "sFunArray in UNSAT"
    _ -> error ""
```

Output of the code

```*** Data.SBV: Unexpected non-success response from Z3:                                                                  
***                                                                                                                     
***    Sent      : (define-fun array_1_initializer_0 () Bool (= array_1 (store array_0 s0 s1)))                         
***    Expected  : success                                                                                              
***    Received  : (error "line 10 column 71: unknown constant s1")                                                    
***                                                                                                                     
***    Exit code : ExitFailure (-15)                                                                                    
***    Executable: /home/www/.local/bin/z3                                                                            
***    Options   : -nw -in -smt2                                                                                        
***                                                                                                                     
***    Reason    : Check solver response for further information. If your code is correct,                              
***                please report this as an issue either with SBV or the solver itself! 
```

**Comment by LeventErkok** [comment]
Pushed in another fix; hopefully this'll solve the issues. Give that a try and let me know what you find out.

**Comment by frenchfrog42** [comment]
Hey !
Thanks for the quick fix. Unfortunately I'm still getting the "Non-constant array initializer in a quantified context" error in my code, and the only issue I found on the web doesn't really help ( #378 )

Here is one example :
```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV

sArrayDef :: SymbolicT IO SBool
sArrayDef = do
  array  :: SArray Int32 Int32 <- newArray_ Nothing
  let e =  readArray array 0
  let array1 = writeArray array 0 e
  array2  :: SArray Int32 Int32 <- newArray_ Nothing
  k :: SInt32 <- forall_
  let cond = readArray array k .== readArray array2 k
  solve [cond, readArray array1 0 .== readArray array2 0]

main :: IO ()
main = do
  res_array_def <- sat sArrayDef
  case res_array_def of
    SatResult (Satisfiable _ _) -> print "sFunArray is SAT"
    SatResult (Unsatisfiable _ _) -> print "sFunArray in UNSAT"
    _ -> error ""
```

Output of the code

```
test.hs: SBV.SMTLib2: Not-yet-supported: Non-constant array initializer in a quantified context                         
CallStack (from HasCallStack):                                                                                            
error, called at ./Data/SBV/SMT/SMTLib2.hs:41:9 in sbv-8.14.5-6x3hCMfslgzAoqq0RO6yQk:Data.SBV.SMT.SMTLib2
```

But it seems Z3 can handle it fine, because this formula (which I believe is equivalent to my haskell code) is declared SAT
```common-lisp
(declare-const array (Array Int Int))

; let e = readArray array 0
(declare-const e Int)
(assert (= e (select array 0)))

; let array1 = writeArray array 0 e
(declare-const array1 (Array Int Int))
(assert (= (store array 0 e) array1))

; readArray array k .== readArray array2 k
(declare-const array2 (Array Int Int))
(assert (forall ((k Int)) (= (select array k) (select array2 k))))

; readArray array1 0 .== readArray array2 0
(assert (= (select array1 0) (select array2 0)))

(check-sat)
```

Do you have an idea on how I can change the haskell code to escape that ? Maybe it's still a bug ? Because defining array1 as `let array1 = writeArray array 0 0` (so 0 instead of e at the end) makes it work

Thanks

**Comment by LeventErkok** [comment]
In the presence of quantifiers, SBV skolemizes the input formula. The issue here is that you're creating `array1` by writing `e` into element 0; and `e` happens to be an expression; and SBV is telling you that it doesn't know how to skolemize `e`, which might end up being a huge sequence of expressions. (In this case it's a simple `readArray`, but in general it can be an arbitrary sequence.)

To summarize, this is a piece of functionality that SBV is missing: It can be added of course, but it would require quite a bit of work and I'm not sure if it's justified.

Regarding workarounds: It's hard to suggest something here. Obviously, you can write `let array1 = writeArray array 0 0`. Your examples seem contrived; which makes it hard for me to understand the actual use case. If you can describe what actual problem you're trying to solve, there might be some other way to code this up.

In general shy away from quantifiers: SBV's support for them is rather weak; and solvers usually don't do well with them either.

**Comment by frenchfrog42** [comment]
Thanks for the explanation !

Unfortunately I think I can't write `writeArray array 0 0` in my code. My usecase is modeling a database with Z3 arrays.

So I read, write, and apply function to that database/array.
Reads and writes are fines with readArray and writeArray.

But applying functions needs to map a function on the array, and I couldn't find that in the SBV doc (from what I understood it's ok in Z3 to do so). That's why I'm using foralls. I want to increment all the element of the array by 1 for instance. And therefore I'm asking Z3 to satisfy `forall x, readArray new x .== 1 + readArray old c`.

Here is a code example
```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Data.SBV

sArrayDef :: SymbolicT IO SBool
sArrayDef = do
  database :: SArray Int32 Int32 <- newArray_ Nothing

  -- Increment one element
  let database1 = writeArray database 0 (1 + readArray database 0)

  -- Increment everyone
  database2  :: SArray Int32 Int32 <- newArray_ Nothing
  k <- forall_
  let must_be_true_database2 = 1 + (readArray database k) .== readArray database2 k

  solve [must_be_true_database2, readArray database1 0 .== readArray database2 0]

main :: IO ()
main = do
  res_array_def <- sat sArrayDef
  print res_array_def
```

My usecase is therefore : I start from a database, I apply a set of transformations (some of which affect an unknown amount of elements, something like `all element between 0 and x are incremented` but x is one argument of the transformations I don't know it. In the code here x is like +infinity), and then compare the result.
If I could map a function on array it would be ok, but can't find it :/

Thanks !

**Comment by LeventErkok** [comment]
Z3 has a very limited notion of mapping functions over arrays. In particular, you cannot map arbitrary functions; but only built-in ones. In either case, SBV does not support such an operation, as this is beyond SMTLib and SBV tries (to a large extent) to stay within the SMTLib boundary.

I think the theory of arrays is going to lead you astray here: The kind of quantification you want to write is not supported by SBV, and furthermore, the moment you introduce these quantifiers it's very likely that z3 will start telling you `unknown`.

I'd instead use uninterpreted functions to model the database, and user-given axioms to assert the "mapping" part. Unfortunately this is a bit of a hack, since user-given axioms are merely strings and they can be fragile. But if you keep naming your uninterpreted functions consistently, I think you can get away with the kind of modeling you want to do.

Based on this, here's how I'd model your problem in SBV:

```haskell
import Data.SBV

-- Model databases as functions from addresses to values
type Adr = SInteger
type Val = SInteger
type DB  = Adr -> Val

-- An "uninitialized" database
newDB :: String -> DB
newDB = uninterpret

-- Reading from an address
readDB :: DB -> Adr -> Val
readDB db adr = db adr

-- Writing to an address
writeDB :: DB -> Adr -> Val -> DB
writeDB db adr val = \adr' -> ite (adr .== adr') val (readDB db adr')

-- Updating the element at an address
updDB :: DB -> Adr -> (Val -> Val) -> DB
updDB db adr f = writeDB db adr (f (readDB db adr))

test :: Predicate
test = do
  let db = newDB "db"

  -- Increment element at index 0
  let db1 = updDB db 0 (1+)

  -- Increment all elements
  let db2 = newDB "db2"
  addAxiom "db2_is_db+1" ["(assert (forall ((k Int)) (= (+ 1 (db k)) (db2 k))))"]

  -- check db1 and db2's 0'th element match
  pure $ readDB db1 0 .== readDB db2 0
```

Now, you can say:

```haskell
*Main> prove test
Q.E.D.
```

which is I believe what you are after. The presence of `addAxiom` is ugly and fragile; but so long as you name your variables consistently, it should work out.

The advantage of this approach is that it can give you a nicer counter-example than what you'd get with arrays as well. For instance, if I change the line:

```haskell
  let db1 = updDB db 0 (1+)
```

to:

```haskell
  let db1 = updDB db 0 (2+)
```

then I get:

```
*Main> prove test
Falsifiable. Counter-example:
  db :: Integer -> Integer
  db _ = 0

  db2 :: Integer -> Integer
  db2 _ = 1
```

which shows you a nice counter-example to your failing property. (You can do similar things with arrays, but it's a lot harder.)

I hope this lets you make progress. But, to summarize, I'd avoid arrays and instead rely on uninterpreted functions and very carefully chosen axioms. It's a bit brittle, but I think it'll fulfill your current needs.
