### ISSUE TITLE
unknown constant mkSBVTuple2

### ISSUE THREAD

**Issue by gregsgit** [LeventErkok/sbv#589]
[crash.log](https://github.com/LeventErkok/sbv/files/6996537/crash.log)
[Main.hs.txt](https://github.com/LeventErkok/sbv/files/6996538/Main.hs.txt)

new to SBV. Using lots of tuples, including for example:

```
type    SRule           = STuple (Label, Label, Label, Label) (Maybe (Label, Label))
```

Z3 version 4.8.12 - 64 bit - build hashcode 3a402ca2c14c3891d24658318406f80ce59b719f

Any thoughts on a workaround?
Thanks.

```
***    Expected  : success
***    Received  : (error "line 163 column 46: unknown constant mkSBVTuple2 ((_ BitVec 16) (_ BitVec 16)) 
***                declared: (declare-fun mkSBVTuple2
***                             ((SBVTuple4 Label Label Label Label)
***                              (SBVMaybe (SBVTuple2 Label Label)))
***                             (SBVTuple2 (SBVTuple4 Label Label Label Label)
***                                        (SBVMaybe (SBVTuple2 Label Label)))) 
***                declared: (declare-fun mkSBVTuple2 (Label Label) (SBVTuple2 Label Label)) ")
***
***    Exit code : ExitFailure (-15)
***    Executable: /home/gregs/other-repos/z3/build/z3
***    Options   : -nw -in -smt2

```

**Comment by LeventErkok** [comment]
Looks like z3 is not quite up to handling this usage. Try cvc4, like this:

```
myConfig = cvc4 { extraArgs = "--strings-exp" }
```

However, when I run it like that cvc4 gets going but does not terminate quickly. Quantifiers are usually a soft-spot for SMT solvers; if you can avoid them, that'd be the way to go.

**Comment by gregsgit** [comment]
Thank you very much for the follow up!
-- Greg

--
Greg Sullivan   email: ***@***.***   cell: 617-417-4746
70 Pigeon Hill Street, Rockport, MA 01966

**Comment by LeventErkok** [comment]
@gregsgit 

This seems to be an issue with z3 itself. I've reported it here: https://github.com/Z3Prover/z3/issues/5486

**Comment by LeventErkok** [comment]
@gregsgit

Based on feedback from the z3 folks, I pushed this commit https://github.com/LeventErkok/sbv/commit/0d5b1e5904a6d30869fd479bf9af427eb4ee8281 which should handle the problem you're running into.

Give it a test and let me know if it gets you past the failure.

**Comment by gregsgit** [comment]
That fix works; I get past the failure; thank you very much!

**Comment by gregsgit** [comment]
Fixed

**Comment by LeventErkok** [comment]
Great! Thanks for the update.

**Comment by LeventErkok** [comment]
@gregsgit 

A new release of SBV (v8.16) is now on package that contains this fix: https://hackage.haskell.org/package/sbv
