### ISSUE TITLE
Missing CRational case

### ISSUE THREAD

**Issue by noughtmare** [LeventErkok/sbv#591]
While trying to find an answer to [this stackoverflow question](https://stackoverflow.com/q/69033969/15207568) I think I found a pattern match that is missing a case for `CRational`:

https://github.com/LeventErkok/sbv/blob/cfaa40b8c8ff8e1b7ff9ab71304654f6f531ba72/Data/SBV/Core/Concrete.hs#L324-L337

I'm not familiar with the code-base, but this seems like a bug.

**Comment by LeventErkok** [comment]
Fixed in the repo. Thanks for the report.
