### ISSUE TITLE
How to express an interpretable functions?

### ISSUE THREAD

**Issue by yaitskov** [LeventErkok/sbv#593]
Z3 SMT syntax has "define-fun" and "define-fun-rec".
Is it possible to define interpretable function with SBV DSL?

**Comment by LeventErkok** [comment]
No; SBV does not allow users to define functions in this way. (You can define uninterpreted functions however.) SBV executes by completely symbolically executing your program, unrolling all function calls, and getting a straight-line SMBLib program. All function definitions (aside from uninterpreted ones) are gone by the time it ships the problem to the underlying SMT solver.
