### ISSUE TITLE
Show CVal instance is missing

### ISSUE THREAD

**Issue by yaitskov** [LeventErkok/sbv#597]
Hi,

CVal doesn't have Show instance.

**Comment by LeventErkok** [comment]
This is on purpose. You shouldn't need to `show` any `CVal` values.

At best, you'd want to show `CV`'s, which wraps around `CVal` with kind info, and those are instances of `Show` if you `import Data.SBV.Internals`.

**Comment by yaitskov** [comment]
What is the expected way to transfer model CV values to Haskell program types?
I wasn't able to find functions and do pattern matching for specific CVal data constructors and fallback branch use Show to help me understand that I don't branch for specific data constructor.

**Comment by LeventErkok** [comment]
There are several ways. But the easiest to use is probably using the query monad and the `getValue` function: https://hackage.haskell.org/package/sbv-8.16/docs/Data-SBV-Control.html#v:getValue

There's an example at the very top of https://hackage.haskell.org/package/sbv-8.16/docs/Data-SBV-Control.html
