### ISSUE TITLE
add `svToSV` to Internals exports

### ISSUE THREAD

**Issue by mpdairy** [LeventErkok/sbv#599]
I'm trying to do make some "dynamic" list operations that work on SVal lists. I was hoping I could lift `SVal`s into the typed list functions and use `SList`, but the problem is that I have to deal with bitvectors of arbitrary width, unknown at compile time, so it's hard to specify the type for an `SList a`.

So, sadly, my only alternative seems to be to make some dynamic versions of the list functions I need.  I have all the pieces I need, except for `svToSV` from `SBV.Core.Symbolic`.

**Comment by mpdairy** [comment]
Let me know if you'd accept a PR that does this, and I'll make one.

**Comment by LeventErkok** [comment]
Sure. PR's are always welcome..
