### ISSUE TITLE
Support for bit-blasting

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#6]
Add support for bit-blasting SBV, and integration with SAT solvers such as ABC (http://www.eecs.berkeley.edu/~alanmi/abc/)

**Comment by elefthei** [comment]
Apologies for resurrecting this old issue but what's the status of integration with ABC? Is it possible to bit blast an SBV expression into an AIG? I think SAW uses AIGs so maybe it does exist but just in a different place.

**Comment by LeventErkok** [comment]
ABC is supported by SBV; since they added basic support for SMTLib. You can use:

    proveWith abc $ \x -> x + x .== 2 * (x::SWord8)

and it should work if you've a recent version of `abc` installed.

I should add that ABC's support for SMTLib format is rather limited; there are cases where it incorrectly parses the SMTLib format and does the wrong thing. (For instance, it does not support arrays.) If you stick to bit-vectors, it should more or less work just fine.

But otherwise, SBV does *not* support bit-blasting. Nor there are any plans for it. Let me know if the existing ABC interface gives you hard time!
