### ISSUE TITLE
GHC 9.2. release

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#606]
All blockers resolved; this'll go ahead shortly.

**Comment by ksqsf** [comment]
Hi, what's the status of the new release? I just tried ghc 9.2.2 but the compilation failed.

**Comment by LeventErkok** [comment]
I expect a Hackage release within the next few weeks. If you have an urgent need, you should be able to compile from GitHub master, which should compile cleanly with 9.2.2.

**Comment by LeventErkok** [comment]
@ksqsf 

Sorry about the delay. SBV 9.0 is now released on hackage, and it should compile cleanly with GHC 9.2.2: https://hackage.haskell.org/package/sbv
