### ISSUE TITLE
Build failure with GHC 9.2.1

### ISSUE THREAD

**Issue by sjakobi** [LeventErkok/sbv#607]
```
Building library for sbv-8.17..

Data/SBV/Core/AlgReals.hs:281:27: error: [-Wincomplete-uni-patterns, -Werror=incomplete-uni-patterns]
    Pattern match(es) are non-exhaustive
    In a pattern binding:
        Patterns of type ‘[Int]’ not matched:
            []
            [_]
            (_:_:_:_)
    |
281 |                           [lts, lfs] = map length [ts, fs]
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
I get the same error building v8.10, v8.13 and v8.16.

As a Hackage trustee, I have created some Hackage revisions that should prevent users from running into this error, e.g. https://hackage.haskell.org/package/sbv-8.17/revisions/

**Comment by LeventErkok** [comment]
@sjakobi Thanks! I'm aware of this, and I'm tracking it at #606 

Alas, some other dependencies are currently blocking an immediate release. Thanks for doing the revisions.
