### ISSUE TITLE
`SymVal` and `HasKind` instances for `Int`

### ISSUE THREAD

**Issue by finnteegen** [LeventErkok/sbv#611]
Hello,

is there a reason why there is no support for the built-in `Int` type? I know that its size depends on the architecture etc. But I wondered whether it would be possible to give the following definitions (based on getting the actual size at run-time):

```haskell
import Data.Bits (finiteBitSize)

instance SymVal Int where
  mkSymVal = genMkSymVar (KBounded True (finiteBitSize @Int 0))
  literal  = genLiteral  (KBounded True (finiteBitSize @Int 0))
  fromCV   = genFromCV

instance HasKind Int where
  kindOf _ = KBounded True (finiteBitSize @Int 0)
```

Unfortunately, one cannot define these instances by hand because none of the methods of the `SymVal` class are exposed. However, having these instances available would be quite helpful.

Cheers,
Finn

**Comment by LeventErkok** [comment]
The basic philosophy behind SBV is to be very clear about sizes, so one instead uses `Int32/Int64` and `SInt32/SInt64`.

Is there a reason why you can't use `Int32` or `Int64` yourself? I'm not sure if introducing the architectural ambiguity is worth it here. (Similarly, I think it'd have been better if Haskell never had the `Int` type to start with, but I digress. For instance, rust completely goes for specific sized-types.)

I'm inclined towards leaving the design as is, though I'd like to hear if you have an example where this really makes a difference. Note that if you really want to do this, you can work around by using the internals escape-hatch:

```haskell
{-# LANGUAGE TypeApplications #-}

import Data.SBV
import Data.SBV.Internals

import Data.Bits (finiteBitSize)

instance SymVal Int where
  mkSymVal = genMkSymVar (KBounded True (finiteBitSize @Int 0))
  literal  = genLiteral  (KBounded True (finiteBitSize @Int 0))
  fromCV   = genFromCV

instance HasKind Int where
  kindOf _ = KBounded True (finiteBitSize @Int 0)
```

The above loads just fine, reaching into the `SymVal` class through the `Data.SBV.Internals` module. I usually don't advise these mechanisms, as they are usually not worth the effort at the end of the day. But perhaps you have a good use case that can benefit from it.

**Comment by LeventErkok** [comment]
No worries! Best of luck and do let me know if you spot any further issues.

Note that for general SBV questions, stack-overflow has a custom tag: https://stackoverflow.com/questions/tagged/sbv
