### ISSUE TITLE
RegExp.All translates to re.allchar, not re.all as the docs would imply

### ISSUE THREAD

**Issue by Torrencem** [LeventErkok/sbv#616]
According to the docs for the [UnicodeStrings theory](https://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml), there are two SMT-Lib regexps:
```
        ; Constant denoting the set of all strings 
        (re.all RegLan)

        ; Constant denoting the set of all strings of length 1
        (re.allchar RegLan)
```
from the [documentation of SBV](https://hackage.haskell.org/package/sbv-8.17/docs/Data-SBV-RegExp.html#t:RegExp), we'd expect `All` to translate into `re.all` (the regular expressioni that accepts every string). However, [it is instead translated to re.allchar](https://github.com/LeventErkok/sbv/blob/bece33a30b5bc676edabc3ab50bc112c07bf2287/Data/SBV/Core/Symbolic.hs#L409). It would make more sense if there were a function `allchar` that translated to `re.allchar`, and if `All` translated to `re.all`.

**Comment by LeventErkok** [comment]
Thanks! Looks like there's a couple of problems with the pull request (nothing big); if you could update those I'll merge the patch. (I added review comments)

**Comment by Torrencem** [comment]
That's odd, I'm having trouble finding the review comments (I know github has been kind of borked today)

**Comment by LeventErkok** [comment]
Thanks!

I've also added `everything`, `nothing`, and `anyChar` to regexeps, which might come in handy:

https://github.com/LeventErkok/sbv/blob/b5e25f870b58997883f31b3e4d20d30b53672142/Data/SBV/RegExp.hs#L128-L147

Also added the `Power` constructor:

https://github.com/LeventErkok/sbv/blob/b5e25f870b58997883f31b3e4d20d30b53672142/Data/SBV/Core/Symbolic.hs#L364

where `Power n r` is shorthand for `Loop n n r`.
