### ISSUE TITLE
Unexpected behavior for zeroExtend / concat on signed bitvectors with a negative concrete value

### ISSUE THREAD

**Issue by lsrcz** [LeventErkok/sbv#621]
I noticed that `zeroExtend` would do sign extension if called on signed bitvectors with a concrete negative value.
I expect that the result of the following expression should be `0b01`, or `1 :: SInt 2`, but it returns `0b11` or `-1 :: SInt 2`.
```haskell
GHCi> zeroExtend (-1 :: SInt 1) :: SInt 2
-1 :: SInt 2
```

The behavior on concrete / symbolic values are inconsistent. The following solver query is unsatisfiable, but calling it on `-1` returns `True`.
```haskell
GHCi let q = \(x :: SInt 1) -> zeroExtend x .== (-1 :: SInt 2)
GHCi> sat q
Unsatisfiable
GHCi> q $ -1
True
```

**Comment by lsrcz** [comment]
I noticed that bit vector concatenation gives unexpected behaviors too. See the following code.

```haskell
GHCi> (0 :: SInt 1) # (-1 :: SInt 1)
-1 :: SInt 2
```

I noticed that `zeroExtend` and `concatenation` are both implemented with `svJoin`, so these should be the same issue.

**Comment by LeventErkok** [comment]
@lsrcz Good catch..

I pushed in a fix; can you do some testing for the corner cases and let me know if it works?

If you're so inclined, I'd also welcome adding a few test cases to https://github.com/LeventErkok/sbv/blob/master/SBVTestSuite/TestSuite/Basics/ArithSolver.hs

It'd be good to have these corner cases in the test-suite..

**Comment by lsrcz** [comment]
Sure! I will try to read the test case formats and add some test cases later. Thank you for your fix!

**Comment by lsrcz** [comment]
Hi Levent, I have created a PR #622 adding the test cases to the test suite. Please review it. Thanks!
