### ISSUE TITLE
Version 10.0+ does not build with GHC 9.0

### ISSUE THREAD

**Issue by lsrcz** [LeventErkok/sbv#655]
The version 10.0+ contains a new example `Documentation.SBV.Examples.Puzzles.Orangutans`, which uses the `OverloadedRecordDot` extension.

The extension is nice but it is GHC 9.2+ only..

**Comment by LeventErkok** [comment]
That’s unfortunate indeed. Alas, I don’t try to support all GHC variants, as trying to do so is an endless task.

if this is a problem for you, I’d recommend getting a local copy and modifying it to either remove the example completely or rewrite it to avoid the overloaded record dot, and use that local version.

**Comment by lsrcz** [comment]
Thanks for the explanation and that makes sense.

However, it could be helpful to also update the base dependency version to represent this decision to avoid confusion.

**Comment by LeventErkok** [comment]
That’s a good point. Do you mind sending a PR that does that? I’ll be happy to merge!

**Comment by LeventErkok** [comment]
Waiting for PR to fix the dependency. Thanks.

**Comment by LeventErkok** [comment]
PR merged.
