### ISSUE TITLE
Build fails on GHC 9.8.1

### ISSUE THREAD

**Issue by noughtmare** [LeventErkok/sbv#674]
I'm getting this error:

```none
Data/SBV/Core/AlgReals.hs:101:22: error: [GHC-63394] [-Wx-partial, -Werror=x-partial]
    In the use of ‘head’
    (imported from Prelude, but defined in GHC.List):
    "This is a partial function, it throws an error on empty lists. Use pattern matching or Data.List.uncons instead. Consider refactoring to use Data.List.NonEmpty."
    |
101 |      where c  = -1 * head ([k | (k, 0) <- xs] ++ [0])
    |                      ^^^^
```

**Comment by noughtmare** [comment]
Nevermind, this is already fixed on master.

**Comment by noughtmare** [comment]
But maybe an upper bound should be added on Hackage?

**Comment by LeventErkok** [comment]
I'm waiting for a few fixes to z3 to become available; after that there'll be a new release; hopefully within a few weeks.

**Comment by noughtmare** [comment]
It still might be nice to make a Hackage revision of the existing versions with a tighter upper bound on base. Otherwise cabal might still try to fall back on broken versions even when the new version is release.

**Comment by LeventErkok** [comment]
sure.. can you go ahead and make the revision on hackage? I'm not exactly sure what the steps are for doing so.

**Comment by noughtmare** [comment]
Only maintainers and Hackage trustees can do it.

You'd need to go to https://hackage.haskell.org/package/sbv/maintain and look under the heading "Cabal file metadata" and click on one of the versions of the package listed there. Then you'll see a text area to edit the cabal file where you can change the upper bound.

But really you'd have to do this for all versions to avoid cabal falling back on older versions. That could be a bit of effort, I don't know if that is worth it.

@Bodigrim you're a trustee and have contributed to sbv before. What do you think the best course of action is?

**Comment by Bodigrim** [comment]
> But really you'd have to do this for all versions to avoid cabal falling back on older versions. That could be a bit of effort, I don't know if that is worth it.

Certainly worth doing. If manual update is a bottleneck, https://hackage.haskell.org/package/hackage-cli allows for bulk update of all Cabal files.

**Comment by Bodigrim** [comment]
Bear with me, I'll make the revisions...

**Comment by LeventErkok** [comment]
@Bodigrim Thanks!

**Comment by Bodigrim** [comment]
Should be better now. @noughtmare could you please check?

**Comment by noughtmare** [comment]
@Bodigrim, it works. Cabal now fails when trying to resolve dependencies. Unfortunately the error message is not very helpful, but that's on cabal.

**Comment by LeventErkok** [comment]
Thanks @noughtmare @Bodigrim Much appreciated.
