### ISSUE TITLE
Re-enable sbv on stackage

### ISSUE THREAD

**Issue by lsrcz** [LeventErkok/sbv#680]
Hi @LeventErkok, this package has been disabled in the stackage nightly snapshot due to bound issues on `base`, but it seems that `sbv-10.3` release has resolved that. Could you please re-enable it on stackage?

**Comment by LeventErkok** [comment]
I'd be happy to; but I do not use stackage, nor I know how to "enable" it. If you can send me instructions on how to do so, I can do it. (Or feel free to go ahead and enable it yourself, if you are able to do so.)

**Comment by lsrcz** [comment]
I saw that you are listed as the maintainer on stackage at https://github.com/commercialhaskell/stackage/blob/5fc13f8d3124ec0d0f9751724638c4c7edaa6254/build-constraints.yaml#L4166, so I thought that I should ask you to do this.

I can send the pull request for the re-enabling, but I am unsure whether I can do it because I am not the maintainer. Let me mention this issue there to see what people say.

**Comment by LeventErkok** [comment]
I added a pull request that should resolve this I suppose: https://github.com/commercialhaskell/stackage/pull/7277

I'm closing the ticket; let me know if the stackage process doesn't go through for some reason.

**Comment by lsrcz** [comment]
Thank you!
