### ISSUE TITLE
GH pages link leads to 404

### ISSUE THREAD

**Issue by fabeulous** [LeventErkok/sbv#686]
When following the link (http://leventerkok.github.io/sbv/) in the 'about' part of the repo I get a 404 not found message. Either there's something wrong with the gh-pages setup, or if the page is no longer maintained the link could be removed.

**Comment by LeventErkok** [comment]
Indeed; the GitHub-pages is no longer maintained; the content of which I moved to the README.md instead. Thanks for pointing out the stray link. Removed now.
