### ISSUE TITLE
Zombie process fixes

### ISSUE THREAD

**Issue by LeventErkok** [LeventErkok/sbv#694]
@lsrcz 

Hi,

I ran the test-suite on your pull request. Alas, I got test failures.  You can replicate one of them by running:

```
make test TGT=exceptionRemote1
```

(There are three failures that I can see. I can run the whole test suite if you can get the above passing.)

I reverted the changes, so GitHub master head is the old version.

I'll leave this here so you can investigate yourself to see perhaps you didn't need this change exactly? Having a clean test-suite is important and when an exception happens it's good to have the report more accurate. (If you run the above test you'll see the change in behavior; new error message is much more cryptic.)

**Comment by LeventErkok** [comment]
Note: From what I can tell, the changes you put in changes the way exceptions are processed. Perhaps this isn't that surprising. But we need to find a way so the exceptions are processed in a reliable way, as it changes the error messages users see. (As exemplified by `make test TGT=exceptionRemote1`.) This order is important to maintain.

**Comment by lsrcz** [comment]
Hi @LeventErkok, thank you for pointing this out. I will have a look at the test failures and see whether I can do something with it.

**Comment by lsrcz** [comment]
Hi @LeventErkok, please see #695 for a new fix. This version should pass `exceptionRemote1`.

**Comment by LeventErkok** [comment]
Great! https://hackage.haskell.org/package/sbv-10.10 is now on hackage that contains your fix.

**Comment by lsrcz** [comment]
Great! Thank you.
