### ISSUE TITLE
Generating `Num (SBV a)` instances "generically"

### ISSUE THREAD

**Issue by andreasabel** [LeventErkok/sbv#698]
(This is my first attempt to use `sbv`.)

I am hitting an _impossible_ in `sbv-10.10` in the internal `sh` function:
```
$ git clone git@github.com:andreasabel/sbv-quarter-circle-puzzle.git
$ cd sbv-*
$ git checkout bug-impossible-sh
$ stack run
...
puzzle-two: SBV.SMT.SMTLib2.cvtExp.sh: impossible happened; can't translate: s5 + s8
CallStack (from HasCallStack):
  error, called at ./Data/SBV/SMT/SMTLib2.hs:1113:18 in sbv-10.10-BssX0E5CD3cIV1ObcQi2gZ:Data.SBV.SMT.SMTLib2
```

**Comment by andreasabel** [comment]
It seems like `svb` chokes on a use of `sum`: https://github.com/andreasabel/sbv-quarter-circle-puzzle/blob/4a5a629191595e189e7b3df009800f34a9a1e0e0/Main.hs#L117-L118
```haskell
boardVal :: Color -> Board -> SBV Val
boardVal i = sum . concat . map (map (squareVal i))
```

**Comment by andreasabel** [comment]
Indeed, here is an shrinking to a use of `sum`:
```haskell
import Data.SBV

type Val = (Integer, Integer)

instance Num Val where
  fromInteger i       = (i, 0)
  negate (x, y)       = (negate x, negate y)
  (x1, y1) + (x2, y2) = (x1 + x2, y1 + y2)
  (*)    = undefined
  abs    = undefined
  signum = undefined

type SVal = SBV Val

valVec :: Int -> Symbolic [SVal]
valVec n = mapM (\ k -> symbolic ("X" ++ show k)) [0..n-1]

main = satWith z3{ verbose = True } $ do
  v <- valVec 3
  pure $ sum v .== 1
```

**Comment by andreasabel** [comment]
This is my final shrinking, to just a use of `+` on tuples:
```haskell
import Data.SBV

type Val = (Integer, Integer)

instance Num Val where
  fromInteger i       = (i, 0)
  (x1, y1) + (x2, y2) = (x1 + x2, y1 + y2)
  (*)    = undefined
  abs    = undefined
  negate = undefined
  signum = undefined

main = satWith z3{ verbose = True } $ do
  x :: SBV Val <- symbolic "x"
  y :: SBV Val <- symbolic "y"
  pure $ x + y .== 1
```

**Comment by andreasabel** [comment]
Hello Levent,

thank you for your quick answer and the explanation.

Maybe the `Num (SBV a)` instance is too general?  I guess the typical Haskeller trusts in the "if it type-checks, it works" paradigm, so getting a crash due to an invalid operation for a well-typed program is unexpected.

Would it make sense to restrict this instance to the types where it works correctly?  E.g. I would have gotten an error "no instance for `Num (SBV (Integer, Integer))`" then.
https://github.com/LeventErkok/sbv/blob/720255d2a843b146d248720036a986917ee62041/Data/SBV/Core/Model.hs#L1322-L1329
(Due to limited expressivity of the Haskell class system, this would probably lead to tons of boilerplate...)

**Comment by LeventErkok** [comment]
Thanks Andreas..

You're absolutely right that `Num a => Num (SBV a)` is way too general. But it does handle most of the basic types (WordN, IntN, Float, Double, Int, BigFloat..) out of the box,  and I don't know how to define it for all the internal types without a lot of boilerplate. Maybe template-haskell can help? If you can pull that off (via template-haskell or not), I'd be thrilled to take a PR if you can pull that off.

The other difficulty is that the `instance Num Val` definition needed to make this work isn't that easy to come up with. (The definition is easy enough, but you have to know exactly how the underlying type is lifted; which is probably too much to ask from an end-user. In fact, the whole point of SBV is that you don't need to know how that is done. But I digress.)

I'm open to enhancements here. Ideas/explorations/Pull-Requests are most welcome.

**Comment by LeventErkok** [comment]
I think we can close this ticket. I captured the exploration of removal of the `Num a => Num (SBV a)` instance in a separate ticket (https://github.com/LeventErkok/sbv/issues/706). I'm not sure what the exact design there will be, but I think it's worthy of exploration.

**Comment by andreasabel** [comment]
Thanks for further digging into this issue @LeventErkok.

> You're an expert in generic programming;

You are flattering me.  :-)
When it comes to Haskell, I unfortunately have zero experience with generic programming.
(When it comes to theory, I could lecture how to use hand-rolled universes to get generic programming for "free" with dependent types, but this is hardly helpful here...)

**Comment by LeventErkok** [comment]
Yeah, I was thinking about it myself and there doesn't seem to be an easy way to do this to lift an "existing" instance. Maybe via template-haskell, but I don't think the complexity is worth it.
