### ISSUE TITLE
Unsound term simplification for ite with SFloatingPoint

### ISSUE THREAD

**Issue by lsrcz** [LeventErkok/sbv#702]
The following code demonstrates the problem. It is falsifiable with the counter-example `x = False`.

```haskell
ghci> prove $ \x -> ite x (-infinity :: SFloatingPoint 8 24) infinity .== -infinity
Q.E.D.
```

**Comment by LeventErkok** [comment]
Yeah, that’s no good. I’ll take a look tomorrow AM.

**Comment by lsrcz** [comment]
I believe that I’ve understood what’s happening.

https://github.com/LeventErkok/sbv/blob/720255d2a843b146d248720036a986917ee62041/Data/SBV/Core/SizedFloats.hs#L226-L233

The newly added arbFPIsEqualObjectH function has a clause that tests whether the lhs is inf, and if so, return whether the rhs is inf. This will make +/-inf equal.

I believe that we don’t need to handle inf specially, but we can just use the == operator. What do you think? I can send a fix for it, but no hurry to review it.
