### ISSUE TITLE
`checkSatWith` in analogy to `satWith`

### ISSUE THREAD

**Issue by andreasabel** [LeventErkok/sbv#715]
It is easy to get debug output by swapping `sat` for `satWith`. https://hackage.haskell.org/package/sbv-10.10/docs/Data-SBV.html#v:satWith

Would be great to have a similarly comfortable `checkSatWith` that complements `checkSat`: https://hackage.haskell.org/package/sbv-10.10/docs/Data-SBV-Control.html#v:checkSat

I didn't find a way to set the `SMTConfig` record in the `Query` monad so that it would be used for `checkSat`.  But maybe it is easy and I just got lost in the API?

**Comment by LeventErkok** [comment]
When you have a query, it's wrapped up in a call to [`runSMT`](https://hackage.haskell.org/package/sbv-10.10/docs/Data-SBV.html#v:runSMT), right? That's where you should be configuring the solver, by using [runSMTWith](https://hackage.haskell.org/package/sbv-10.10/docs/Data-SBV.html#v:runSMTWith) and passing `z3{verbose=True}`.

Does that not work for you?

**Comment by LeventErkok** [comment]
@andreasabel Is this addressed? If so, I'd like to close the ticket. Cheers..

**Comment by LeventErkok** [comment]
I think this is handled with the `runSMTWith` call. Feel free to re-open if you still have issues.
