### ISSUE TITLE
Split SymWord into two classes

### ISSUE THREAD

**Issue by Mathnerd314** [LeventErkok/sbv#92]
Currently most of ``SymWord``'s functions produce values of type ``Symbolic (SBV a)``. However, some functions do not, such as ``literal``, ``fromCW``, and ``mbMaxBound``; they deal directly with types ``a`` and ``SBV a``.

I suggest splitting SymWord into two classes (say, SymWord and Sym) based along this division:
```haskell
class (HasKind a, Ord a) => SymWord a where
  literal :: a -> SBV a
  unliteral :: SBV a -> Maybe a
  fromCW :: CW -> a
  isConcretely :: SBV a -> (a -> Bool) -> Bool
  isConcrete :: SBV a -> Bool
  isSymbolic :: SBV a -> Bool
  mbMaxBound, mbMinBound :: Maybe a

class Sym a where
  forall :: String -> Symbolic a
  forall_ :: Symbolic a
  mkForallVars :: Int -> Symbolic [a]
  exists  :: String -> Symbolic a
  exists_ :: Symbolic a
  mkExistVars :: Int -> Symbolic [a]
  free :: String -> Symbolic a
  free_ :: Symbolic a
  mkFreeVars :: Int -> Symbolic [a]
  symbolic  :: String -> Symbolic a
  symbolics :: [String] -> Symbolic [a]
  {-# MINIMAL mkSym #-}
  mkSym :: Maybe Quantifier -> Maybe String -> Symbolic a
```
Then ``Bool``, ``Double``, etc. can be instances of ``SymWord``; ``SBool``, ``SDouble``, etc. can be instances of ``Sym``; and higher-level types such as ``(SBool,SBool)`` can be instances of ``Sym`` as well. The semantics is that ``free "blah"`` generates two variables, ``blah_1`` and ``blah_2``, returned as a tuple.

**Comment by LeventErkok** [comment]
Closing this ticket as it's unlikely to be addressed; though it would be nice to have had this in the first place, lack of actual need overrides the cost of refactoring at this point.
